-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d_3x3 is
port (
    data_in_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    data_in_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    data_in_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    data_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    data_out_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    data_out_TKEEP : OUT STD_LOGIC_VECTOR (7 downto 0);
    data_out_TSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    data_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    data_in_TVALID : IN STD_LOGIC;
    data_in_TREADY : OUT STD_LOGIC;
    data_out_TVALID : OUT STD_LOGIC;
    data_out_TREADY : IN STD_LOGIC );
end;


architecture behav of conv2d_3x3 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "conv2d_3x3_conv2d_3x3,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu1cg-sbva484-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.304750,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=30,HLS_SYN_DSP=0,HLS_SYN_FF=3194,HLS_SYN_LUT=8490,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal data_unpacket_U0_ap_start : STD_LOGIC;
    signal data_unpacket_U0_ap_done : STD_LOGIC;
    signal data_unpacket_U0_ap_continue : STD_LOGIC;
    signal data_unpacket_U0_ap_idle : STD_LOGIC;
    signal data_unpacket_U0_ap_ready : STD_LOGIC;
    signal data_unpacket_U0_input_r_din : STD_LOGIC_VECTOR (79 downto 0);
    signal data_unpacket_U0_input_r_write : STD_LOGIC;
    signal data_unpacket_U0_data_in_TREADY : STD_LOGIC;
    signal image_filter_U0_ap_start : STD_LOGIC;
    signal image_filter_U0_ap_done : STD_LOGIC;
    signal image_filter_U0_ap_continue : STD_LOGIC;
    signal image_filter_U0_ap_idle : STD_LOGIC;
    signal image_filter_U0_ap_ready : STD_LOGIC;
    signal image_filter_U0_input_r_read : STD_LOGIC;
    signal image_filter_U0_output_r_din : STD_LOGIC_VECTOR (79 downto 0);
    signal image_filter_U0_output_r_write : STD_LOGIC;
    signal data_packet_U0_ap_start : STD_LOGIC;
    signal data_packet_U0_ap_done : STD_LOGIC;
    signal data_packet_U0_ap_continue : STD_LOGIC;
    signal data_packet_U0_ap_idle : STD_LOGIC;
    signal data_packet_U0_ap_ready : STD_LOGIC;
    signal data_packet_U0_output_r_read : STD_LOGIC;
    signal data_packet_U0_data_out_TDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal data_packet_U0_data_out_TVALID : STD_LOGIC;
    signal data_packet_U0_data_out_TKEEP : STD_LOGIC_VECTOR (7 downto 0);
    signal data_packet_U0_data_out_TSTRB : STD_LOGIC_VECTOR (7 downto 0);
    signal data_packet_U0_data_out_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal input_r_full_n : STD_LOGIC;
    signal input_r_dout : STD_LOGIC_VECTOR (79 downto 0);
    signal input_r_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal input_r_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal input_r_empty_n : STD_LOGIC;
    signal output_r_full_n : STD_LOGIC;
    signal output_r_dout : STD_LOGIC_VECTOR (79 downto 0);
    signal output_r_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal output_r_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal output_r_empty_n : STD_LOGIC;

    component conv2d_3x3_data_unpacket IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_in_TVALID : IN STD_LOGIC;
        input_r_din : OUT STD_LOGIC_VECTOR (79 downto 0);
        input_r_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        input_r_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        input_r_full_n : IN STD_LOGIC;
        input_r_write : OUT STD_LOGIC;
        data_in_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        data_in_TREADY : OUT STD_LOGIC;
        data_in_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
        data_in_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
        data_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component conv2d_3x3_image_filter IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_r_dout : IN STD_LOGIC_VECTOR (79 downto 0);
        input_r_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        input_r_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        input_r_empty_n : IN STD_LOGIC;
        input_r_read : OUT STD_LOGIC;
        output_r_din : OUT STD_LOGIC_VECTOR (79 downto 0);
        output_r_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        output_r_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        output_r_full_n : IN STD_LOGIC;
        output_r_write : OUT STD_LOGIC );
    end component;


    component conv2d_3x3_data_packet IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        output_r_dout : IN STD_LOGIC_VECTOR (79 downto 0);
        output_r_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        output_r_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        output_r_empty_n : IN STD_LOGIC;
        output_r_read : OUT STD_LOGIC;
        data_out_TREADY : IN STD_LOGIC;
        data_out_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        data_out_TVALID : OUT STD_LOGIC;
        data_out_TKEEP : OUT STD_LOGIC_VECTOR (7 downto 0);
        data_out_TSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
        data_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component conv2d_3x3_fifo_w80_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (79 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (79 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    data_unpacket_U0 : component conv2d_3x3_data_unpacket
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => data_unpacket_U0_ap_start,
        ap_done => data_unpacket_U0_ap_done,
        ap_continue => data_unpacket_U0_ap_continue,
        ap_idle => data_unpacket_U0_ap_idle,
        ap_ready => data_unpacket_U0_ap_ready,
        data_in_TVALID => data_in_TVALID,
        input_r_din => data_unpacket_U0_input_r_din,
        input_r_num_data_valid => input_r_num_data_valid,
        input_r_fifo_cap => input_r_fifo_cap,
        input_r_full_n => input_r_full_n,
        input_r_write => data_unpacket_U0_input_r_write,
        data_in_TDATA => data_in_TDATA,
        data_in_TREADY => data_unpacket_U0_data_in_TREADY,
        data_in_TKEEP => data_in_TKEEP,
        data_in_TSTRB => data_in_TSTRB,
        data_in_TLAST => data_in_TLAST);

    image_filter_U0 : component conv2d_3x3_image_filter
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => image_filter_U0_ap_start,
        ap_done => image_filter_U0_ap_done,
        ap_continue => image_filter_U0_ap_continue,
        ap_idle => image_filter_U0_ap_idle,
        ap_ready => image_filter_U0_ap_ready,
        input_r_dout => input_r_dout,
        input_r_num_data_valid => input_r_num_data_valid,
        input_r_fifo_cap => input_r_fifo_cap,
        input_r_empty_n => input_r_empty_n,
        input_r_read => image_filter_U0_input_r_read,
        output_r_din => image_filter_U0_output_r_din,
        output_r_num_data_valid => output_r_num_data_valid,
        output_r_fifo_cap => output_r_fifo_cap,
        output_r_full_n => output_r_full_n,
        output_r_write => image_filter_U0_output_r_write);

    data_packet_U0 : component conv2d_3x3_data_packet
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => data_packet_U0_ap_start,
        ap_done => data_packet_U0_ap_done,
        ap_continue => data_packet_U0_ap_continue,
        ap_idle => data_packet_U0_ap_idle,
        ap_ready => data_packet_U0_ap_ready,
        output_r_dout => output_r_dout,
        output_r_num_data_valid => output_r_num_data_valid,
        output_r_fifo_cap => output_r_fifo_cap,
        output_r_empty_n => output_r_empty_n,
        output_r_read => data_packet_U0_output_r_read,
        data_out_TREADY => data_out_TREADY,
        data_out_TDATA => data_packet_U0_data_out_TDATA,
        data_out_TVALID => data_packet_U0_data_out_TVALID,
        data_out_TKEEP => data_packet_U0_data_out_TKEEP,
        data_out_TSTRB => data_packet_U0_data_out_TSTRB,
        data_out_TLAST => data_packet_U0_data_out_TLAST);

    input_r_U : component conv2d_3x3_fifo_w80_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => data_unpacket_U0_input_r_din,
        if_full_n => input_r_full_n,
        if_write => data_unpacket_U0_input_r_write,
        if_dout => input_r_dout,
        if_num_data_valid => input_r_num_data_valid,
        if_fifo_cap => input_r_fifo_cap,
        if_empty_n => input_r_empty_n,
        if_read => image_filter_U0_input_r_read);

    output_r_U : component conv2d_3x3_fifo_w80_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => image_filter_U0_output_r_din,
        if_full_n => output_r_full_n,
        if_write => image_filter_U0_output_r_write,
        if_dout => output_r_dout,
        if_num_data_valid => output_r_num_data_valid,
        if_fifo_cap => output_r_fifo_cap,
        if_empty_n => output_r_empty_n,
        if_read => data_packet_U0_output_r_read);





    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    data_in_TREADY <= data_unpacket_U0_data_in_TREADY;
    data_out_TDATA <= data_packet_U0_data_out_TDATA;
    data_out_TKEEP <= data_packet_U0_data_out_TKEEP;
    data_out_TLAST <= data_packet_U0_data_out_TLAST;
    data_out_TSTRB <= data_packet_U0_data_out_TSTRB;
    data_out_TVALID <= data_packet_U0_data_out_TVALID;
    data_packet_U0_ap_continue <= ap_const_logic_1;
    data_packet_U0_ap_start <= ap_const_logic_1;
    data_unpacket_U0_ap_continue <= ap_const_logic_1;
    data_unpacket_U0_ap_start <= ap_const_logic_1;
    image_filter_U0_ap_continue <= ap_const_logic_1;
    image_filter_U0_ap_start <= ap_const_logic_1;
end behav;
