-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d_3x3_sobelConvolve is
port (
    ap_ready : OUT STD_LOGIC;
    window_adjust_0_0_0 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_2_0 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_0_0 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_2_0 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_0_0 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_2_0 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_0_1 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_2_1 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_0_1 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_2_1 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_0_1 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_2_1 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_0_2 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_2_2 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_0_2 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_2_2 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_0_2 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_2_2 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_0_3 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_2_3 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_0_3 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_2_3 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_0_3 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_2_3 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_0_4 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_2_4 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_0_4 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_2_4 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_0_4 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_2_4 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_0_5 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_2_5 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_0_5 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_2_5 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_0_5 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_2_5 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_0_6 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_2_6 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_0_6 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_2_6 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_0_6 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_2_6 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_0_7 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_0_2_7 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_0_7 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_1_2_7 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_0_7 : IN STD_LOGIC_VECTOR (9 downto 0);
    window_adjust_2_2_7 : IN STD_LOGIC_VECTOR (9 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (79 downto 0) );
end;


architecture behav of conv2d_3x3_sobelConvolve is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal zext_ln41_3_fu_150_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln41_2_fu_142_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_i_fu_162_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_fu_168_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_172_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln41_1_fu_134_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln41_fu_126_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln41_fu_192_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln41_fu_198_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal window_adjust_2_0_0_load_cast_i_fu_158_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln41_1_fu_202_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln41_4_fu_212_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln41_fu_216_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln41_fu_222_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_cast_fu_180_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln41_3_fu_226_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln41_1_fu_188_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln41_1_fu_236_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln44_8_fu_242_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_fu_254_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_246_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_fu_284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_8_fu_276_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln44_fu_230_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln41_8_fu_326_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln41_7_fu_318_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp83_i_fu_338_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_25_fu_344_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_1_fu_348_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln41_6_fu_310_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln41_5_fu_302_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln41_2_fu_368_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln41_2_fu_374_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal window_adjust_2_0_1_load_cast_i_fu_334_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln41_3_fu_378_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln41_9_fu_388_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln41_2_fu_392_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln41_1_fu_398_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_1_cast_fu_356_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln41_7_fu_402_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln41_5_fu_364_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln41_3_fu_412_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln44_fu_418_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_fu_430_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_10_fu_422_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_1_fu_446_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_1_fu_440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_1_fu_460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_9_fu_452_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln44_1_fu_406_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln41_13_fu_502_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln41_12_fu_494_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp86_i_fu_514_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_26_fu_520_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_2_fu_524_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln41_11_fu_486_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln41_10_fu_478_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln41_4_fu_544_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln41_4_fu_550_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal window_adjust_2_0_2_load_cast_i_fu_510_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln41_5_fu_554_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln41_14_fu_564_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln41_4_fu_568_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln41_2_fu_574_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_2_cast_fu_532_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln41_11_fu_578_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln41_9_fu_540_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln41_5_fu_588_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln44_9_fu_594_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_13_fu_606_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_12_fu_598_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_2_fu_622_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_2_fu_616_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_2_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_10_fu_628_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln44_2_fu_582_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln41_18_fu_678_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln41_17_fu_670_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp89_i_fu_690_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_27_fu_696_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_3_fu_700_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln41_16_fu_662_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln41_15_fu_654_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln41_6_fu_720_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln41_6_fu_726_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal window_adjust_2_0_3_load_cast_i_fu_686_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln41_7_fu_730_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln41_19_fu_740_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln41_6_fu_744_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln41_3_fu_750_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_3_cast_fu_708_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln41_15_fu_754_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln41_13_fu_716_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln41_7_fu_764_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln44_10_fu_770_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_15_fu_782_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_fu_774_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_3_fu_798_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_3_fu_792_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_3_fu_812_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_11_fu_804_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln44_3_fu_758_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln41_23_fu_854_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln41_22_fu_846_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp92_i_fu_866_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_28_fu_872_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_4_fu_876_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln41_21_fu_838_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln41_20_fu_830_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln41_8_fu_896_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln41_8_fu_902_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal window_adjust_2_0_4_load_cast_i_fu_862_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln41_9_fu_906_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln41_24_fu_916_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln41_8_fu_920_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln41_4_fu_926_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_4_cast_fu_884_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln41_17_fu_930_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln41_16_fu_892_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln41_9_fu_940_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln44_11_fu_946_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_17_fu_958_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_16_fu_950_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_4_fu_974_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_4_fu_968_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_4_fu_988_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_12_fu_980_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln44_4_fu_934_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln41_28_fu_1030_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln41_27_fu_1022_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp95_i_fu_1042_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_29_fu_1048_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_5_fu_1052_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln41_26_fu_1014_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln41_25_fu_1006_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln41_10_fu_1072_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln41_10_fu_1078_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal window_adjust_2_0_5_load_cast_i_fu_1038_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln41_11_fu_1082_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln41_29_fu_1092_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln41_10_fu_1096_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln41_5_fu_1102_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_5_cast_fu_1060_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln41_19_fu_1106_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln41_18_fu_1068_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln41_11_fu_1116_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln44_12_fu_1122_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_19_fu_1134_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_18_fu_1126_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_5_fu_1150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_5_fu_1144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_5_fu_1164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_13_fu_1156_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln44_5_fu_1110_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln41_33_fu_1206_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln41_32_fu_1198_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp98_i_fu_1218_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_30_fu_1224_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_6_fu_1228_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln41_31_fu_1190_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln41_30_fu_1182_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln41_12_fu_1248_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln41_12_fu_1254_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal window_adjust_2_0_6_load_cast_i_fu_1214_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln41_13_fu_1258_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln41_34_fu_1268_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln41_12_fu_1272_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln41_6_fu_1278_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_6_cast_fu_1236_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln41_21_fu_1282_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln41_20_fu_1244_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln41_13_fu_1292_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln44_13_fu_1298_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_21_fu_1310_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_20_fu_1302_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_6_fu_1326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_6_fu_1320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_6_fu_1340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_14_fu_1332_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln44_6_fu_1286_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln41_38_fu_1382_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln41_37_fu_1374_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp101_i_fu_1394_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_31_fu_1400_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_7_fu_1404_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln41_36_fu_1366_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln41_35_fu_1358_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln41_14_fu_1424_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln41_14_fu_1430_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal window_adjust_2_0_7_load_cast_i_fu_1390_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln41_15_fu_1434_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln41_39_fu_1444_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln41_14_fu_1448_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln41_7_fu_1454_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_7_cast_fu_1412_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln41_23_fu_1458_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln41_22_fu_1420_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln41_15_fu_1468_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln44_14_fu_1474_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_23_fu_1486_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_22_fu_1478_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_7_fu_1502_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_7_fu_1496_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_7_fu_1516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_15_fu_1508_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln44_7_fu_1462_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln44_fu_290_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln44_1_fu_466_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln44_2_fu_642_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln44_3_fu_818_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln44_4_fu_994_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln44_5_fu_1170_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln44_6_fu_1346_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln44_7_fu_1522_p3 : STD_LOGIC_VECTOR (9 downto 0);


begin



    add_ln41_10_fu_1096_p2 <= std_logic_vector(unsigned(sub_ln41_11_fu_1082_p2) + unsigned(zext_ln41_29_fu_1092_p1));
    add_ln41_11_fu_1116_p2 <= std_logic_vector(signed(sext_ln41_19_fu_1106_p1) + signed(sext_ln41_18_fu_1068_p1));
    add_ln41_12_fu_1272_p2 <= std_logic_vector(unsigned(sub_ln41_13_fu_1258_p2) + unsigned(zext_ln41_34_fu_1268_p1));
    add_ln41_13_fu_1292_p2 <= std_logic_vector(signed(sext_ln41_21_fu_1282_p1) + signed(sext_ln41_20_fu_1244_p1));
    add_ln41_14_fu_1448_p2 <= std_logic_vector(unsigned(sub_ln41_15_fu_1434_p2) + unsigned(zext_ln41_39_fu_1444_p1));
    add_ln41_15_fu_1468_p2 <= std_logic_vector(signed(sext_ln41_23_fu_1458_p1) + signed(sext_ln41_22_fu_1420_p1));
    add_ln41_1_fu_236_p2 <= std_logic_vector(signed(sext_ln41_3_fu_226_p1) + signed(sext_ln41_1_fu_188_p1));
    add_ln41_2_fu_392_p2 <= std_logic_vector(unsigned(sub_ln41_3_fu_378_p2) + unsigned(zext_ln41_9_fu_388_p1));
    add_ln41_3_fu_412_p2 <= std_logic_vector(signed(sext_ln41_7_fu_402_p1) + signed(sext_ln41_5_fu_364_p1));
    add_ln41_4_fu_568_p2 <= std_logic_vector(unsigned(sub_ln41_5_fu_554_p2) + unsigned(zext_ln41_14_fu_564_p1));
    add_ln41_5_fu_588_p2 <= std_logic_vector(signed(sext_ln41_11_fu_578_p1) + signed(sext_ln41_9_fu_540_p1));
    add_ln41_6_fu_744_p2 <= std_logic_vector(unsigned(sub_ln41_7_fu_730_p2) + unsigned(zext_ln41_19_fu_740_p1));
    add_ln41_7_fu_764_p2 <= std_logic_vector(signed(sext_ln41_15_fu_754_p1) + signed(sext_ln41_13_fu_716_p1));
    add_ln41_8_fu_920_p2 <= std_logic_vector(unsigned(sub_ln41_9_fu_906_p2) + unsigned(zext_ln41_24_fu_916_p1));
    add_ln41_9_fu_940_p2 <= std_logic_vector(signed(sext_ln41_17_fu_930_p1) + signed(sext_ln41_16_fu_892_p1));
    add_ln41_fu_216_p2 <= std_logic_vector(unsigned(sub_ln41_1_fu_202_p2) + unsigned(zext_ln41_4_fu_212_p1));
    add_ln44_1_fu_406_p2 <= std_logic_vector(unsigned(trunc_ln41_1_fu_398_p1) + unsigned(tmp_1_cast_fu_356_p3));
    add_ln44_2_fu_582_p2 <= std_logic_vector(unsigned(trunc_ln41_2_fu_574_p1) + unsigned(tmp_2_cast_fu_532_p3));
    add_ln44_3_fu_758_p2 <= std_logic_vector(unsigned(trunc_ln41_3_fu_750_p1) + unsigned(tmp_3_cast_fu_708_p3));
    add_ln44_4_fu_934_p2 <= std_logic_vector(unsigned(trunc_ln41_4_fu_926_p1) + unsigned(tmp_4_cast_fu_884_p3));
    add_ln44_5_fu_1110_p2 <= std_logic_vector(unsigned(trunc_ln41_5_fu_1102_p1) + unsigned(tmp_5_cast_fu_1060_p3));
    add_ln44_6_fu_1286_p2 <= std_logic_vector(unsigned(trunc_ln41_6_fu_1278_p1) + unsigned(tmp_6_cast_fu_1236_p3));
    add_ln44_7_fu_1462_p2 <= std_logic_vector(unsigned(trunc_ln41_7_fu_1454_p1) + unsigned(tmp_7_cast_fu_1412_p3));
    add_ln44_fu_230_p2 <= std_logic_vector(unsigned(trunc_ln41_fu_222_p1) + unsigned(tmp_cast_fu_180_p3));
    ap_ready <= ap_const_logic_1;
    ap_return <= (((((((select_ln44_fu_290_p3 & select_ln44_1_fu_466_p3) & select_ln44_2_fu_642_p3) & select_ln44_3_fu_818_p3) & select_ln44_4_fu_994_p3) & select_ln44_5_fu_1170_p3) & select_ln44_6_fu_1346_p3) & select_ln44_7_fu_1522_p3);
    empty_25_fu_344_p1 <= tmp83_i_fu_338_p2(9 - 1 downto 0);
    empty_26_fu_520_p1 <= tmp86_i_fu_514_p2(9 - 1 downto 0);
    empty_27_fu_696_p1 <= tmp89_i_fu_690_p2(9 - 1 downto 0);
    empty_28_fu_872_p1 <= tmp92_i_fu_866_p2(9 - 1 downto 0);
    empty_29_fu_1048_p1 <= tmp95_i_fu_1042_p2(9 - 1 downto 0);
    empty_30_fu_1224_p1 <= tmp98_i_fu_1218_p2(9 - 1 downto 0);
    empty_31_fu_1400_p1 <= tmp101_i_fu_1394_p2(9 - 1 downto 0);
    empty_fu_168_p1 <= tmp_i_fu_162_p2(9 - 1 downto 0);
    icmp_ln46_1_fu_440_p2 <= "1" when (signed(tmp_11_fu_430_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln46_2_fu_616_p2 <= "1" when (signed(tmp_13_fu_606_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln46_3_fu_792_p2 <= "1" when (signed(tmp_15_fu_782_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln46_4_fu_968_p2 <= "1" when (signed(tmp_17_fu_958_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln46_5_fu_1144_p2 <= "1" when (signed(tmp_19_fu_1134_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln46_6_fu_1320_p2 <= "1" when (signed(tmp_21_fu_1310_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln46_7_fu_1496_p2 <= "1" when (signed(tmp_23_fu_1486_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln46_fu_264_p2 <= "1" when (signed(tmp_9_fu_254_p4) > signed(ap_const_lv3_0)) else "0";
    or_ln44_1_fu_460_p2 <= (tmp_10_fu_422_p3 or icmp_ln46_1_fu_440_p2);
    or_ln44_2_fu_636_p2 <= (tmp_12_fu_598_p3 or icmp_ln46_2_fu_616_p2);
    or_ln44_3_fu_812_p2 <= (tmp_14_fu_774_p3 or icmp_ln46_3_fu_792_p2);
    or_ln44_4_fu_988_p2 <= (tmp_16_fu_950_p3 or icmp_ln46_4_fu_968_p2);
    or_ln44_5_fu_1164_p2 <= (tmp_18_fu_1126_p3 or icmp_ln46_5_fu_1144_p2);
    or_ln44_6_fu_1340_p2 <= (tmp_20_fu_1302_p3 or icmp_ln46_6_fu_1320_p2);
    or_ln44_7_fu_1516_p2 <= (tmp_22_fu_1478_p3 or icmp_ln46_7_fu_1496_p2);
    or_ln44_fu_284_p2 <= (tmp_8_fu_246_p3 or icmp_ln46_fu_264_p2);
    select_ln44_10_fu_628_p3 <= 
        ap_const_lv10_3FF when (xor_ln44_2_fu_622_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln44_11_fu_804_p3 <= 
        ap_const_lv10_3FF when (xor_ln44_3_fu_798_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln44_12_fu_980_p3 <= 
        ap_const_lv10_3FF when (xor_ln44_4_fu_974_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln44_13_fu_1156_p3 <= 
        ap_const_lv10_3FF when (xor_ln44_5_fu_1150_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln44_14_fu_1332_p3 <= 
        ap_const_lv10_3FF when (xor_ln44_6_fu_1326_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln44_15_fu_1508_p3 <= 
        ap_const_lv10_3FF when (xor_ln44_7_fu_1502_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln44_1_fu_466_p3 <= 
        select_ln44_9_fu_452_p3 when (or_ln44_1_fu_460_p2(0) = '1') else 
        add_ln44_1_fu_406_p2;
    select_ln44_2_fu_642_p3 <= 
        select_ln44_10_fu_628_p3 when (or_ln44_2_fu_636_p2(0) = '1') else 
        add_ln44_2_fu_582_p2;
    select_ln44_3_fu_818_p3 <= 
        select_ln44_11_fu_804_p3 when (or_ln44_3_fu_812_p2(0) = '1') else 
        add_ln44_3_fu_758_p2;
    select_ln44_4_fu_994_p3 <= 
        select_ln44_12_fu_980_p3 when (or_ln44_4_fu_988_p2(0) = '1') else 
        add_ln44_4_fu_934_p2;
    select_ln44_5_fu_1170_p3 <= 
        select_ln44_13_fu_1156_p3 when (or_ln44_5_fu_1164_p2(0) = '1') else 
        add_ln44_5_fu_1110_p2;
    select_ln44_6_fu_1346_p3 <= 
        select_ln44_14_fu_1332_p3 when (or_ln44_6_fu_1340_p2(0) = '1') else 
        add_ln44_6_fu_1286_p2;
    select_ln44_7_fu_1522_p3 <= 
        select_ln44_15_fu_1508_p3 when (or_ln44_7_fu_1516_p2(0) = '1') else 
        add_ln44_7_fu_1462_p2;
    select_ln44_8_fu_276_p3 <= 
        ap_const_lv10_3FF when (xor_ln44_fu_270_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln44_9_fu_452_p3 <= 
        ap_const_lv10_3FF when (xor_ln44_1_fu_446_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln44_fu_290_p3 <= 
        select_ln44_8_fu_276_p3 when (or_ln44_fu_284_p2(0) = '1') else 
        add_ln44_fu_230_p2;
        sext_ln41_10_fu_1078_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln41_10_fu_1072_p2),12));

        sext_ln41_11_fu_578_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln41_4_fu_568_p2),13));

        sext_ln41_12_fu_1254_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln41_12_fu_1248_p2),12));

        sext_ln41_13_fu_716_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_3_fu_700_p3),13));

        sext_ln41_14_fu_1430_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln41_14_fu_1424_p2),12));

        sext_ln41_15_fu_754_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln41_6_fu_744_p2),13));

        sext_ln41_16_fu_892_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_4_fu_876_p3),13));

        sext_ln41_17_fu_930_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln41_8_fu_920_p2),13));

        sext_ln41_18_fu_1068_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_5_fu_1052_p3),13));

        sext_ln41_19_fu_1106_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln41_10_fu_1096_p2),13));

        sext_ln41_1_fu_188_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_172_p3),13));

        sext_ln41_20_fu_1244_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_6_fu_1228_p3),13));

        sext_ln41_21_fu_1282_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln41_12_fu_1272_p2),13));

        sext_ln41_22_fu_1420_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_7_fu_1404_p3),13));

        sext_ln41_23_fu_1458_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln41_14_fu_1448_p2),13));

        sext_ln41_2_fu_374_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln41_2_fu_368_p2),12));

        sext_ln41_3_fu_226_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln41_fu_216_p2),13));

        sext_ln41_4_fu_550_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln41_4_fu_544_p2),12));

        sext_ln41_5_fu_364_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_fu_348_p3),13));

        sext_ln41_6_fu_726_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln41_6_fu_720_p2),12));

        sext_ln41_7_fu_402_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln41_2_fu_392_p2),13));

        sext_ln41_8_fu_902_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln41_8_fu_896_p2),12));

        sext_ln41_9_fu_540_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_524_p3),13));

        sext_ln41_fu_198_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln41_fu_192_p2),12));

        sext_ln44_10_fu_770_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln41_7_fu_764_p2),32));

        sext_ln44_11_fu_946_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln41_9_fu_940_p2),32));

        sext_ln44_12_fu_1122_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln41_11_fu_1116_p2),32));

        sext_ln44_13_fu_1298_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln41_13_fu_1292_p2),32));

        sext_ln44_14_fu_1474_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln41_15_fu_1468_p2),32));

        sext_ln44_8_fu_242_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln41_1_fu_236_p2),32));

        sext_ln44_9_fu_594_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln41_5_fu_588_p2),32));

        sext_ln44_fu_418_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln41_3_fu_412_p2),32));

    sub_ln41_10_fu_1072_p2 <= std_logic_vector(unsigned(zext_ln41_26_fu_1014_p1) - unsigned(zext_ln41_25_fu_1006_p1));
    sub_ln41_11_fu_1082_p2 <= std_logic_vector(signed(sext_ln41_10_fu_1078_p1) - signed(window_adjust_2_0_5_load_cast_i_fu_1038_p1));
    sub_ln41_12_fu_1248_p2 <= std_logic_vector(unsigned(zext_ln41_31_fu_1190_p1) - unsigned(zext_ln41_30_fu_1182_p1));
    sub_ln41_13_fu_1258_p2 <= std_logic_vector(signed(sext_ln41_12_fu_1254_p1) - signed(window_adjust_2_0_6_load_cast_i_fu_1214_p1));
    sub_ln41_14_fu_1424_p2 <= std_logic_vector(unsigned(zext_ln41_36_fu_1366_p1) - unsigned(zext_ln41_35_fu_1358_p1));
    sub_ln41_15_fu_1434_p2 <= std_logic_vector(signed(sext_ln41_14_fu_1430_p1) - signed(window_adjust_2_0_7_load_cast_i_fu_1390_p1));
    sub_ln41_1_fu_202_p2 <= std_logic_vector(signed(sext_ln41_fu_198_p1) - signed(window_adjust_2_0_0_load_cast_i_fu_158_p1));
    sub_ln41_2_fu_368_p2 <= std_logic_vector(unsigned(zext_ln41_6_fu_310_p1) - unsigned(zext_ln41_5_fu_302_p1));
    sub_ln41_3_fu_378_p2 <= std_logic_vector(signed(sext_ln41_2_fu_374_p1) - signed(window_adjust_2_0_1_load_cast_i_fu_334_p1));
    sub_ln41_4_fu_544_p2 <= std_logic_vector(unsigned(zext_ln41_11_fu_486_p1) - unsigned(zext_ln41_10_fu_478_p1));
    sub_ln41_5_fu_554_p2 <= std_logic_vector(signed(sext_ln41_4_fu_550_p1) - signed(window_adjust_2_0_2_load_cast_i_fu_510_p1));
    sub_ln41_6_fu_720_p2 <= std_logic_vector(unsigned(zext_ln41_16_fu_662_p1) - unsigned(zext_ln41_15_fu_654_p1));
    sub_ln41_7_fu_730_p2 <= std_logic_vector(signed(sext_ln41_6_fu_726_p1) - signed(window_adjust_2_0_3_load_cast_i_fu_686_p1));
    sub_ln41_8_fu_896_p2 <= std_logic_vector(unsigned(zext_ln41_21_fu_838_p1) - unsigned(zext_ln41_20_fu_830_p1));
    sub_ln41_9_fu_906_p2 <= std_logic_vector(signed(sext_ln41_8_fu_902_p1) - signed(window_adjust_2_0_4_load_cast_i_fu_862_p1));
    sub_ln41_fu_192_p2 <= std_logic_vector(unsigned(zext_ln41_1_fu_134_p1) - unsigned(zext_ln41_fu_126_p1));
    tmp101_i_fu_1394_p2 <= std_logic_vector(unsigned(zext_ln41_38_fu_1382_p1) - unsigned(zext_ln41_37_fu_1374_p1));
    tmp83_i_fu_338_p2 <= std_logic_vector(unsigned(zext_ln41_8_fu_326_p1) - unsigned(zext_ln41_7_fu_318_p1));
    tmp86_i_fu_514_p2 <= std_logic_vector(unsigned(zext_ln41_13_fu_502_p1) - unsigned(zext_ln41_12_fu_494_p1));
    tmp89_i_fu_690_p2 <= std_logic_vector(unsigned(zext_ln41_18_fu_678_p1) - unsigned(zext_ln41_17_fu_670_p1));
    tmp92_i_fu_866_p2 <= std_logic_vector(unsigned(zext_ln41_23_fu_854_p1) - unsigned(zext_ln41_22_fu_846_p1));
    tmp95_i_fu_1042_p2 <= std_logic_vector(unsigned(zext_ln41_28_fu_1030_p1) - unsigned(zext_ln41_27_fu_1022_p1));
    tmp98_i_fu_1218_p2 <= std_logic_vector(unsigned(zext_ln41_33_fu_1206_p1) - unsigned(zext_ln41_32_fu_1198_p1));
    tmp_10_fu_422_p3 <= sext_ln44_fu_418_p1(31 downto 31);
    tmp_11_fu_430_p4 <= add_ln41_3_fu_412_p2(12 downto 10);
    tmp_12_fu_598_p3 <= sext_ln44_9_fu_594_p1(31 downto 31);
    tmp_13_fu_606_p4 <= add_ln41_5_fu_588_p2(12 downto 10);
    tmp_14_fu_774_p3 <= sext_ln44_10_fu_770_p1(31 downto 31);
    tmp_15_fu_782_p4 <= add_ln41_7_fu_764_p2(12 downto 10);
    tmp_16_fu_950_p3 <= sext_ln44_11_fu_946_p1(31 downto 31);
    tmp_17_fu_958_p4 <= add_ln41_9_fu_940_p2(12 downto 10);
    tmp_18_fu_1126_p3 <= sext_ln44_12_fu_1122_p1(31 downto 31);
    tmp_19_fu_1134_p4 <= add_ln41_11_fu_1116_p2(12 downto 10);
    tmp_1_cast_fu_356_p3 <= (empty_25_fu_344_p1 & ap_const_lv1_0);
    tmp_1_fu_348_p3 <= (tmp83_i_fu_338_p2 & ap_const_lv1_0);
    tmp_20_fu_1302_p3 <= sext_ln44_13_fu_1298_p1(31 downto 31);
    tmp_21_fu_1310_p4 <= add_ln41_13_fu_1292_p2(12 downto 10);
    tmp_22_fu_1478_p3 <= sext_ln44_14_fu_1474_p1(31 downto 31);
    tmp_23_fu_1486_p4 <= add_ln41_15_fu_1468_p2(12 downto 10);
    tmp_2_cast_fu_532_p3 <= (empty_26_fu_520_p1 & ap_const_lv1_0);
    tmp_2_fu_524_p3 <= (tmp86_i_fu_514_p2 & ap_const_lv1_0);
    tmp_3_cast_fu_708_p3 <= (empty_27_fu_696_p1 & ap_const_lv1_0);
    tmp_3_fu_700_p3 <= (tmp89_i_fu_690_p2 & ap_const_lv1_0);
    tmp_4_cast_fu_884_p3 <= (empty_28_fu_872_p1 & ap_const_lv1_0);
    tmp_4_fu_876_p3 <= (tmp92_i_fu_866_p2 & ap_const_lv1_0);
    tmp_5_cast_fu_1060_p3 <= (empty_29_fu_1048_p1 & ap_const_lv1_0);
    tmp_5_fu_1052_p3 <= (tmp95_i_fu_1042_p2 & ap_const_lv1_0);
    tmp_6_cast_fu_1236_p3 <= (empty_30_fu_1224_p1 & ap_const_lv1_0);
    tmp_6_fu_1228_p3 <= (tmp98_i_fu_1218_p2 & ap_const_lv1_0);
    tmp_7_cast_fu_1412_p3 <= (empty_31_fu_1400_p1 & ap_const_lv1_0);
    tmp_7_fu_1404_p3 <= (tmp101_i_fu_1394_p2 & ap_const_lv1_0);
    tmp_8_fu_246_p3 <= sext_ln44_8_fu_242_p1(31 downto 31);
    tmp_9_fu_254_p4 <= add_ln41_1_fu_236_p2(12 downto 10);
    tmp_cast_fu_180_p3 <= (empty_fu_168_p1 & ap_const_lv1_0);
    tmp_fu_172_p3 <= (tmp_i_fu_162_p2 & ap_const_lv1_0);
    tmp_i_fu_162_p2 <= std_logic_vector(unsigned(zext_ln41_3_fu_150_p1) - unsigned(zext_ln41_2_fu_142_p1));
    trunc_ln41_1_fu_398_p1 <= add_ln41_2_fu_392_p2(10 - 1 downto 0);
    trunc_ln41_2_fu_574_p1 <= add_ln41_4_fu_568_p2(10 - 1 downto 0);
    trunc_ln41_3_fu_750_p1 <= add_ln41_6_fu_744_p2(10 - 1 downto 0);
    trunc_ln41_4_fu_926_p1 <= add_ln41_8_fu_920_p2(10 - 1 downto 0);
    trunc_ln41_5_fu_1102_p1 <= add_ln41_10_fu_1096_p2(10 - 1 downto 0);
    trunc_ln41_6_fu_1278_p1 <= add_ln41_12_fu_1272_p2(10 - 1 downto 0);
    trunc_ln41_7_fu_1454_p1 <= add_ln41_14_fu_1448_p2(10 - 1 downto 0);
    trunc_ln41_fu_222_p1 <= add_ln41_fu_216_p2(10 - 1 downto 0);
    window_adjust_2_0_0_load_cast_i_fu_158_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_0_0),12));
    window_adjust_2_0_1_load_cast_i_fu_334_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_0_1),12));
    window_adjust_2_0_2_load_cast_i_fu_510_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_0_2),12));
    window_adjust_2_0_3_load_cast_i_fu_686_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_0_3),12));
    window_adjust_2_0_4_load_cast_i_fu_862_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_0_4),12));
    window_adjust_2_0_5_load_cast_i_fu_1038_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_0_5),12));
    window_adjust_2_0_6_load_cast_i_fu_1214_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_0_6),12));
    window_adjust_2_0_7_load_cast_i_fu_1390_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_0_7),12));
    xor_ln44_1_fu_446_p2 <= (tmp_10_fu_422_p3 xor ap_const_lv1_1);
    xor_ln44_2_fu_622_p2 <= (tmp_12_fu_598_p3 xor ap_const_lv1_1);
    xor_ln44_3_fu_798_p2 <= (tmp_14_fu_774_p3 xor ap_const_lv1_1);
    xor_ln44_4_fu_974_p2 <= (tmp_16_fu_950_p3 xor ap_const_lv1_1);
    xor_ln44_5_fu_1150_p2 <= (tmp_18_fu_1126_p3 xor ap_const_lv1_1);
    xor_ln44_6_fu_1326_p2 <= (tmp_20_fu_1302_p3 xor ap_const_lv1_1);
    xor_ln44_7_fu_1502_p2 <= (tmp_22_fu_1478_p3 xor ap_const_lv1_1);
    xor_ln44_fu_270_p2 <= (tmp_8_fu_246_p3 xor ap_const_lv1_1);
    zext_ln41_10_fu_478_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_0_2),11));
    zext_ln41_11_fu_486_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_2_2),11));
    zext_ln41_12_fu_494_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_0_2),11));
    zext_ln41_13_fu_502_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_2_2),11));
    zext_ln41_14_fu_564_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_2_2),12));
    zext_ln41_15_fu_654_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_0_3),11));
    zext_ln41_16_fu_662_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_2_3),11));
    zext_ln41_17_fu_670_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_0_3),11));
    zext_ln41_18_fu_678_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_2_3),11));
    zext_ln41_19_fu_740_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_2_3),12));
    zext_ln41_1_fu_134_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_2_0),11));
    zext_ln41_20_fu_830_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_0_4),11));
    zext_ln41_21_fu_838_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_2_4),11));
    zext_ln41_22_fu_846_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_0_4),11));
    zext_ln41_23_fu_854_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_2_4),11));
    zext_ln41_24_fu_916_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_2_4),12));
    zext_ln41_25_fu_1006_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_0_5),11));
    zext_ln41_26_fu_1014_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_2_5),11));
    zext_ln41_27_fu_1022_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_0_5),11));
    zext_ln41_28_fu_1030_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_2_5),11));
    zext_ln41_29_fu_1092_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_2_5),12));
    zext_ln41_2_fu_142_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_0_0),11));
    zext_ln41_30_fu_1182_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_0_6),11));
    zext_ln41_31_fu_1190_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_2_6),11));
    zext_ln41_32_fu_1198_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_0_6),11));
    zext_ln41_33_fu_1206_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_2_6),11));
    zext_ln41_34_fu_1268_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_2_6),12));
    zext_ln41_35_fu_1358_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_0_7),11));
    zext_ln41_36_fu_1366_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_2_7),11));
    zext_ln41_37_fu_1374_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_0_7),11));
    zext_ln41_38_fu_1382_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_2_7),11));
    zext_ln41_39_fu_1444_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_2_7),12));
    zext_ln41_3_fu_150_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_2_0),11));
    zext_ln41_4_fu_212_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_2_0),12));
    zext_ln41_5_fu_302_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_0_1),11));
    zext_ln41_6_fu_310_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_2_1),11));
    zext_ln41_7_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_0_1),11));
    zext_ln41_8_fu_326_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_1_2_1),11));
    zext_ln41_9_fu_388_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_2_2_1),12));
    zext_ln41_fu_126_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_adjust_0_0_0),11));
end behav;
