// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module conv2d_3x3_sobelConvolve (
        ap_ready,
        window_adjust_0_0_0,
        window_adjust_0_2_0,
        window_adjust_1_0_0,
        window_adjust_1_2_0,
        window_adjust_2_0_0,
        window_adjust_2_2_0,
        window_adjust_0_0_1,
        window_adjust_0_2_1,
        window_adjust_1_0_1,
        window_adjust_1_2_1,
        window_adjust_2_0_1,
        window_adjust_2_2_1,
        window_adjust_0_0_2,
        window_adjust_0_2_2,
        window_adjust_1_0_2,
        window_adjust_1_2_2,
        window_adjust_2_0_2,
        window_adjust_2_2_2,
        window_adjust_0_0_3,
        window_adjust_0_2_3,
        window_adjust_1_0_3,
        window_adjust_1_2_3,
        window_adjust_2_0_3,
        window_adjust_2_2_3,
        window_adjust_0_0_4,
        window_adjust_0_2_4,
        window_adjust_1_0_4,
        window_adjust_1_2_4,
        window_adjust_2_0_4,
        window_adjust_2_2_4,
        window_adjust_0_0_5,
        window_adjust_0_2_5,
        window_adjust_1_0_5,
        window_adjust_1_2_5,
        window_adjust_2_0_5,
        window_adjust_2_2_5,
        window_adjust_0_0_6,
        window_adjust_0_2_6,
        window_adjust_1_0_6,
        window_adjust_1_2_6,
        window_adjust_2_0_6,
        window_adjust_2_2_6,
        window_adjust_0_0_7,
        window_adjust_0_2_7,
        window_adjust_1_0_7,
        window_adjust_1_2_7,
        window_adjust_2_0_7,
        window_adjust_2_2_7,
        ap_return
);


output   ap_ready;
input  [9:0] window_adjust_0_0_0;
input  [9:0] window_adjust_0_2_0;
input  [9:0] window_adjust_1_0_0;
input  [9:0] window_adjust_1_2_0;
input  [9:0] window_adjust_2_0_0;
input  [9:0] window_adjust_2_2_0;
input  [9:0] window_adjust_0_0_1;
input  [9:0] window_adjust_0_2_1;
input  [9:0] window_adjust_1_0_1;
input  [9:0] window_adjust_1_2_1;
input  [9:0] window_adjust_2_0_1;
input  [9:0] window_adjust_2_2_1;
input  [9:0] window_adjust_0_0_2;
input  [9:0] window_adjust_0_2_2;
input  [9:0] window_adjust_1_0_2;
input  [9:0] window_adjust_1_2_2;
input  [9:0] window_adjust_2_0_2;
input  [9:0] window_adjust_2_2_2;
input  [9:0] window_adjust_0_0_3;
input  [9:0] window_adjust_0_2_3;
input  [9:0] window_adjust_1_0_3;
input  [9:0] window_adjust_1_2_3;
input  [9:0] window_adjust_2_0_3;
input  [9:0] window_adjust_2_2_3;
input  [9:0] window_adjust_0_0_4;
input  [9:0] window_adjust_0_2_4;
input  [9:0] window_adjust_1_0_4;
input  [9:0] window_adjust_1_2_4;
input  [9:0] window_adjust_2_0_4;
input  [9:0] window_adjust_2_2_4;
input  [9:0] window_adjust_0_0_5;
input  [9:0] window_adjust_0_2_5;
input  [9:0] window_adjust_1_0_5;
input  [9:0] window_adjust_1_2_5;
input  [9:0] window_adjust_2_0_5;
input  [9:0] window_adjust_2_2_5;
input  [9:0] window_adjust_0_0_6;
input  [9:0] window_adjust_0_2_6;
input  [9:0] window_adjust_1_0_6;
input  [9:0] window_adjust_1_2_6;
input  [9:0] window_adjust_2_0_6;
input  [9:0] window_adjust_2_2_6;
input  [9:0] window_adjust_0_0_7;
input  [9:0] window_adjust_0_2_7;
input  [9:0] window_adjust_1_0_7;
input  [9:0] window_adjust_1_2_7;
input  [9:0] window_adjust_2_0_7;
input  [9:0] window_adjust_2_2_7;
output  [79:0] ap_return;

wire   [10:0] zext_ln41_3_fu_150_p1;
wire   [10:0] zext_ln41_2_fu_142_p1;
wire   [10:0] tmp_i_fu_162_p2;
wire   [8:0] empty_fu_168_p1;
wire   [11:0] tmp_fu_172_p3;
wire   [10:0] zext_ln41_1_fu_134_p1;
wire   [10:0] zext_ln41_fu_126_p1;
wire   [10:0] sub_ln41_fu_192_p2;
wire  signed [11:0] sext_ln41_fu_198_p1;
wire   [11:0] window_adjust_2_0_0_load_cast_i_fu_158_p1;
wire   [11:0] sub_ln41_1_fu_202_p2;
wire   [11:0] zext_ln41_4_fu_212_p1;
wire  signed [11:0] add_ln41_fu_216_p2;
wire   [9:0] trunc_ln41_fu_222_p1;
wire   [9:0] tmp_cast_fu_180_p3;
wire  signed [12:0] sext_ln41_3_fu_226_p1;
wire  signed [12:0] sext_ln41_1_fu_188_p1;
wire  signed [12:0] add_ln41_1_fu_236_p2;
wire  signed [31:0] sext_ln44_8_fu_242_p1;
wire   [2:0] tmp_9_fu_254_p4;
wire   [0:0] tmp_8_fu_246_p3;
wire   [0:0] xor_ln44_fu_270_p2;
wire   [0:0] icmp_ln46_fu_264_p2;
wire   [0:0] or_ln44_fu_284_p2;
wire   [9:0] select_ln44_8_fu_276_p3;
wire   [9:0] add_ln44_fu_230_p2;
wire   [10:0] zext_ln41_8_fu_326_p1;
wire   [10:0] zext_ln41_7_fu_318_p1;
wire   [10:0] tmp83_i_fu_338_p2;
wire   [8:0] empty_25_fu_344_p1;
wire   [11:0] tmp_1_fu_348_p3;
wire   [10:0] zext_ln41_6_fu_310_p1;
wire   [10:0] zext_ln41_5_fu_302_p1;
wire   [10:0] sub_ln41_2_fu_368_p2;
wire  signed [11:0] sext_ln41_2_fu_374_p1;
wire   [11:0] window_adjust_2_0_1_load_cast_i_fu_334_p1;
wire   [11:0] sub_ln41_3_fu_378_p2;
wire   [11:0] zext_ln41_9_fu_388_p1;
wire  signed [11:0] add_ln41_2_fu_392_p2;
wire   [9:0] trunc_ln41_1_fu_398_p1;
wire   [9:0] tmp_1_cast_fu_356_p3;
wire  signed [12:0] sext_ln41_7_fu_402_p1;
wire  signed [12:0] sext_ln41_5_fu_364_p1;
wire  signed [12:0] add_ln41_3_fu_412_p2;
wire  signed [31:0] sext_ln44_fu_418_p1;
wire   [2:0] tmp_11_fu_430_p4;
wire   [0:0] tmp_10_fu_422_p3;
wire   [0:0] xor_ln44_1_fu_446_p2;
wire   [0:0] icmp_ln46_1_fu_440_p2;
wire   [0:0] or_ln44_1_fu_460_p2;
wire   [9:0] select_ln44_9_fu_452_p3;
wire   [9:0] add_ln44_1_fu_406_p2;
wire   [10:0] zext_ln41_13_fu_502_p1;
wire   [10:0] zext_ln41_12_fu_494_p1;
wire   [10:0] tmp86_i_fu_514_p2;
wire   [8:0] empty_26_fu_520_p1;
wire   [11:0] tmp_2_fu_524_p3;
wire   [10:0] zext_ln41_11_fu_486_p1;
wire   [10:0] zext_ln41_10_fu_478_p1;
wire   [10:0] sub_ln41_4_fu_544_p2;
wire  signed [11:0] sext_ln41_4_fu_550_p1;
wire   [11:0] window_adjust_2_0_2_load_cast_i_fu_510_p1;
wire   [11:0] sub_ln41_5_fu_554_p2;
wire   [11:0] zext_ln41_14_fu_564_p1;
wire  signed [11:0] add_ln41_4_fu_568_p2;
wire   [9:0] trunc_ln41_2_fu_574_p1;
wire   [9:0] tmp_2_cast_fu_532_p3;
wire  signed [12:0] sext_ln41_11_fu_578_p1;
wire  signed [12:0] sext_ln41_9_fu_540_p1;
wire  signed [12:0] add_ln41_5_fu_588_p2;
wire  signed [31:0] sext_ln44_9_fu_594_p1;
wire   [2:0] tmp_13_fu_606_p4;
wire   [0:0] tmp_12_fu_598_p3;
wire   [0:0] xor_ln44_2_fu_622_p2;
wire   [0:0] icmp_ln46_2_fu_616_p2;
wire   [0:0] or_ln44_2_fu_636_p2;
wire   [9:0] select_ln44_10_fu_628_p3;
wire   [9:0] add_ln44_2_fu_582_p2;
wire   [10:0] zext_ln41_18_fu_678_p1;
wire   [10:0] zext_ln41_17_fu_670_p1;
wire   [10:0] tmp89_i_fu_690_p2;
wire   [8:0] empty_27_fu_696_p1;
wire   [11:0] tmp_3_fu_700_p3;
wire   [10:0] zext_ln41_16_fu_662_p1;
wire   [10:0] zext_ln41_15_fu_654_p1;
wire   [10:0] sub_ln41_6_fu_720_p2;
wire  signed [11:0] sext_ln41_6_fu_726_p1;
wire   [11:0] window_adjust_2_0_3_load_cast_i_fu_686_p1;
wire   [11:0] sub_ln41_7_fu_730_p2;
wire   [11:0] zext_ln41_19_fu_740_p1;
wire  signed [11:0] add_ln41_6_fu_744_p2;
wire   [9:0] trunc_ln41_3_fu_750_p1;
wire   [9:0] tmp_3_cast_fu_708_p3;
wire  signed [12:0] sext_ln41_15_fu_754_p1;
wire  signed [12:0] sext_ln41_13_fu_716_p1;
wire  signed [12:0] add_ln41_7_fu_764_p2;
wire  signed [31:0] sext_ln44_10_fu_770_p1;
wire   [2:0] tmp_15_fu_782_p4;
wire   [0:0] tmp_14_fu_774_p3;
wire   [0:0] xor_ln44_3_fu_798_p2;
wire   [0:0] icmp_ln46_3_fu_792_p2;
wire   [0:0] or_ln44_3_fu_812_p2;
wire   [9:0] select_ln44_11_fu_804_p3;
wire   [9:0] add_ln44_3_fu_758_p2;
wire   [10:0] zext_ln41_23_fu_854_p1;
wire   [10:0] zext_ln41_22_fu_846_p1;
wire   [10:0] tmp92_i_fu_866_p2;
wire   [8:0] empty_28_fu_872_p1;
wire   [11:0] tmp_4_fu_876_p3;
wire   [10:0] zext_ln41_21_fu_838_p1;
wire   [10:0] zext_ln41_20_fu_830_p1;
wire   [10:0] sub_ln41_8_fu_896_p2;
wire  signed [11:0] sext_ln41_8_fu_902_p1;
wire   [11:0] window_adjust_2_0_4_load_cast_i_fu_862_p1;
wire   [11:0] sub_ln41_9_fu_906_p2;
wire   [11:0] zext_ln41_24_fu_916_p1;
wire  signed [11:0] add_ln41_8_fu_920_p2;
wire   [9:0] trunc_ln41_4_fu_926_p1;
wire   [9:0] tmp_4_cast_fu_884_p3;
wire  signed [12:0] sext_ln41_17_fu_930_p1;
wire  signed [12:0] sext_ln41_16_fu_892_p1;
wire  signed [12:0] add_ln41_9_fu_940_p2;
wire  signed [31:0] sext_ln44_11_fu_946_p1;
wire   [2:0] tmp_17_fu_958_p4;
wire   [0:0] tmp_16_fu_950_p3;
wire   [0:0] xor_ln44_4_fu_974_p2;
wire   [0:0] icmp_ln46_4_fu_968_p2;
wire   [0:0] or_ln44_4_fu_988_p2;
wire   [9:0] select_ln44_12_fu_980_p3;
wire   [9:0] add_ln44_4_fu_934_p2;
wire   [10:0] zext_ln41_28_fu_1030_p1;
wire   [10:0] zext_ln41_27_fu_1022_p1;
wire   [10:0] tmp95_i_fu_1042_p2;
wire   [8:0] empty_29_fu_1048_p1;
wire   [11:0] tmp_5_fu_1052_p3;
wire   [10:0] zext_ln41_26_fu_1014_p1;
wire   [10:0] zext_ln41_25_fu_1006_p1;
wire   [10:0] sub_ln41_10_fu_1072_p2;
wire  signed [11:0] sext_ln41_10_fu_1078_p1;
wire   [11:0] window_adjust_2_0_5_load_cast_i_fu_1038_p1;
wire   [11:0] sub_ln41_11_fu_1082_p2;
wire   [11:0] zext_ln41_29_fu_1092_p1;
wire  signed [11:0] add_ln41_10_fu_1096_p2;
wire   [9:0] trunc_ln41_5_fu_1102_p1;
wire   [9:0] tmp_5_cast_fu_1060_p3;
wire  signed [12:0] sext_ln41_19_fu_1106_p1;
wire  signed [12:0] sext_ln41_18_fu_1068_p1;
wire  signed [12:0] add_ln41_11_fu_1116_p2;
wire  signed [31:0] sext_ln44_12_fu_1122_p1;
wire   [2:0] tmp_19_fu_1134_p4;
wire   [0:0] tmp_18_fu_1126_p3;
wire   [0:0] xor_ln44_5_fu_1150_p2;
wire   [0:0] icmp_ln46_5_fu_1144_p2;
wire   [0:0] or_ln44_5_fu_1164_p2;
wire   [9:0] select_ln44_13_fu_1156_p3;
wire   [9:0] add_ln44_5_fu_1110_p2;
wire   [10:0] zext_ln41_33_fu_1206_p1;
wire   [10:0] zext_ln41_32_fu_1198_p1;
wire   [10:0] tmp98_i_fu_1218_p2;
wire   [8:0] empty_30_fu_1224_p1;
wire   [11:0] tmp_6_fu_1228_p3;
wire   [10:0] zext_ln41_31_fu_1190_p1;
wire   [10:0] zext_ln41_30_fu_1182_p1;
wire   [10:0] sub_ln41_12_fu_1248_p2;
wire  signed [11:0] sext_ln41_12_fu_1254_p1;
wire   [11:0] window_adjust_2_0_6_load_cast_i_fu_1214_p1;
wire   [11:0] sub_ln41_13_fu_1258_p2;
wire   [11:0] zext_ln41_34_fu_1268_p1;
wire  signed [11:0] add_ln41_12_fu_1272_p2;
wire   [9:0] trunc_ln41_6_fu_1278_p1;
wire   [9:0] tmp_6_cast_fu_1236_p3;
wire  signed [12:0] sext_ln41_21_fu_1282_p1;
wire  signed [12:0] sext_ln41_20_fu_1244_p1;
wire  signed [12:0] add_ln41_13_fu_1292_p2;
wire  signed [31:0] sext_ln44_13_fu_1298_p1;
wire   [2:0] tmp_21_fu_1310_p4;
wire   [0:0] tmp_20_fu_1302_p3;
wire   [0:0] xor_ln44_6_fu_1326_p2;
wire   [0:0] icmp_ln46_6_fu_1320_p2;
wire   [0:0] or_ln44_6_fu_1340_p2;
wire   [9:0] select_ln44_14_fu_1332_p3;
wire   [9:0] add_ln44_6_fu_1286_p2;
wire   [10:0] zext_ln41_38_fu_1382_p1;
wire   [10:0] zext_ln41_37_fu_1374_p1;
wire   [10:0] tmp101_i_fu_1394_p2;
wire   [8:0] empty_31_fu_1400_p1;
wire   [11:0] tmp_7_fu_1404_p3;
wire   [10:0] zext_ln41_36_fu_1366_p1;
wire   [10:0] zext_ln41_35_fu_1358_p1;
wire   [10:0] sub_ln41_14_fu_1424_p2;
wire  signed [11:0] sext_ln41_14_fu_1430_p1;
wire   [11:0] window_adjust_2_0_7_load_cast_i_fu_1390_p1;
wire   [11:0] sub_ln41_15_fu_1434_p2;
wire   [11:0] zext_ln41_39_fu_1444_p1;
wire  signed [11:0] add_ln41_14_fu_1448_p2;
wire   [9:0] trunc_ln41_7_fu_1454_p1;
wire   [9:0] tmp_7_cast_fu_1412_p3;
wire  signed [12:0] sext_ln41_23_fu_1458_p1;
wire  signed [12:0] sext_ln41_22_fu_1420_p1;
wire  signed [12:0] add_ln41_15_fu_1468_p2;
wire  signed [31:0] sext_ln44_14_fu_1474_p1;
wire   [2:0] tmp_23_fu_1486_p4;
wire   [0:0] tmp_22_fu_1478_p3;
wire   [0:0] xor_ln44_7_fu_1502_p2;
wire   [0:0] icmp_ln46_7_fu_1496_p2;
wire   [0:0] or_ln44_7_fu_1516_p2;
wire   [9:0] select_ln44_15_fu_1508_p3;
wire   [9:0] add_ln44_7_fu_1462_p2;
wire   [9:0] select_ln44_fu_290_p3;
wire   [9:0] select_ln44_1_fu_466_p3;
wire   [9:0] select_ln44_2_fu_642_p3;
wire   [9:0] select_ln44_3_fu_818_p3;
wire   [9:0] select_ln44_4_fu_994_p3;
wire   [9:0] select_ln44_5_fu_1170_p3;
wire   [9:0] select_ln44_6_fu_1346_p3;
wire   [9:0] select_ln44_7_fu_1522_p3;

assign add_ln41_10_fu_1096_p2 = (sub_ln41_11_fu_1082_p2 + zext_ln41_29_fu_1092_p1);

assign add_ln41_11_fu_1116_p2 = ($signed(sext_ln41_19_fu_1106_p1) + $signed(sext_ln41_18_fu_1068_p1));

assign add_ln41_12_fu_1272_p2 = (sub_ln41_13_fu_1258_p2 + zext_ln41_34_fu_1268_p1);

assign add_ln41_13_fu_1292_p2 = ($signed(sext_ln41_21_fu_1282_p1) + $signed(sext_ln41_20_fu_1244_p1));

assign add_ln41_14_fu_1448_p2 = (sub_ln41_15_fu_1434_p2 + zext_ln41_39_fu_1444_p1);

assign add_ln41_15_fu_1468_p2 = ($signed(sext_ln41_23_fu_1458_p1) + $signed(sext_ln41_22_fu_1420_p1));

assign add_ln41_1_fu_236_p2 = ($signed(sext_ln41_3_fu_226_p1) + $signed(sext_ln41_1_fu_188_p1));

assign add_ln41_2_fu_392_p2 = (sub_ln41_3_fu_378_p2 + zext_ln41_9_fu_388_p1);

assign add_ln41_3_fu_412_p2 = ($signed(sext_ln41_7_fu_402_p1) + $signed(sext_ln41_5_fu_364_p1));

assign add_ln41_4_fu_568_p2 = (sub_ln41_5_fu_554_p2 + zext_ln41_14_fu_564_p1);

assign add_ln41_5_fu_588_p2 = ($signed(sext_ln41_11_fu_578_p1) + $signed(sext_ln41_9_fu_540_p1));

assign add_ln41_6_fu_744_p2 = (sub_ln41_7_fu_730_p2 + zext_ln41_19_fu_740_p1);

assign add_ln41_7_fu_764_p2 = ($signed(sext_ln41_15_fu_754_p1) + $signed(sext_ln41_13_fu_716_p1));

assign add_ln41_8_fu_920_p2 = (sub_ln41_9_fu_906_p2 + zext_ln41_24_fu_916_p1);

assign add_ln41_9_fu_940_p2 = ($signed(sext_ln41_17_fu_930_p1) + $signed(sext_ln41_16_fu_892_p1));

assign add_ln41_fu_216_p2 = (sub_ln41_1_fu_202_p2 + zext_ln41_4_fu_212_p1);

assign add_ln44_1_fu_406_p2 = (trunc_ln41_1_fu_398_p1 + tmp_1_cast_fu_356_p3);

assign add_ln44_2_fu_582_p2 = (trunc_ln41_2_fu_574_p1 + tmp_2_cast_fu_532_p3);

assign add_ln44_3_fu_758_p2 = (trunc_ln41_3_fu_750_p1 + tmp_3_cast_fu_708_p3);

assign add_ln44_4_fu_934_p2 = (trunc_ln41_4_fu_926_p1 + tmp_4_cast_fu_884_p3);

assign add_ln44_5_fu_1110_p2 = (trunc_ln41_5_fu_1102_p1 + tmp_5_cast_fu_1060_p3);

assign add_ln44_6_fu_1286_p2 = (trunc_ln41_6_fu_1278_p1 + tmp_6_cast_fu_1236_p3);

assign add_ln44_7_fu_1462_p2 = (trunc_ln41_7_fu_1454_p1 + tmp_7_cast_fu_1412_p3);

assign add_ln44_fu_230_p2 = (trunc_ln41_fu_222_p1 + tmp_cast_fu_180_p3);

assign ap_ready = 1'b1;

assign empty_25_fu_344_p1 = tmp83_i_fu_338_p2[8:0];

assign empty_26_fu_520_p1 = tmp86_i_fu_514_p2[8:0];

assign empty_27_fu_696_p1 = tmp89_i_fu_690_p2[8:0];

assign empty_28_fu_872_p1 = tmp92_i_fu_866_p2[8:0];

assign empty_29_fu_1048_p1 = tmp95_i_fu_1042_p2[8:0];

assign empty_30_fu_1224_p1 = tmp98_i_fu_1218_p2[8:0];

assign empty_31_fu_1400_p1 = tmp101_i_fu_1394_p2[8:0];

assign empty_fu_168_p1 = tmp_i_fu_162_p2[8:0];

assign or_ln44_1_fu_460_p2 = (tmp_10_fu_422_p3 | icmp_ln46_1_fu_440_p2);

assign or_ln44_2_fu_636_p2 = (tmp_12_fu_598_p3 | icmp_ln46_2_fu_616_p2);

assign or_ln44_3_fu_812_p2 = (tmp_14_fu_774_p3 | icmp_ln46_3_fu_792_p2);

assign or_ln44_4_fu_988_p2 = (tmp_16_fu_950_p3 | icmp_ln46_4_fu_968_p2);

assign or_ln44_5_fu_1164_p2 = (tmp_18_fu_1126_p3 | icmp_ln46_5_fu_1144_p2);

assign or_ln44_6_fu_1340_p2 = (tmp_20_fu_1302_p3 | icmp_ln46_6_fu_1320_p2);

assign or_ln44_7_fu_1516_p2 = (tmp_22_fu_1478_p3 | icmp_ln46_7_fu_1496_p2);

assign or_ln44_fu_284_p2 = (tmp_8_fu_246_p3 | icmp_ln46_fu_264_p2);

assign select_ln44_10_fu_628_p3 = ((xor_ln44_2_fu_622_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln44_11_fu_804_p3 = ((xor_ln44_3_fu_798_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln44_12_fu_980_p3 = ((xor_ln44_4_fu_974_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln44_13_fu_1156_p3 = ((xor_ln44_5_fu_1150_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln44_14_fu_1332_p3 = ((xor_ln44_6_fu_1326_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln44_15_fu_1508_p3 = ((xor_ln44_7_fu_1502_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln44_1_fu_466_p3 = ((or_ln44_1_fu_460_p2[0:0] == 1'b1) ? select_ln44_9_fu_452_p3 : add_ln44_1_fu_406_p2);

assign select_ln44_2_fu_642_p3 = ((or_ln44_2_fu_636_p2[0:0] == 1'b1) ? select_ln44_10_fu_628_p3 : add_ln44_2_fu_582_p2);

assign select_ln44_3_fu_818_p3 = ((or_ln44_3_fu_812_p2[0:0] == 1'b1) ? select_ln44_11_fu_804_p3 : add_ln44_3_fu_758_p2);

assign select_ln44_4_fu_994_p3 = ((or_ln44_4_fu_988_p2[0:0] == 1'b1) ? select_ln44_12_fu_980_p3 : add_ln44_4_fu_934_p2);

assign select_ln44_5_fu_1170_p3 = ((or_ln44_5_fu_1164_p2[0:0] == 1'b1) ? select_ln44_13_fu_1156_p3 : add_ln44_5_fu_1110_p2);

assign select_ln44_6_fu_1346_p3 = ((or_ln44_6_fu_1340_p2[0:0] == 1'b1) ? select_ln44_14_fu_1332_p3 : add_ln44_6_fu_1286_p2);

assign select_ln44_7_fu_1522_p3 = ((or_ln44_7_fu_1516_p2[0:0] == 1'b1) ? select_ln44_15_fu_1508_p3 : add_ln44_7_fu_1462_p2);

assign select_ln44_8_fu_276_p3 = ((xor_ln44_fu_270_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln44_9_fu_452_p3 = ((xor_ln44_1_fu_446_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln44_fu_290_p3 = ((or_ln44_fu_284_p2[0:0] == 1'b1) ? select_ln44_8_fu_276_p3 : add_ln44_fu_230_p2);

assign sext_ln41_10_fu_1078_p1 = $signed(sub_ln41_10_fu_1072_p2);

assign sext_ln41_11_fu_578_p1 = add_ln41_4_fu_568_p2;

assign sext_ln41_12_fu_1254_p1 = $signed(sub_ln41_12_fu_1248_p2);

assign sext_ln41_13_fu_716_p1 = $signed(tmp_3_fu_700_p3);

assign sext_ln41_14_fu_1430_p1 = $signed(sub_ln41_14_fu_1424_p2);

assign sext_ln41_15_fu_754_p1 = add_ln41_6_fu_744_p2;

assign sext_ln41_16_fu_892_p1 = $signed(tmp_4_fu_876_p3);

assign sext_ln41_17_fu_930_p1 = add_ln41_8_fu_920_p2;

assign sext_ln41_18_fu_1068_p1 = $signed(tmp_5_fu_1052_p3);

assign sext_ln41_19_fu_1106_p1 = add_ln41_10_fu_1096_p2;

assign sext_ln41_1_fu_188_p1 = $signed(tmp_fu_172_p3);

assign sext_ln41_20_fu_1244_p1 = $signed(tmp_6_fu_1228_p3);

assign sext_ln41_21_fu_1282_p1 = add_ln41_12_fu_1272_p2;

assign sext_ln41_22_fu_1420_p1 = $signed(tmp_7_fu_1404_p3);

assign sext_ln41_23_fu_1458_p1 = add_ln41_14_fu_1448_p2;

assign sext_ln41_2_fu_374_p1 = $signed(sub_ln41_2_fu_368_p2);

assign sext_ln41_3_fu_226_p1 = add_ln41_fu_216_p2;

assign sext_ln41_4_fu_550_p1 = $signed(sub_ln41_4_fu_544_p2);

assign sext_ln41_5_fu_364_p1 = $signed(tmp_1_fu_348_p3);

assign sext_ln41_6_fu_726_p1 = $signed(sub_ln41_6_fu_720_p2);

assign sext_ln41_7_fu_402_p1 = add_ln41_2_fu_392_p2;

assign sext_ln41_8_fu_902_p1 = $signed(sub_ln41_8_fu_896_p2);

assign sext_ln41_9_fu_540_p1 = $signed(tmp_2_fu_524_p3);

assign sext_ln41_fu_198_p1 = $signed(sub_ln41_fu_192_p2);

assign sext_ln44_10_fu_770_p1 = add_ln41_7_fu_764_p2;

assign sext_ln44_11_fu_946_p1 = add_ln41_9_fu_940_p2;

assign sext_ln44_12_fu_1122_p1 = add_ln41_11_fu_1116_p2;

assign sext_ln44_13_fu_1298_p1 = add_ln41_13_fu_1292_p2;

assign sext_ln44_14_fu_1474_p1 = add_ln41_15_fu_1468_p2;

assign sext_ln44_8_fu_242_p1 = add_ln41_1_fu_236_p2;

assign sext_ln44_9_fu_594_p1 = add_ln41_5_fu_588_p2;

assign sext_ln44_fu_418_p1 = add_ln41_3_fu_412_p2;

assign sub_ln41_10_fu_1072_p2 = (zext_ln41_26_fu_1014_p1 - zext_ln41_25_fu_1006_p1);

assign sub_ln41_11_fu_1082_p2 = ($signed(sext_ln41_10_fu_1078_p1) - $signed(window_adjust_2_0_5_load_cast_i_fu_1038_p1));

assign sub_ln41_12_fu_1248_p2 = (zext_ln41_31_fu_1190_p1 - zext_ln41_30_fu_1182_p1);

assign sub_ln41_13_fu_1258_p2 = ($signed(sext_ln41_12_fu_1254_p1) - $signed(window_adjust_2_0_6_load_cast_i_fu_1214_p1));

assign sub_ln41_14_fu_1424_p2 = (zext_ln41_36_fu_1366_p1 - zext_ln41_35_fu_1358_p1);

assign sub_ln41_15_fu_1434_p2 = ($signed(sext_ln41_14_fu_1430_p1) - $signed(window_adjust_2_0_7_load_cast_i_fu_1390_p1));

assign sub_ln41_1_fu_202_p2 = ($signed(sext_ln41_fu_198_p1) - $signed(window_adjust_2_0_0_load_cast_i_fu_158_p1));

assign sub_ln41_2_fu_368_p2 = (zext_ln41_6_fu_310_p1 - zext_ln41_5_fu_302_p1);

assign sub_ln41_3_fu_378_p2 = ($signed(sext_ln41_2_fu_374_p1) - $signed(window_adjust_2_0_1_load_cast_i_fu_334_p1));

assign sub_ln41_4_fu_544_p2 = (zext_ln41_11_fu_486_p1 - zext_ln41_10_fu_478_p1);

assign sub_ln41_5_fu_554_p2 = ($signed(sext_ln41_4_fu_550_p1) - $signed(window_adjust_2_0_2_load_cast_i_fu_510_p1));

assign sub_ln41_6_fu_720_p2 = (zext_ln41_16_fu_662_p1 - zext_ln41_15_fu_654_p1);

assign sub_ln41_7_fu_730_p2 = ($signed(sext_ln41_6_fu_726_p1) - $signed(window_adjust_2_0_3_load_cast_i_fu_686_p1));

assign sub_ln41_8_fu_896_p2 = (zext_ln41_21_fu_838_p1 - zext_ln41_20_fu_830_p1);

assign sub_ln41_9_fu_906_p2 = ($signed(sext_ln41_8_fu_902_p1) - $signed(window_adjust_2_0_4_load_cast_i_fu_862_p1));

assign sub_ln41_fu_192_p2 = (zext_ln41_1_fu_134_p1 - zext_ln41_fu_126_p1);

assign tmp101_i_fu_1394_p2 = (zext_ln41_38_fu_1382_p1 - zext_ln41_37_fu_1374_p1);

assign tmp83_i_fu_338_p2 = (zext_ln41_8_fu_326_p1 - zext_ln41_7_fu_318_p1);

assign tmp86_i_fu_514_p2 = (zext_ln41_13_fu_502_p1 - zext_ln41_12_fu_494_p1);

assign tmp89_i_fu_690_p2 = (zext_ln41_18_fu_678_p1 - zext_ln41_17_fu_670_p1);

assign tmp92_i_fu_866_p2 = (zext_ln41_23_fu_854_p1 - zext_ln41_22_fu_846_p1);

assign tmp95_i_fu_1042_p2 = (zext_ln41_28_fu_1030_p1 - zext_ln41_27_fu_1022_p1);

assign tmp98_i_fu_1218_p2 = (zext_ln41_33_fu_1206_p1 - zext_ln41_32_fu_1198_p1);

assign tmp_10_fu_422_p3 = sext_ln44_fu_418_p1[32'd31];

assign tmp_11_fu_430_p4 = {{add_ln41_3_fu_412_p2[12:10]}};

assign tmp_12_fu_598_p3 = sext_ln44_9_fu_594_p1[32'd31];

assign tmp_13_fu_606_p4 = {{add_ln41_5_fu_588_p2[12:10]}};

assign tmp_14_fu_774_p3 = sext_ln44_10_fu_770_p1[32'd31];

assign tmp_15_fu_782_p4 = {{add_ln41_7_fu_764_p2[12:10]}};

assign tmp_16_fu_950_p3 = sext_ln44_11_fu_946_p1[32'd31];

assign tmp_17_fu_958_p4 = {{add_ln41_9_fu_940_p2[12:10]}};

assign tmp_18_fu_1126_p3 = sext_ln44_12_fu_1122_p1[32'd31];

assign tmp_19_fu_1134_p4 = {{add_ln41_11_fu_1116_p2[12:10]}};

assign tmp_1_cast_fu_356_p3 = {{empty_25_fu_344_p1}, {1'd0}};

assign tmp_1_fu_348_p3 = {{tmp83_i_fu_338_p2}, {1'd0}};

assign tmp_20_fu_1302_p3 = sext_ln44_13_fu_1298_p1[32'd31];

assign tmp_21_fu_1310_p4 = {{add_ln41_13_fu_1292_p2[12:10]}};

assign tmp_22_fu_1478_p3 = sext_ln44_14_fu_1474_p1[32'd31];

assign tmp_23_fu_1486_p4 = {{add_ln41_15_fu_1468_p2[12:10]}};

assign tmp_2_cast_fu_532_p3 = {{empty_26_fu_520_p1}, {1'd0}};

assign tmp_2_fu_524_p3 = {{tmp86_i_fu_514_p2}, {1'd0}};

assign tmp_3_cast_fu_708_p3 = {{empty_27_fu_696_p1}, {1'd0}};

assign tmp_3_fu_700_p3 = {{tmp89_i_fu_690_p2}, {1'd0}};

assign tmp_4_cast_fu_884_p3 = {{empty_28_fu_872_p1}, {1'd0}};

assign tmp_4_fu_876_p3 = {{tmp92_i_fu_866_p2}, {1'd0}};

assign tmp_5_cast_fu_1060_p3 = {{empty_29_fu_1048_p1}, {1'd0}};

assign tmp_5_fu_1052_p3 = {{tmp95_i_fu_1042_p2}, {1'd0}};

assign tmp_6_cast_fu_1236_p3 = {{empty_30_fu_1224_p1}, {1'd0}};

assign tmp_6_fu_1228_p3 = {{tmp98_i_fu_1218_p2}, {1'd0}};

assign tmp_7_cast_fu_1412_p3 = {{empty_31_fu_1400_p1}, {1'd0}};

assign tmp_7_fu_1404_p3 = {{tmp101_i_fu_1394_p2}, {1'd0}};

assign tmp_8_fu_246_p3 = sext_ln44_8_fu_242_p1[32'd31];

assign tmp_9_fu_254_p4 = {{add_ln41_1_fu_236_p2[12:10]}};

assign tmp_cast_fu_180_p3 = {{empty_fu_168_p1}, {1'd0}};

assign tmp_fu_172_p3 = {{tmp_i_fu_162_p2}, {1'd0}};

assign tmp_i_fu_162_p2 = (zext_ln41_3_fu_150_p1 - zext_ln41_2_fu_142_p1);

assign trunc_ln41_1_fu_398_p1 = add_ln41_2_fu_392_p2[9:0];

assign trunc_ln41_2_fu_574_p1 = add_ln41_4_fu_568_p2[9:0];

assign trunc_ln41_3_fu_750_p1 = add_ln41_6_fu_744_p2[9:0];

assign trunc_ln41_4_fu_926_p1 = add_ln41_8_fu_920_p2[9:0];

assign trunc_ln41_5_fu_1102_p1 = add_ln41_10_fu_1096_p2[9:0];

assign trunc_ln41_6_fu_1278_p1 = add_ln41_12_fu_1272_p2[9:0];

assign trunc_ln41_7_fu_1454_p1 = add_ln41_14_fu_1448_p2[9:0];

assign trunc_ln41_fu_222_p1 = add_ln41_fu_216_p2[9:0];

assign window_adjust_2_0_0_load_cast_i_fu_158_p1 = window_adjust_2_0_0;

assign window_adjust_2_0_1_load_cast_i_fu_334_p1 = window_adjust_2_0_1;

assign window_adjust_2_0_2_load_cast_i_fu_510_p1 = window_adjust_2_0_2;

assign window_adjust_2_0_3_load_cast_i_fu_686_p1 = window_adjust_2_0_3;

assign window_adjust_2_0_4_load_cast_i_fu_862_p1 = window_adjust_2_0_4;

assign window_adjust_2_0_5_load_cast_i_fu_1038_p1 = window_adjust_2_0_5;

assign window_adjust_2_0_6_load_cast_i_fu_1214_p1 = window_adjust_2_0_6;

assign window_adjust_2_0_7_load_cast_i_fu_1390_p1 = window_adjust_2_0_7;

assign xor_ln44_1_fu_446_p2 = (tmp_10_fu_422_p3 ^ 1'd1);

assign xor_ln44_2_fu_622_p2 = (tmp_12_fu_598_p3 ^ 1'd1);

assign xor_ln44_3_fu_798_p2 = (tmp_14_fu_774_p3 ^ 1'd1);

assign xor_ln44_4_fu_974_p2 = (tmp_16_fu_950_p3 ^ 1'd1);

assign xor_ln44_5_fu_1150_p2 = (tmp_18_fu_1126_p3 ^ 1'd1);

assign xor_ln44_6_fu_1326_p2 = (tmp_20_fu_1302_p3 ^ 1'd1);

assign xor_ln44_7_fu_1502_p2 = (tmp_22_fu_1478_p3 ^ 1'd1);

assign xor_ln44_fu_270_p2 = (tmp_8_fu_246_p3 ^ 1'd1);

assign zext_ln41_10_fu_478_p1 = window_adjust_0_0_2;

assign zext_ln41_11_fu_486_p1 = window_adjust_0_2_2;

assign zext_ln41_12_fu_494_p1 = window_adjust_1_0_2;

assign zext_ln41_13_fu_502_p1 = window_adjust_1_2_2;

assign zext_ln41_14_fu_564_p1 = window_adjust_2_2_2;

assign zext_ln41_15_fu_654_p1 = window_adjust_0_0_3;

assign zext_ln41_16_fu_662_p1 = window_adjust_0_2_3;

assign zext_ln41_17_fu_670_p1 = window_adjust_1_0_3;

assign zext_ln41_18_fu_678_p1 = window_adjust_1_2_3;

assign zext_ln41_19_fu_740_p1 = window_adjust_2_2_3;

assign zext_ln41_1_fu_134_p1 = window_adjust_0_2_0;

assign zext_ln41_20_fu_830_p1 = window_adjust_0_0_4;

assign zext_ln41_21_fu_838_p1 = window_adjust_0_2_4;

assign zext_ln41_22_fu_846_p1 = window_adjust_1_0_4;

assign zext_ln41_23_fu_854_p1 = window_adjust_1_2_4;

assign zext_ln41_24_fu_916_p1 = window_adjust_2_2_4;

assign zext_ln41_25_fu_1006_p1 = window_adjust_0_0_5;

assign zext_ln41_26_fu_1014_p1 = window_adjust_0_2_5;

assign zext_ln41_27_fu_1022_p1 = window_adjust_1_0_5;

assign zext_ln41_28_fu_1030_p1 = window_adjust_1_2_5;

assign zext_ln41_29_fu_1092_p1 = window_adjust_2_2_5;

assign zext_ln41_2_fu_142_p1 = window_adjust_1_0_0;

assign zext_ln41_30_fu_1182_p1 = window_adjust_0_0_6;

assign zext_ln41_31_fu_1190_p1 = window_adjust_0_2_6;

assign zext_ln41_32_fu_1198_p1 = window_adjust_1_0_6;

assign zext_ln41_33_fu_1206_p1 = window_adjust_1_2_6;

assign zext_ln41_34_fu_1268_p1 = window_adjust_2_2_6;

assign zext_ln41_35_fu_1358_p1 = window_adjust_0_0_7;

assign zext_ln41_36_fu_1366_p1 = window_adjust_0_2_7;

assign zext_ln41_37_fu_1374_p1 = window_adjust_1_0_7;

assign zext_ln41_38_fu_1382_p1 = window_adjust_1_2_7;

assign zext_ln41_39_fu_1444_p1 = window_adjust_2_2_7;

assign zext_ln41_3_fu_150_p1 = window_adjust_1_2_0;

assign zext_ln41_4_fu_212_p1 = window_adjust_2_2_0;

assign zext_ln41_5_fu_302_p1 = window_adjust_0_0_1;

assign zext_ln41_6_fu_310_p1 = window_adjust_0_2_1;

assign zext_ln41_7_fu_318_p1 = window_adjust_1_0_1;

assign zext_ln41_8_fu_326_p1 = window_adjust_1_2_1;

assign zext_ln41_9_fu_388_p1 = window_adjust_2_2_1;

assign zext_ln41_fu_126_p1 = window_adjust_0_0_0;

assign ap_return = {{{{{{{{select_ln44_fu_290_p3}, {select_ln44_1_fu_466_p3}}, {select_ln44_2_fu_642_p3}}, {select_ln44_3_fu_818_p3}}, {select_ln44_4_fu_994_p3}}, {select_ln44_5_fu_1170_p3}}, {select_ln44_6_fu_1346_p3}}, {select_ln44_7_fu_1522_p3}};

assign icmp_ln46_1_fu_440_p2 = (($signed(tmp_11_fu_430_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln46_2_fu_616_p2 = (($signed(tmp_13_fu_606_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln46_3_fu_792_p2 = (($signed(tmp_15_fu_782_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln46_4_fu_968_p2 = (($signed(tmp_17_fu_958_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln46_5_fu_1144_p2 = (($signed(tmp_19_fu_1134_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln46_6_fu_1320_p2 = (($signed(tmp_21_fu_1310_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln46_7_fu_1496_p2 = (($signed(tmp_23_fu_1486_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_264_p2 = (($signed(tmp_9_fu_254_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

endmodule //conv2d_3x3_sobelConvolve
