// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module conv2d_3x3_shift_register (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        row,
        linebuf_0_0_address0,
        linebuf_0_0_ce0,
        linebuf_0_0_q0,
        linebuf_0_1_address0,
        linebuf_0_1_ce0,
        linebuf_0_1_q0,
        linebuf_1_0_address0,
        linebuf_1_0_ce0,
        linebuf_1_0_q0,
        linebuf_1_1_address0,
        linebuf_1_1_ce0,
        linebuf_1_1_q0,
        linebuf_2_0_address0,
        linebuf_2_0_ce0,
        linebuf_2_0_q0,
        linebuf_2_1_address0,
        linebuf_2_1_ce0,
        linebuf_2_1_q0,
        window_adjust_0_0_0_i,
        window_adjust_0_0_0_o,
        window_adjust_0_0_0_o_ap_vld,
        window_adjust_1_0_0_i,
        window_adjust_1_0_0_o,
        window_adjust_1_0_0_o_ap_vld,
        window_adjust_2_0_0_i,
        window_adjust_2_0_0_o,
        window_adjust_2_0_0_o_ap_vld,
        window_adjust_0_0_1_i,
        window_adjust_0_0_1_o,
        window_adjust_0_0_1_o_ap_vld,
        window_adjust_1_0_1_i,
        window_adjust_1_0_1_o,
        window_adjust_1_0_1_o_ap_vld,
        window_adjust_2_0_1_i,
        window_adjust_2_0_1_o,
        window_adjust_2_0_1_o_ap_vld,
        window_adjust_0_0_2_i,
        window_adjust_0_0_2_o,
        window_adjust_0_0_2_o_ap_vld,
        window_adjust_1_0_2_i,
        window_adjust_1_0_2_o,
        window_adjust_1_0_2_o_ap_vld,
        window_adjust_2_0_2_i,
        window_adjust_2_0_2_o,
        window_adjust_2_0_2_o_ap_vld,
        window_adjust_0_0_3_i,
        window_adjust_0_0_3_o,
        window_adjust_0_0_3_o_ap_vld,
        window_adjust_1_0_3_i,
        window_adjust_1_0_3_o,
        window_adjust_1_0_3_o_ap_vld,
        window_adjust_2_0_3_i,
        window_adjust_2_0_3_o,
        window_adjust_2_0_3_o_ap_vld,
        window_adjust_0_0_4_i,
        window_adjust_0_0_4_o,
        window_adjust_0_0_4_o_ap_vld,
        window_adjust_1_0_4_i,
        window_adjust_1_0_4_o,
        window_adjust_1_0_4_o_ap_vld,
        window_adjust_2_0_4_i,
        window_adjust_2_0_4_o,
        window_adjust_2_0_4_o_ap_vld,
        window_adjust_0_0_5_i,
        window_adjust_0_0_5_o,
        window_adjust_0_0_5_o_ap_vld,
        window_adjust_1_0_5_i,
        window_adjust_1_0_5_o,
        window_adjust_1_0_5_o_ap_vld,
        window_adjust_2_0_5_i,
        window_adjust_2_0_5_o,
        window_adjust_2_0_5_o_ap_vld,
        window_adjust_0_0_6_i,
        window_adjust_0_0_6_o,
        window_adjust_0_0_6_o_ap_vld,
        window_adjust_1_0_6_i,
        window_adjust_1_0_6_o,
        window_adjust_1_0_6_o_ap_vld,
        window_adjust_2_0_6_i,
        window_adjust_2_0_6_o,
        window_adjust_2_0_6_o_ap_vld,
        window_adjust_0_0_7_i,
        window_adjust_0_0_7_o,
        window_adjust_0_0_7_o_ap_vld,
        window_adjust_1_0_7_i,
        window_adjust_1_0_7_o,
        window_adjust_1_0_7_o_ap_vld,
        window_adjust_2_0_7_i,
        window_adjust_2_0_7_o,
        window_adjust_2_0_7_o_ap_vld,
        window_adjust_0_2_0_i,
        window_adjust_0_2_0_o,
        window_adjust_0_2_0_o_ap_vld,
        window_adjust_1_2_0_i,
        window_adjust_1_2_0_o,
        window_adjust_1_2_0_o_ap_vld,
        window_adjust_2_2_0_i,
        window_adjust_2_2_0_o,
        window_adjust_2_2_0_o_ap_vld,
        window_adjust_0_2_1_i,
        window_adjust_0_2_1_o,
        window_adjust_0_2_1_o_ap_vld,
        window_adjust_1_2_1_i,
        window_adjust_1_2_1_o,
        window_adjust_1_2_1_o_ap_vld,
        window_adjust_2_2_1_i,
        window_adjust_2_2_1_o,
        window_adjust_2_2_1_o_ap_vld,
        window_adjust_0_2_2_i,
        window_adjust_0_2_2_o,
        window_adjust_0_2_2_o_ap_vld,
        window_adjust_1_2_2_i,
        window_adjust_1_2_2_o,
        window_adjust_1_2_2_o_ap_vld,
        window_adjust_2_2_2_i,
        window_adjust_2_2_2_o,
        window_adjust_2_2_2_o_ap_vld,
        window_adjust_0_2_3_i,
        window_adjust_0_2_3_o,
        window_adjust_0_2_3_o_ap_vld,
        window_adjust_1_2_3_i,
        window_adjust_1_2_3_o,
        window_adjust_1_2_3_o_ap_vld,
        window_adjust_2_2_3_i,
        window_adjust_2_2_3_o,
        window_adjust_2_2_3_o_ap_vld,
        window_adjust_0_2_4_i,
        window_adjust_0_2_4_o,
        window_adjust_0_2_4_o_ap_vld,
        window_adjust_1_2_4_i,
        window_adjust_1_2_4_o,
        window_adjust_1_2_4_o_ap_vld,
        window_adjust_2_2_4_i,
        window_adjust_2_2_4_o,
        window_adjust_2_2_4_o_ap_vld,
        window_adjust_0_2_5_i,
        window_adjust_0_2_5_o,
        window_adjust_0_2_5_o_ap_vld,
        window_adjust_1_2_5_i,
        window_adjust_1_2_5_o,
        window_adjust_1_2_5_o_ap_vld,
        window_adjust_2_2_5_i,
        window_adjust_2_2_5_o,
        window_adjust_2_2_5_o_ap_vld,
        window_adjust_0_2_6_i,
        window_adjust_0_2_6_o,
        window_adjust_0_2_6_o_ap_vld,
        window_adjust_1_2_6_i,
        window_adjust_1_2_6_o,
        window_adjust_1_2_6_o_ap_vld,
        window_adjust_2_2_6_i,
        window_adjust_2_2_6_o,
        window_adjust_2_2_6_o_ap_vld,
        window_adjust_0_2_7_i,
        window_adjust_0_2_7_o,
        window_adjust_0_2_7_o_ap_vld,
        window_adjust_1_2_7_i,
        window_adjust_1_2_7_o,
        window_adjust_1_2_7_o_ap_vld,
        window_adjust_2_2_7_i,
        window_adjust_2_2_7_o,
        window_adjust_2_2_7_o_ap_vld,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [10:0] row;
output  [6:0] linebuf_0_0_address0;
output   linebuf_0_0_ce0;
input  [79:0] linebuf_0_0_q0;
output  [6:0] linebuf_0_1_address0;
output   linebuf_0_1_ce0;
input  [79:0] linebuf_0_1_q0;
output  [6:0] linebuf_1_0_address0;
output   linebuf_1_0_ce0;
input  [79:0] linebuf_1_0_q0;
output  [6:0] linebuf_1_1_address0;
output   linebuf_1_1_ce0;
input  [79:0] linebuf_1_1_q0;
output  [6:0] linebuf_2_0_address0;
output   linebuf_2_0_ce0;
input  [79:0] linebuf_2_0_q0;
output  [6:0] linebuf_2_1_address0;
output   linebuf_2_1_ce0;
input  [79:0] linebuf_2_1_q0;
input  [9:0] window_adjust_0_0_0_i;
output  [9:0] window_adjust_0_0_0_o;
output   window_adjust_0_0_0_o_ap_vld;
input  [9:0] window_adjust_1_0_0_i;
output  [9:0] window_adjust_1_0_0_o;
output   window_adjust_1_0_0_o_ap_vld;
input  [9:0] window_adjust_2_0_0_i;
output  [9:0] window_adjust_2_0_0_o;
output   window_adjust_2_0_0_o_ap_vld;
input  [9:0] window_adjust_0_0_1_i;
output  [9:0] window_adjust_0_0_1_o;
output   window_adjust_0_0_1_o_ap_vld;
input  [9:0] window_adjust_1_0_1_i;
output  [9:0] window_adjust_1_0_1_o;
output   window_adjust_1_0_1_o_ap_vld;
input  [9:0] window_adjust_2_0_1_i;
output  [9:0] window_adjust_2_0_1_o;
output   window_adjust_2_0_1_o_ap_vld;
input  [9:0] window_adjust_0_0_2_i;
output  [9:0] window_adjust_0_0_2_o;
output   window_adjust_0_0_2_o_ap_vld;
input  [9:0] window_adjust_1_0_2_i;
output  [9:0] window_adjust_1_0_2_o;
output   window_adjust_1_0_2_o_ap_vld;
input  [9:0] window_adjust_2_0_2_i;
output  [9:0] window_adjust_2_0_2_o;
output   window_adjust_2_0_2_o_ap_vld;
input  [9:0] window_adjust_0_0_3_i;
output  [9:0] window_adjust_0_0_3_o;
output   window_adjust_0_0_3_o_ap_vld;
input  [9:0] window_adjust_1_0_3_i;
output  [9:0] window_adjust_1_0_3_o;
output   window_adjust_1_0_3_o_ap_vld;
input  [9:0] window_adjust_2_0_3_i;
output  [9:0] window_adjust_2_0_3_o;
output   window_adjust_2_0_3_o_ap_vld;
input  [9:0] window_adjust_0_0_4_i;
output  [9:0] window_adjust_0_0_4_o;
output   window_adjust_0_0_4_o_ap_vld;
input  [9:0] window_adjust_1_0_4_i;
output  [9:0] window_adjust_1_0_4_o;
output   window_adjust_1_0_4_o_ap_vld;
input  [9:0] window_adjust_2_0_4_i;
output  [9:0] window_adjust_2_0_4_o;
output   window_adjust_2_0_4_o_ap_vld;
input  [9:0] window_adjust_0_0_5_i;
output  [9:0] window_adjust_0_0_5_o;
output   window_adjust_0_0_5_o_ap_vld;
input  [9:0] window_adjust_1_0_5_i;
output  [9:0] window_adjust_1_0_5_o;
output   window_adjust_1_0_5_o_ap_vld;
input  [9:0] window_adjust_2_0_5_i;
output  [9:0] window_adjust_2_0_5_o;
output   window_adjust_2_0_5_o_ap_vld;
input  [9:0] window_adjust_0_0_6_i;
output  [9:0] window_adjust_0_0_6_o;
output   window_adjust_0_0_6_o_ap_vld;
input  [9:0] window_adjust_1_0_6_i;
output  [9:0] window_adjust_1_0_6_o;
output   window_adjust_1_0_6_o_ap_vld;
input  [9:0] window_adjust_2_0_6_i;
output  [9:0] window_adjust_2_0_6_o;
output   window_adjust_2_0_6_o_ap_vld;
input  [9:0] window_adjust_0_0_7_i;
output  [9:0] window_adjust_0_0_7_o;
output   window_adjust_0_0_7_o_ap_vld;
input  [9:0] window_adjust_1_0_7_i;
output  [9:0] window_adjust_1_0_7_o;
output   window_adjust_1_0_7_o_ap_vld;
input  [9:0] window_adjust_2_0_7_i;
output  [9:0] window_adjust_2_0_7_o;
output   window_adjust_2_0_7_o_ap_vld;
input  [9:0] window_adjust_0_2_0_i;
output  [9:0] window_adjust_0_2_0_o;
output   window_adjust_0_2_0_o_ap_vld;
input  [9:0] window_adjust_1_2_0_i;
output  [9:0] window_adjust_1_2_0_o;
output   window_adjust_1_2_0_o_ap_vld;
input  [9:0] window_adjust_2_2_0_i;
output  [9:0] window_adjust_2_2_0_o;
output   window_adjust_2_2_0_o_ap_vld;
input  [9:0] window_adjust_0_2_1_i;
output  [9:0] window_adjust_0_2_1_o;
output   window_adjust_0_2_1_o_ap_vld;
input  [9:0] window_adjust_1_2_1_i;
output  [9:0] window_adjust_1_2_1_o;
output   window_adjust_1_2_1_o_ap_vld;
input  [9:0] window_adjust_2_2_1_i;
output  [9:0] window_adjust_2_2_1_o;
output   window_adjust_2_2_1_o_ap_vld;
input  [9:0] window_adjust_0_2_2_i;
output  [9:0] window_adjust_0_2_2_o;
output   window_adjust_0_2_2_o_ap_vld;
input  [9:0] window_adjust_1_2_2_i;
output  [9:0] window_adjust_1_2_2_o;
output   window_adjust_1_2_2_o_ap_vld;
input  [9:0] window_adjust_2_2_2_i;
output  [9:0] window_adjust_2_2_2_o;
output   window_adjust_2_2_2_o_ap_vld;
input  [9:0] window_adjust_0_2_3_i;
output  [9:0] window_adjust_0_2_3_o;
output   window_adjust_0_2_3_o_ap_vld;
input  [9:0] window_adjust_1_2_3_i;
output  [9:0] window_adjust_1_2_3_o;
output   window_adjust_1_2_3_o_ap_vld;
input  [9:0] window_adjust_2_2_3_i;
output  [9:0] window_adjust_2_2_3_o;
output   window_adjust_2_2_3_o_ap_vld;
input  [9:0] window_adjust_0_2_4_i;
output  [9:0] window_adjust_0_2_4_o;
output   window_adjust_0_2_4_o_ap_vld;
input  [9:0] window_adjust_1_2_4_i;
output  [9:0] window_adjust_1_2_4_o;
output   window_adjust_1_2_4_o_ap_vld;
input  [9:0] window_adjust_2_2_4_i;
output  [9:0] window_adjust_2_2_4_o;
output   window_adjust_2_2_4_o_ap_vld;
input  [9:0] window_adjust_0_2_5_i;
output  [9:0] window_adjust_0_2_5_o;
output   window_adjust_0_2_5_o_ap_vld;
input  [9:0] window_adjust_1_2_5_i;
output  [9:0] window_adjust_1_2_5_o;
output   window_adjust_1_2_5_o_ap_vld;
input  [9:0] window_adjust_2_2_5_i;
output  [9:0] window_adjust_2_2_5_o;
output   window_adjust_2_2_5_o_ap_vld;
input  [9:0] window_adjust_0_2_6_i;
output  [9:0] window_adjust_0_2_6_o;
output   window_adjust_0_2_6_o_ap_vld;
input  [9:0] window_adjust_1_2_6_i;
output  [9:0] window_adjust_1_2_6_o;
output   window_adjust_1_2_6_o_ap_vld;
input  [9:0] window_adjust_2_2_6_i;
output  [9:0] window_adjust_2_2_6_o;
output   window_adjust_2_2_6_o_ap_vld;
input  [9:0] window_adjust_0_2_7_i;
output  [9:0] window_adjust_0_2_7_o;
output   window_adjust_0_2_7_o_ap_vld;
input  [9:0] window_adjust_1_2_7_i;
output  [9:0] window_adjust_1_2_7_o;
output   window_adjust_1_2_7_o_ap_vld;
input  [9:0] window_adjust_2_2_7_i;
output  [9:0] window_adjust_2_2_7_o;
output   window_adjust_2_2_7_o_ap_vld;
output  [79:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg linebuf_0_0_ce0;
reg linebuf_0_1_ce0;
reg linebuf_1_0_ce0;
reg linebuf_1_1_ce0;
reg linebuf_2_0_ce0;
reg linebuf_2_1_ce0;
reg[9:0] window_adjust_0_0_0_o;
reg window_adjust_0_0_0_o_ap_vld;
reg[9:0] window_adjust_1_0_0_o;
reg window_adjust_1_0_0_o_ap_vld;
reg[9:0] window_adjust_2_0_0_o;
reg window_adjust_2_0_0_o_ap_vld;
reg[9:0] window_adjust_0_0_1_o;
reg window_adjust_0_0_1_o_ap_vld;
reg[9:0] window_adjust_1_0_1_o;
reg window_adjust_1_0_1_o_ap_vld;
reg[9:0] window_adjust_2_0_1_o;
reg window_adjust_2_0_1_o_ap_vld;
reg[9:0] window_adjust_0_0_2_o;
reg window_adjust_0_0_2_o_ap_vld;
reg[9:0] window_adjust_1_0_2_o;
reg window_adjust_1_0_2_o_ap_vld;
reg[9:0] window_adjust_2_0_2_o;
reg window_adjust_2_0_2_o_ap_vld;
reg[9:0] window_adjust_0_0_3_o;
reg window_adjust_0_0_3_o_ap_vld;
reg[9:0] window_adjust_1_0_3_o;
reg window_adjust_1_0_3_o_ap_vld;
reg[9:0] window_adjust_2_0_3_o;
reg window_adjust_2_0_3_o_ap_vld;
reg[9:0] window_adjust_0_0_4_o;
reg window_adjust_0_0_4_o_ap_vld;
reg[9:0] window_adjust_1_0_4_o;
reg window_adjust_1_0_4_o_ap_vld;
reg[9:0] window_adjust_2_0_4_o;
reg window_adjust_2_0_4_o_ap_vld;
reg[9:0] window_adjust_0_0_5_o;
reg window_adjust_0_0_5_o_ap_vld;
reg[9:0] window_adjust_1_0_5_o;
reg window_adjust_1_0_5_o_ap_vld;
reg[9:0] window_adjust_2_0_5_o;
reg window_adjust_2_0_5_o_ap_vld;
reg[9:0] window_adjust_0_0_6_o;
reg window_adjust_0_0_6_o_ap_vld;
reg[9:0] window_adjust_1_0_6_o;
reg window_adjust_1_0_6_o_ap_vld;
reg[9:0] window_adjust_2_0_6_o;
reg window_adjust_2_0_6_o_ap_vld;
reg[9:0] window_adjust_0_0_7_o;
reg window_adjust_0_0_7_o_ap_vld;
reg[9:0] window_adjust_1_0_7_o;
reg window_adjust_1_0_7_o_ap_vld;
reg[9:0] window_adjust_2_0_7_o;
reg window_adjust_2_0_7_o_ap_vld;
reg[9:0] window_adjust_0_2_0_o;
reg window_adjust_0_2_0_o_ap_vld;
reg[9:0] window_adjust_1_2_0_o;
reg window_adjust_1_2_0_o_ap_vld;
reg[9:0] window_adjust_2_2_0_o;
reg window_adjust_2_2_0_o_ap_vld;
reg[9:0] window_adjust_0_2_1_o;
reg window_adjust_0_2_1_o_ap_vld;
reg[9:0] window_adjust_1_2_1_o;
reg window_adjust_1_2_1_o_ap_vld;
reg[9:0] window_adjust_2_2_1_o;
reg window_adjust_2_2_1_o_ap_vld;
reg[9:0] window_adjust_0_2_2_o;
reg window_adjust_0_2_2_o_ap_vld;
reg[9:0] window_adjust_1_2_2_o;
reg window_adjust_1_2_2_o_ap_vld;
reg[9:0] window_adjust_2_2_2_o;
reg window_adjust_2_2_2_o_ap_vld;
reg[9:0] window_adjust_0_2_3_o;
reg window_adjust_0_2_3_o_ap_vld;
reg[9:0] window_adjust_1_2_3_o;
reg window_adjust_1_2_3_o_ap_vld;
reg[9:0] window_adjust_2_2_3_o;
reg window_adjust_2_2_3_o_ap_vld;
reg[9:0] window_adjust_0_2_4_o;
reg window_adjust_0_2_4_o_ap_vld;
reg[9:0] window_adjust_1_2_4_o;
reg window_adjust_1_2_4_o_ap_vld;
reg[9:0] window_adjust_2_2_4_o;
reg window_adjust_2_2_4_o_ap_vld;
reg[9:0] window_adjust_0_2_5_o;
reg window_adjust_0_2_5_o_ap_vld;
reg[9:0] window_adjust_1_2_5_o;
reg window_adjust_1_2_5_o_ap_vld;
reg[9:0] window_adjust_2_2_5_o;
reg window_adjust_2_2_5_o_ap_vld;
reg[9:0] window_adjust_0_2_6_o;
reg window_adjust_0_2_6_o_ap_vld;
reg[9:0] window_adjust_1_2_6_o;
reg window_adjust_1_2_6_o_ap_vld;
reg[9:0] window_adjust_2_2_6_o;
reg window_adjust_2_2_6_o_ap_vld;
reg[9:0] window_adjust_0_2_7_o;
reg window_adjust_0_2_7_o_ap_vld;
reg[9:0] window_adjust_1_2_7_o;
reg window_adjust_1_2_7_o_ap_vld;
reg[9:0] window_adjust_2_2_7_o;
reg window_adjust_2_2_7_o_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage0_11001;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
reg   [10:0] ap_port_reg_row;
wire    tmp_sobelConvolve_fu_242_ap_ready;
wire   [79:0] tmp_sobelConvolve_fu_242_ap_return;
wire    ap_block_pp0_stage0;
wire   [9:0] select_ln117_fu_588_p3;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire   [9:0] trunc_ln101_1_fu_420_p1;
wire   [9:0] select_ln119_fu_660_p3;
wire   [9:0] select_ln117_1_fu_596_p3;
wire   [9:0] tmp_i_fu_424_p4;
wire   [9:0] select_ln119_1_fu_668_p3;
wire   [9:0] select_ln117_2_fu_604_p3;
wire   [9:0] tmp_10_i_fu_434_p4;
wire   [9:0] select_ln119_2_fu_676_p3;
wire   [9:0] select_ln117_3_fu_612_p3;
wire   [9:0] tmp_11_i_fu_444_p4;
wire   [9:0] select_ln119_3_fu_684_p3;
wire   [9:0] select_ln117_4_fu_620_p3;
wire   [9:0] tmp_12_i_fu_454_p4;
wire   [9:0] select_ln119_4_fu_692_p3;
wire   [9:0] select_ln117_5_fu_628_p3;
wire   [9:0] tmp_13_i_fu_464_p4;
wire   [9:0] select_ln119_5_fu_700_p3;
wire   [9:0] select_ln117_6_fu_636_p3;
wire   [9:0] tmp_14_i_fu_474_p4;
wire   [9:0] select_ln119_6_fu_708_p3;
wire   [9:0] select_ln117_7_fu_644_p3;
wire   [9:0] tmp_15_i_fu_484_p4;
wire   [9:0] select_ln119_7_fu_716_p3;
wire   [9:0] select_ln117_8_fu_652_p3;
wire   [9:0] trunc_ln105_1_fu_494_p1;
wire   [9:0] select_ln119_8_fu_724_p3;
wire   [0:0] cmp97_i_fu_576_p2;
wire   [9:0] trunc_ln101_fu_342_p1;
wire   [9:0] tmp_1_i_fu_346_p4;
wire   [9:0] tmp_2_i_fu_356_p4;
wire   [9:0] tmp_3_i_fu_366_p4;
wire   [9:0] tmp_4_i_fu_376_p4;
wire   [9:0] tmp_5_i_fu_386_p4;
wire   [9:0] tmp_6_i_fu_396_p4;
wire   [9:0] tmp_7_i_fu_406_p4;
wire   [9:0] trunc_ln105_fu_416_p1;
wire   [0:0] cmp122_i_fu_582_p2;
wire   [9:0] trunc_ln101_2_fu_498_p1;
wire   [9:0] tmp_18_i_fu_502_p4;
wire   [9:0] tmp_19_i_fu_512_p4;
wire   [9:0] tmp_20_i_fu_522_p4;
wire   [9:0] tmp_21_i_fu_532_p4;
wire   [9:0] tmp_22_i_fu_542_p4;
wire   [9:0] tmp_23_i_fu_552_p4;
wire   [9:0] tmp_24_i_fu_562_p4;
wire   [9:0] trunc_ln105_2_fu_572_p1;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

conv2d_3x3_sobelConvolve tmp_sobelConvolve_fu_242(
    .ap_ready(tmp_sobelConvolve_fu_242_ap_ready),
    .window_adjust_0_0_0(window_adjust_0_0_0_i),
    .window_adjust_0_2_0(window_adjust_0_2_0_i),
    .window_adjust_1_0_0(window_adjust_1_0_0_i),
    .window_adjust_1_2_0(window_adjust_1_2_0_i),
    .window_adjust_2_0_0(window_adjust_2_0_0_i),
    .window_adjust_2_2_0(window_adjust_2_2_0_i),
    .window_adjust_0_0_1(window_adjust_0_0_1_i),
    .window_adjust_0_2_1(window_adjust_0_2_1_i),
    .window_adjust_1_0_1(window_adjust_1_0_1_i),
    .window_adjust_1_2_1(window_adjust_1_2_1_i),
    .window_adjust_2_0_1(window_adjust_2_0_1_i),
    .window_adjust_2_2_1(window_adjust_2_2_1_i),
    .window_adjust_0_0_2(window_adjust_0_0_2_i),
    .window_adjust_0_2_2(window_adjust_0_2_2_i),
    .window_adjust_1_0_2(window_adjust_1_0_2_i),
    .window_adjust_1_2_2(window_adjust_1_2_2_i),
    .window_adjust_2_0_2(window_adjust_2_0_2_i),
    .window_adjust_2_2_2(window_adjust_2_2_2_i),
    .window_adjust_0_0_3(window_adjust_0_0_3_i),
    .window_adjust_0_2_3(window_adjust_0_2_3_i),
    .window_adjust_1_0_3(window_adjust_1_0_3_i),
    .window_adjust_1_2_3(window_adjust_1_2_3_i),
    .window_adjust_2_0_3(window_adjust_2_0_3_i),
    .window_adjust_2_2_3(window_adjust_2_2_3_i),
    .window_adjust_0_0_4(window_adjust_0_0_4_i),
    .window_adjust_0_2_4(window_adjust_0_2_4_i),
    .window_adjust_1_0_4(window_adjust_1_0_4_i),
    .window_adjust_1_2_4(window_adjust_1_2_4_i),
    .window_adjust_2_0_4(window_adjust_2_0_4_i),
    .window_adjust_2_2_4(window_adjust_2_2_4_i),
    .window_adjust_0_0_5(window_adjust_0_0_5_i),
    .window_adjust_0_2_5(window_adjust_0_2_5_i),
    .window_adjust_1_0_5(window_adjust_1_0_5_i),
    .window_adjust_1_2_5(window_adjust_1_2_5_i),
    .window_adjust_2_0_5(window_adjust_2_0_5_i),
    .window_adjust_2_2_5(window_adjust_2_2_5_i),
    .window_adjust_0_0_6(window_adjust_0_0_6_i),
    .window_adjust_0_2_6(window_adjust_0_2_6_i),
    .window_adjust_1_0_6(window_adjust_1_0_6_i),
    .window_adjust_1_2_6(window_adjust_1_2_6_i),
    .window_adjust_2_0_6(window_adjust_2_0_6_i),
    .window_adjust_2_2_6(window_adjust_2_2_6_i),
    .window_adjust_0_0_7(window_adjust_0_0_7_i),
    .window_adjust_0_2_7(window_adjust_0_2_7_i),
    .window_adjust_1_0_7(window_adjust_1_0_7_i),
    .window_adjust_1_2_7(window_adjust_1_2_7_i),
    .window_adjust_2_0_7(window_adjust_2_0_7_i),
    .window_adjust_2_2_7(window_adjust_2_2_7_i),
    .ap_return(tmp_sobelConvolve_fu_242_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_port_reg_row <= row;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_0_0_ce0 = 1'b1;
    end else begin
        linebuf_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_0_1_ce0 = 1'b1;
    end else begin
        linebuf_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_1_0_ce0 = 1'b1;
    end else begin
        linebuf_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_1_1_ce0 = 1'b1;
    end else begin
        linebuf_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_2_0_ce0 = 1'b1;
    end else begin
        linebuf_2_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuf_2_1_ce0 = 1'b1;
    end else begin
        linebuf_2_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_0_0_o = select_ln117_fu_588_p3;
    end else begin
        window_adjust_0_0_0_o = window_adjust_0_0_0_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_0_0_o_ap_vld = 1'b1;
    end else begin
        window_adjust_0_0_0_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_0_1_o = select_ln117_1_fu_596_p3;
    end else begin
        window_adjust_0_0_1_o = window_adjust_0_0_1_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_0_1_o_ap_vld = 1'b1;
    end else begin
        window_adjust_0_0_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_0_2_o = select_ln117_2_fu_604_p3;
    end else begin
        window_adjust_0_0_2_o = window_adjust_0_0_2_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_0_2_o_ap_vld = 1'b1;
    end else begin
        window_adjust_0_0_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_0_3_o = select_ln117_3_fu_612_p3;
    end else begin
        window_adjust_0_0_3_o = window_adjust_0_0_3_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_0_3_o_ap_vld = 1'b1;
    end else begin
        window_adjust_0_0_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_0_4_o = select_ln117_4_fu_620_p3;
    end else begin
        window_adjust_0_0_4_o = window_adjust_0_0_4_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_0_4_o_ap_vld = 1'b1;
    end else begin
        window_adjust_0_0_4_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_0_5_o = select_ln117_5_fu_628_p3;
    end else begin
        window_adjust_0_0_5_o = window_adjust_0_0_5_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_0_5_o_ap_vld = 1'b1;
    end else begin
        window_adjust_0_0_5_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_0_6_o = select_ln117_6_fu_636_p3;
    end else begin
        window_adjust_0_0_6_o = window_adjust_0_0_6_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_0_6_o_ap_vld = 1'b1;
    end else begin
        window_adjust_0_0_6_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_0_7_o = select_ln117_7_fu_644_p3;
    end else begin
        window_adjust_0_0_7_o = window_adjust_0_0_7_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_0_7_o_ap_vld = 1'b1;
    end else begin
        window_adjust_0_0_7_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_2_0_o = select_ln117_2_fu_604_p3;
    end else begin
        window_adjust_0_2_0_o = window_adjust_0_2_0_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_2_0_o_ap_vld = 1'b1;
    end else begin
        window_adjust_0_2_0_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_2_1_o = select_ln117_3_fu_612_p3;
    end else begin
        window_adjust_0_2_1_o = window_adjust_0_2_1_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_2_1_o_ap_vld = 1'b1;
    end else begin
        window_adjust_0_2_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_2_2_o = select_ln117_4_fu_620_p3;
    end else begin
        window_adjust_0_2_2_o = window_adjust_0_2_2_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_2_2_o_ap_vld = 1'b1;
    end else begin
        window_adjust_0_2_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_2_3_o = select_ln117_5_fu_628_p3;
    end else begin
        window_adjust_0_2_3_o = window_adjust_0_2_3_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_2_3_o_ap_vld = 1'b1;
    end else begin
        window_adjust_0_2_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_2_4_o = select_ln117_6_fu_636_p3;
    end else begin
        window_adjust_0_2_4_o = window_adjust_0_2_4_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_2_4_o_ap_vld = 1'b1;
    end else begin
        window_adjust_0_2_4_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_2_5_o = select_ln117_7_fu_644_p3;
    end else begin
        window_adjust_0_2_5_o = window_adjust_0_2_5_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_2_5_o_ap_vld = 1'b1;
    end else begin
        window_adjust_0_2_5_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_2_6_o = select_ln117_8_fu_652_p3;
    end else begin
        window_adjust_0_2_6_o = window_adjust_0_2_6_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_2_6_o_ap_vld = 1'b1;
    end else begin
        window_adjust_0_2_6_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_2_7_o = select_ln117_1_fu_596_p3;
    end else begin
        window_adjust_0_2_7_o = window_adjust_0_2_7_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_0_2_7_o_ap_vld = 1'b1;
    end else begin
        window_adjust_0_2_7_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_0_0_o = trunc_ln101_1_fu_420_p1;
    end else begin
        window_adjust_1_0_0_o = window_adjust_1_0_0_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_0_0_o_ap_vld = 1'b1;
    end else begin
        window_adjust_1_0_0_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_0_1_o = {{linebuf_1_1_q0[79:70]}};
    end else begin
        window_adjust_1_0_1_o = window_adjust_1_0_1_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_0_1_o_ap_vld = 1'b1;
    end else begin
        window_adjust_1_0_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_0_2_o = {{linebuf_1_1_q0[69:60]}};
    end else begin
        window_adjust_1_0_2_o = window_adjust_1_0_2_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_0_2_o_ap_vld = 1'b1;
    end else begin
        window_adjust_1_0_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_0_3_o = {{linebuf_1_1_q0[59:50]}};
    end else begin
        window_adjust_1_0_3_o = window_adjust_1_0_3_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_0_3_o_ap_vld = 1'b1;
    end else begin
        window_adjust_1_0_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_0_4_o = {{linebuf_1_1_q0[49:40]}};
    end else begin
        window_adjust_1_0_4_o = window_adjust_1_0_4_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_0_4_o_ap_vld = 1'b1;
    end else begin
        window_adjust_1_0_4_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_0_5_o = {{linebuf_1_1_q0[39:30]}};
    end else begin
        window_adjust_1_0_5_o = window_adjust_1_0_5_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_0_5_o_ap_vld = 1'b1;
    end else begin
        window_adjust_1_0_5_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_0_6_o = {{linebuf_1_1_q0[29:20]}};
    end else begin
        window_adjust_1_0_6_o = window_adjust_1_0_6_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_0_6_o_ap_vld = 1'b1;
    end else begin
        window_adjust_1_0_6_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_0_7_o = {{linebuf_1_1_q0[19:10]}};
    end else begin
        window_adjust_1_0_7_o = window_adjust_1_0_7_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_0_7_o_ap_vld = 1'b1;
    end else begin
        window_adjust_1_0_7_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_2_0_o = {{linebuf_1_1_q0[69:60]}};
    end else begin
        window_adjust_1_2_0_o = window_adjust_1_2_0_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_2_0_o_ap_vld = 1'b1;
    end else begin
        window_adjust_1_2_0_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_2_1_o = {{linebuf_1_1_q0[59:50]}};
    end else begin
        window_adjust_1_2_1_o = window_adjust_1_2_1_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_2_1_o_ap_vld = 1'b1;
    end else begin
        window_adjust_1_2_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_2_2_o = {{linebuf_1_1_q0[49:40]}};
    end else begin
        window_adjust_1_2_2_o = window_adjust_1_2_2_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_2_2_o_ap_vld = 1'b1;
    end else begin
        window_adjust_1_2_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_2_3_o = {{linebuf_1_1_q0[39:30]}};
    end else begin
        window_adjust_1_2_3_o = window_adjust_1_2_3_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_2_3_o_ap_vld = 1'b1;
    end else begin
        window_adjust_1_2_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_2_4_o = {{linebuf_1_1_q0[29:20]}};
    end else begin
        window_adjust_1_2_4_o = window_adjust_1_2_4_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_2_4_o_ap_vld = 1'b1;
    end else begin
        window_adjust_1_2_4_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_2_5_o = {{linebuf_1_1_q0[19:10]}};
    end else begin
        window_adjust_1_2_5_o = window_adjust_1_2_5_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_2_5_o_ap_vld = 1'b1;
    end else begin
        window_adjust_1_2_5_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_2_6_o = trunc_ln105_1_fu_494_p1;
    end else begin
        window_adjust_1_2_6_o = window_adjust_1_2_6_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_2_6_o_ap_vld = 1'b1;
    end else begin
        window_adjust_1_2_6_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_2_7_o = {{linebuf_1_1_q0[79:70]}};
    end else begin
        window_adjust_1_2_7_o = window_adjust_1_2_7_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_1_2_7_o_ap_vld = 1'b1;
    end else begin
        window_adjust_1_2_7_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_0_0_o = select_ln119_fu_660_p3;
    end else begin
        window_adjust_2_0_0_o = window_adjust_2_0_0_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_0_0_o_ap_vld = 1'b1;
    end else begin
        window_adjust_2_0_0_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_0_1_o = select_ln119_1_fu_668_p3;
    end else begin
        window_adjust_2_0_1_o = window_adjust_2_0_1_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_0_1_o_ap_vld = 1'b1;
    end else begin
        window_adjust_2_0_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_0_2_o = select_ln119_2_fu_676_p3;
    end else begin
        window_adjust_2_0_2_o = window_adjust_2_0_2_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_0_2_o_ap_vld = 1'b1;
    end else begin
        window_adjust_2_0_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_0_3_o = select_ln119_3_fu_684_p3;
    end else begin
        window_adjust_2_0_3_o = window_adjust_2_0_3_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_0_3_o_ap_vld = 1'b1;
    end else begin
        window_adjust_2_0_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_0_4_o = select_ln119_4_fu_692_p3;
    end else begin
        window_adjust_2_0_4_o = window_adjust_2_0_4_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_0_4_o_ap_vld = 1'b1;
    end else begin
        window_adjust_2_0_4_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_0_5_o = select_ln119_5_fu_700_p3;
    end else begin
        window_adjust_2_0_5_o = window_adjust_2_0_5_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_0_5_o_ap_vld = 1'b1;
    end else begin
        window_adjust_2_0_5_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_0_6_o = select_ln119_6_fu_708_p3;
    end else begin
        window_adjust_2_0_6_o = window_adjust_2_0_6_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_0_6_o_ap_vld = 1'b1;
    end else begin
        window_adjust_2_0_6_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_0_7_o = select_ln119_7_fu_716_p3;
    end else begin
        window_adjust_2_0_7_o = window_adjust_2_0_7_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_0_7_o_ap_vld = 1'b1;
    end else begin
        window_adjust_2_0_7_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_2_0_o = select_ln119_2_fu_676_p3;
    end else begin
        window_adjust_2_2_0_o = window_adjust_2_2_0_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_2_0_o_ap_vld = 1'b1;
    end else begin
        window_adjust_2_2_0_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_2_1_o = select_ln119_3_fu_684_p3;
    end else begin
        window_adjust_2_2_1_o = window_adjust_2_2_1_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_2_1_o_ap_vld = 1'b1;
    end else begin
        window_adjust_2_2_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_2_2_o = select_ln119_4_fu_692_p3;
    end else begin
        window_adjust_2_2_2_o = window_adjust_2_2_2_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_2_2_o_ap_vld = 1'b1;
    end else begin
        window_adjust_2_2_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_2_3_o = select_ln119_5_fu_700_p3;
    end else begin
        window_adjust_2_2_3_o = window_adjust_2_2_3_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_2_3_o_ap_vld = 1'b1;
    end else begin
        window_adjust_2_2_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_2_4_o = select_ln119_6_fu_708_p3;
    end else begin
        window_adjust_2_2_4_o = window_adjust_2_2_4_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_2_4_o_ap_vld = 1'b1;
    end else begin
        window_adjust_2_2_4_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_2_5_o = select_ln119_7_fu_716_p3;
    end else begin
        window_adjust_2_2_5_o = window_adjust_2_2_5_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_2_5_o_ap_vld = 1'b1;
    end else begin
        window_adjust_2_2_5_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_2_6_o = select_ln119_8_fu_724_p3;
    end else begin
        window_adjust_2_2_6_o = window_adjust_2_2_6_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_2_6_o_ap_vld = 1'b1;
    end else begin
        window_adjust_2_2_6_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_2_7_o = select_ln119_1_fu_668_p3;
    end else begin
        window_adjust_2_2_7_o = window_adjust_2_2_7_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        window_adjust_2_2_7_o_ap_vld = 1'b1;
    end else begin
        window_adjust_2_2_7_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (ap_reset_idle_pp0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((ap_reset_idle_pp0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_return = tmp_sobelConvolve_fu_242_ap_return;

assign cmp122_i_fu_582_p2 = ((ap_port_reg_row == 11'd1080) ? 1'b1 : 1'b0);

assign cmp97_i_fu_576_p2 = ((ap_port_reg_row == 11'd1) ? 1'b1 : 1'b0);

assign linebuf_0_0_address0 = 64'd119;

assign linebuf_0_1_address0 = 64'd119;

assign linebuf_1_0_address0 = 64'd119;

assign linebuf_1_1_address0 = 64'd119;

assign linebuf_2_0_address0 = 64'd119;

assign linebuf_2_1_address0 = 64'd119;

assign select_ln117_1_fu_596_p3 = ((cmp97_i_fu_576_p2[0:0] == 1'b1) ? tmp_i_fu_424_p4 : tmp_1_i_fu_346_p4);

assign select_ln117_2_fu_604_p3 = ((cmp97_i_fu_576_p2[0:0] == 1'b1) ? tmp_10_i_fu_434_p4 : tmp_2_i_fu_356_p4);

assign select_ln117_3_fu_612_p3 = ((cmp97_i_fu_576_p2[0:0] == 1'b1) ? tmp_11_i_fu_444_p4 : tmp_3_i_fu_366_p4);

assign select_ln117_4_fu_620_p3 = ((cmp97_i_fu_576_p2[0:0] == 1'b1) ? tmp_12_i_fu_454_p4 : tmp_4_i_fu_376_p4);

assign select_ln117_5_fu_628_p3 = ((cmp97_i_fu_576_p2[0:0] == 1'b1) ? tmp_13_i_fu_464_p4 : tmp_5_i_fu_386_p4);

assign select_ln117_6_fu_636_p3 = ((cmp97_i_fu_576_p2[0:0] == 1'b1) ? tmp_14_i_fu_474_p4 : tmp_6_i_fu_396_p4);

assign select_ln117_7_fu_644_p3 = ((cmp97_i_fu_576_p2[0:0] == 1'b1) ? tmp_15_i_fu_484_p4 : tmp_7_i_fu_406_p4);

assign select_ln117_8_fu_652_p3 = ((cmp97_i_fu_576_p2[0:0] == 1'b1) ? trunc_ln105_1_fu_494_p1 : trunc_ln105_fu_416_p1);

assign select_ln117_fu_588_p3 = ((cmp97_i_fu_576_p2[0:0] == 1'b1) ? trunc_ln101_1_fu_420_p1 : trunc_ln101_fu_342_p1);

assign select_ln119_1_fu_668_p3 = ((cmp122_i_fu_582_p2[0:0] == 1'b1) ? tmp_i_fu_424_p4 : tmp_18_i_fu_502_p4);

assign select_ln119_2_fu_676_p3 = ((cmp122_i_fu_582_p2[0:0] == 1'b1) ? tmp_10_i_fu_434_p4 : tmp_19_i_fu_512_p4);

assign select_ln119_3_fu_684_p3 = ((cmp122_i_fu_582_p2[0:0] == 1'b1) ? tmp_11_i_fu_444_p4 : tmp_20_i_fu_522_p4);

assign select_ln119_4_fu_692_p3 = ((cmp122_i_fu_582_p2[0:0] == 1'b1) ? tmp_12_i_fu_454_p4 : tmp_21_i_fu_532_p4);

assign select_ln119_5_fu_700_p3 = ((cmp122_i_fu_582_p2[0:0] == 1'b1) ? tmp_13_i_fu_464_p4 : tmp_22_i_fu_542_p4);

assign select_ln119_6_fu_708_p3 = ((cmp122_i_fu_582_p2[0:0] == 1'b1) ? tmp_14_i_fu_474_p4 : tmp_23_i_fu_552_p4);

assign select_ln119_7_fu_716_p3 = ((cmp122_i_fu_582_p2[0:0] == 1'b1) ? tmp_15_i_fu_484_p4 : tmp_24_i_fu_562_p4);

assign select_ln119_8_fu_724_p3 = ((cmp122_i_fu_582_p2[0:0] == 1'b1) ? trunc_ln105_1_fu_494_p1 : trunc_ln105_2_fu_572_p1);

assign select_ln119_fu_660_p3 = ((cmp122_i_fu_582_p2[0:0] == 1'b1) ? trunc_ln101_1_fu_420_p1 : trunc_ln101_2_fu_498_p1);

assign tmp_10_i_fu_434_p4 = {{linebuf_1_1_q0[69:60]}};

assign tmp_11_i_fu_444_p4 = {{linebuf_1_1_q0[59:50]}};

assign tmp_12_i_fu_454_p4 = {{linebuf_1_1_q0[49:40]}};

assign tmp_13_i_fu_464_p4 = {{linebuf_1_1_q0[39:30]}};

assign tmp_14_i_fu_474_p4 = {{linebuf_1_1_q0[29:20]}};

assign tmp_15_i_fu_484_p4 = {{linebuf_1_1_q0[19:10]}};

assign tmp_18_i_fu_502_p4 = {{linebuf_2_1_q0[79:70]}};

assign tmp_19_i_fu_512_p4 = {{linebuf_2_1_q0[69:60]}};

assign tmp_1_i_fu_346_p4 = {{linebuf_0_1_q0[79:70]}};

assign tmp_20_i_fu_522_p4 = {{linebuf_2_1_q0[59:50]}};

assign tmp_21_i_fu_532_p4 = {{linebuf_2_1_q0[49:40]}};

assign tmp_22_i_fu_542_p4 = {{linebuf_2_1_q0[39:30]}};

assign tmp_23_i_fu_552_p4 = {{linebuf_2_1_q0[29:20]}};

assign tmp_24_i_fu_562_p4 = {{linebuf_2_1_q0[19:10]}};

assign tmp_2_i_fu_356_p4 = {{linebuf_0_1_q0[69:60]}};

assign tmp_3_i_fu_366_p4 = {{linebuf_0_1_q0[59:50]}};

assign tmp_4_i_fu_376_p4 = {{linebuf_0_1_q0[49:40]}};

assign tmp_5_i_fu_386_p4 = {{linebuf_0_1_q0[39:30]}};

assign tmp_6_i_fu_396_p4 = {{linebuf_0_1_q0[29:20]}};

assign tmp_7_i_fu_406_p4 = {{linebuf_0_1_q0[19:10]}};

assign tmp_i_fu_424_p4 = {{linebuf_1_1_q0[79:70]}};

assign trunc_ln101_1_fu_420_p1 = linebuf_1_0_q0[9:0];

assign trunc_ln101_2_fu_498_p1 = linebuf_2_0_q0[9:0];

assign trunc_ln101_fu_342_p1 = linebuf_0_0_q0[9:0];

assign trunc_ln105_1_fu_494_p1 = linebuf_1_1_q0[9:0];

assign trunc_ln105_2_fu_572_p1 = linebuf_2_1_q0[9:0];

assign trunc_ln105_fu_416_p1 = linebuf_0_1_q0[9:0];

endmodule //conv2d_3x3_shift_register
