// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module conv2d_3x3_data_packet (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        output_r_dout,
        output_r_num_data_valid,
        output_r_fifo_cap,
        output_r_empty_n,
        output_r_read,
        data_out_TREADY,
        data_out_TDATA,
        data_out_TVALID,
        data_out_TKEEP,
        data_out_TSTRB,
        data_out_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 5'd1;
parameter    ap_ST_fsm_pp0_stage1 = 5'd2;
parameter    ap_ST_fsm_pp0_stage2 = 5'd4;
parameter    ap_ST_fsm_pp0_stage3 = 5'd8;
parameter    ap_ST_fsm_pp0_stage4 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [79:0] output_r_dout;
input  [2:0] output_r_num_data_valid;
input  [2:0] output_r_fifo_cap;
input   output_r_empty_n;
output   output_r_read;
input   data_out_TREADY;
output  [63:0] data_out_TDATA;
output   data_out_TVALID;
output  [7:0] data_out_TKEEP;
output  [7:0] data_out_TSTRB;
output  [0:0] data_out_TLAST;

reg ap_idle;
reg output_r_read;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln159_reg_409;
reg   [0:0] icmp_ln169_reg_413;
reg    ap_predicate_op31_write_state2;
wire    regslice_both_data_out_V_data_V_U_apdone_blk;
reg    ap_block_state2_pp0_stage1_iter0;
reg    ap_block_state2_io;
reg   [0:0] icmp_ln159_reg_409_pp0_iter1_reg;
reg   [0:0] icmp_ln169_4_reg_489;
reg    ap_predicate_op83_write_state7;
reg    ap_block_state7_pp0_stage1_iter1;
reg    ap_block_state7_io;
wire    ap_loop_exit_ready;
reg    ap_block_pp0_stage1_subdone;
reg    ap_condition_exit_pp0_iter0_stage1;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage4;
reg   [0:0] icmp_ln169_2_reg_451;
reg    ap_predicate_op65_write_state5;
reg   [0:0] icmp_ln169_3_reg_470;
reg    ap_predicate_op70_write_state5;
reg    ap_block_state5_pp0_stage4_iter0;
reg    ap_block_state5_io;
reg    ap_block_pp0_stage4_subdone;
reg    data_out_TDATA_blk_n;
wire    ap_block_pp0_stage1;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
reg   [0:0] icmp_ln169_1_reg_432;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
wire    ap_block_pp0_stage4;
wire    ap_block_pp0_stage0;
reg    output_r_blk_n;
reg   [31:0] output_addr_2_reg_116;
reg   [31:0] output_addr_4_reg_126;
reg   [31:0] output_addr_6_reg_137;
reg   [79:0] reg_168;
reg    ap_block_pp0_stage1_11001;
reg    ap_predicate_op38_write_state3;
reg    ap_predicate_op43_write_state3;
reg    ap_block_state3_pp0_stage2_iter0;
reg    ap_block_state3_io;
reg    ap_done_reg;
reg    ap_block_pp0_stage2_11001;
reg    ap_predicate_op50_write_state4;
reg    ap_predicate_op55_write_state4;
reg    ap_block_state4_pp0_stage3_iter0;
reg    ap_block_state4_io;
reg    ap_block_pp0_stage3_11001;
reg    ap_block_pp0_stage4_11001;
reg   [31:0] output_addr_11_reg_403;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_predicate_op80_write_state6;
reg    ap_predicate_op82_write_state6;
reg    ap_block_state6_pp0_stage0_iter1;
reg    ap_block_state6_io;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln159_fu_188_p2;
wire   [0:0] icmp_ln169_fu_194_p2;
wire   [31:0] output_addr_12_fu_200_p2;
wire   [63:0] output_data_fu_217_p1;
wire   [0:0] output_last_fu_222_p2;
wire   [0:0] icmp_ln169_1_fu_228_p2;
wire   [31:0] output_addr_13_fu_234_p2;
wire   [63:0] output_data_1_fu_254_p3;
wire   [0:0] output_last_1_fu_263_p2;
wire   [0:0] icmp_ln169_2_fu_270_p2;
wire   [31:0] output_addr_14_fu_276_p2;
wire   [63:0] output_data_2_fu_296_p3;
wire   [0:0] output_last_2_fu_305_p2;
wire   [0:0] icmp_ln169_3_fu_312_p2;
wire   [31:0] output_addr_15_fu_318_p2;
wire   [63:0] output_data_3_fu_338_p3;
wire   [0:0] output_last_3_fu_347_p2;
wire   [0:0] icmp_ln169_4_fu_354_p2;
wire   [0:0] output_last_4_fu_360_p2;
reg   [0:0] output_last_4_reg_493;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [31:0] ap_phi_reg_pp0_iter0_output_addr_2_reg_116;
reg   [31:0] ap_phi_reg_pp0_iter0_output_addr_4_reg_126;
reg   [31:0] ap_phi_reg_pp0_iter0_output_addr_6_reg_137;
reg   [31:0] ap_phi_reg_pp0_iter0_output_addr_8_reg_148;
reg   [31:0] ap_phi_mux_output_addr_10_phi_fu_161_p4;
wire   [31:0] output_addr_16_fu_366_p2;
wire   [31:0] ap_phi_reg_pp0_iter0_output_addr_10_reg_158;
reg   [17:0] i_fu_84;
wire   [17:0] i_5_fu_206_p2;
wire    ap_loop_init;
reg   [17:0] ap_sig_allocacmp_i_4;
reg   [31:0] output_addr_fu_88;
reg   [31:0] ap_sig_allocacmp_output_addr_11;
reg    ap_block_pp0_stage1_01001;
reg    ap_block_pp0_stage2_01001;
reg    ap_block_pp0_stage3_01001;
reg    ap_block_pp0_stage4_01001;
reg    ap_block_pp0_stage0_01001;
wire   [47:0] trunc_ln171_fu_250_p1;
wire   [15:0] tmp_fu_240_p4;
wire   [31:0] trunc_ln171_1_fu_292_p1;
wire   [31:0] tmp_18_fu_282_p4;
wire   [15:0] trunc_ln171_2_fu_334_p1;
wire   [47:0] tmp_20_fu_324_p4;
wire    ap_continue_int;
reg    ap_done_int;
reg   [4:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
reg   [63:0] data_out_TDATA_int_regslice;
reg    data_out_TVALID_int_regslice;
wire    data_out_TREADY_int_regslice;
wire    regslice_both_data_out_V_data_V_U_vld_out;
wire    regslice_both_data_out_V_keep_V_U_apdone_blk;
wire    regslice_both_data_out_V_keep_V_U_ack_in_dummy;
wire    regslice_both_data_out_V_keep_V_U_vld_out;
wire    regslice_both_data_out_V_strb_V_U_apdone_blk;
wire   [7:0] data_out_TSTRB_int_regslice;
wire    regslice_both_data_out_V_strb_V_U_ack_in_dummy;
wire    regslice_both_data_out_V_strb_V_U_vld_out;
wire    regslice_both_data_out_V_last_V_U_apdone_blk;
reg   [0:0] data_out_TLAST_int_regslice;
wire    regslice_both_data_out_V_last_V_U_ack_in_dummy;
wire    regslice_both_data_out_V_last_V_U_vld_out;
reg    ap_condition_400;
reg    ap_condition_405;
reg    ap_condition_406;
reg    ap_condition_408;
reg    ap_condition_346;
reg    ap_condition_675;
reg    ap_condition_679;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_fu_84 = 18'd0;
#0 output_addr_fu_88 = 32'd0;
end

conv2d_3x3_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

conv2d_3x3_regslice_both #(
    .DataWidth( 64 ))
regslice_both_data_out_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(data_out_TDATA_int_regslice),
    .vld_in(data_out_TVALID_int_regslice),
    .ack_in(data_out_TREADY_int_regslice),
    .data_out(data_out_TDATA),
    .vld_out(regslice_both_data_out_V_data_V_U_vld_out),
    .ack_out(data_out_TREADY),
    .apdone_blk(regslice_both_data_out_V_data_V_U_apdone_blk)
);

conv2d_3x3_regslice_both #(
    .DataWidth( 8 ))
regslice_both_data_out_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(8'd255),
    .vld_in(data_out_TVALID_int_regslice),
    .ack_in(regslice_both_data_out_V_keep_V_U_ack_in_dummy),
    .data_out(data_out_TKEEP),
    .vld_out(regslice_both_data_out_V_keep_V_U_vld_out),
    .ack_out(data_out_TREADY),
    .apdone_blk(regslice_both_data_out_V_keep_V_U_apdone_blk)
);

conv2d_3x3_regslice_both #(
    .DataWidth( 8 ))
regslice_both_data_out_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(data_out_TSTRB_int_regslice),
    .vld_in(data_out_TVALID_int_regslice),
    .ack_in(regslice_both_data_out_V_strb_V_U_ack_in_dummy),
    .data_out(data_out_TSTRB),
    .vld_out(regslice_both_data_out_V_strb_V_U_vld_out),
    .ack_out(data_out_TREADY),
    .apdone_blk(regslice_both_data_out_V_strb_V_U_apdone_blk)
);

conv2d_3x3_regslice_both #(
    .DataWidth( 1 ))
regslice_both_data_out_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(data_out_TLAST_int_regslice),
    .vld_in(data_out_TVALID_int_regslice),
    .ack_in(regslice_both_data_out_V_last_V_U_ack_in_dummy),
    .data_out(data_out_TLAST),
    .vld_out(regslice_both_data_out_V_last_V_U_vld_out),
    .ack_out(data_out_TREADY),
    .apdone_blk(regslice_both_data_out_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_400)) begin
        if ((icmp_ln169_fu_194_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_output_addr_2_reg_116 <= ap_sig_allocacmp_output_addr_11;
        end else if ((icmp_ln169_fu_194_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_output_addr_2_reg_116 <= output_addr_12_fu_200_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_405)) begin
        if ((icmp_ln169_1_fu_228_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_output_addr_4_reg_126 <= ap_phi_reg_pp0_iter0_output_addr_2_reg_116;
        end else if ((icmp_ln169_1_fu_228_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_output_addr_4_reg_126 <= output_addr_13_fu_234_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_406)) begin
        if ((icmp_ln169_2_fu_270_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_output_addr_6_reg_137 <= ap_phi_reg_pp0_iter0_output_addr_4_reg_126;
        end else if ((icmp_ln169_2_fu_270_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_output_addr_6_reg_137 <= output_addr_14_fu_276_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_408)) begin
        if ((icmp_ln169_3_fu_312_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_output_addr_8_reg_148 <= ap_phi_reg_pp0_iter0_output_addr_6_reg_137;
        end else if ((icmp_ln169_3_fu_312_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_output_addr_8_reg_148 <= output_addr_15_fu_318_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_346)) begin
        if ((icmp_ln159_fu_188_p2 == 1'd1)) begin
            i_fu_84 <= i_5_fu_206_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_84 <= 18'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if ((1'b1 == ap_condition_679)) begin
            output_addr_fu_88 <= 32'd0;
        end else if ((1'b1 == ap_condition_675)) begin
            output_addr_fu_88 <= ap_phi_mux_output_addr_10_phi_fu_161_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln159_reg_409 <= icmp_ln159_fu_188_p2;
        icmp_ln159_reg_409_pp0_iter1_reg <= icmp_ln159_reg_409;
        icmp_ln169_reg_413 <= icmp_ln169_fu_194_p2;
        output_addr_11_reg_403 <= ap_sig_allocacmp_output_addr_11;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        icmp_ln169_1_reg_432 <= icmp_ln169_1_fu_228_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        icmp_ln169_2_reg_451 <= icmp_ln169_2_fu_270_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        icmp_ln169_3_reg_470 <= icmp_ln169_3_fu_312_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        icmp_ln169_4_reg_489 <= icmp_ln169_4_fu_354_p2;
        output_last_4_reg_493 <= output_last_4_fu_360_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        output_addr_2_reg_116 <= ap_phi_reg_pp0_iter0_output_addr_2_reg_116;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        output_addr_4_reg_126 <= ap_phi_reg_pp0_iter0_output_addr_4_reg_126;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        output_addr_6_reg_137 <= ap_phi_reg_pp0_iter0_output_addr_6_reg_137;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_168 <= output_r_dout;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (icmp_ln159_reg_409 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln159_reg_409 == 1'd1)) begin
        if ((icmp_ln169_4_fu_354_p2 == 1'd0)) begin
            ap_phi_mux_output_addr_10_phi_fu_161_p4 = ap_phi_reg_pp0_iter0_output_addr_8_reg_148;
        end else if ((icmp_ln169_4_fu_354_p2 == 1'd1)) begin
            ap_phi_mux_output_addr_10_phi_fu_161_p4 = output_addr_16_fu_366_p2;
        end else begin
            ap_phi_mux_output_addr_10_phi_fu_161_p4 = ap_phi_reg_pp0_iter0_output_addr_10_reg_158;
        end
    end else begin
        ap_phi_mux_output_addr_10_phi_fu_161_p4 = ap_phi_reg_pp0_iter0_output_addr_10_reg_158;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_4 = 18'd0;
    end else begin
        ap_sig_allocacmp_i_4 = i_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_output_addr_11 = 32'd0;
    end else begin
        ap_sig_allocacmp_output_addr_11 = output_addr_fu_88;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (icmp_ln169_4_reg_489 == 1'd1) & (icmp_ln159_reg_409 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (icmp_ln159_reg_409 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln169_3_reg_470 == 1'd1)) | ((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_predicate_op70_write_state5 == 1'b1)) | ((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_predicate_op65_write_state5 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3) & (icmp_ln159_reg_409 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (icmp_ln169_1_reg_432 == 1'd1)) | ((1'b0 == ap_block_pp0_stage3) & (icmp_ln159_reg_409 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (icmp_ln169_2_reg_451 == 1'd1)) | ((1'b0 == ap_block_pp0_stage2) & (icmp_ln169_reg_413 == 1'd1) & 
    (icmp_ln159_reg_409 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage2) & (icmp_ln159_reg_409 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln169_1_reg_432 == 1'd1)) | ((1'b0 == ap_block_pp0_stage1) & (ap_predicate_op83_write_state7 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage1) & (ap_predicate_op31_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        data_out_TDATA_blk_n = data_out_TREADY_int_regslice;
    end else begin
        data_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_predicate_op82_write_state6 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_out_TDATA_int_regslice = {{reg_168[79:16]}};
    end else if (((1'b0 == ap_block_pp0_stage4_01001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_predicate_op70_write_state5 == 1'b1))) begin
        data_out_TDATA_int_regslice = output_data_3_fu_338_p3;
    end else if (((1'b0 == ap_block_pp0_stage3_01001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op55_write_state4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        data_out_TDATA_int_regslice = output_data_2_fu_296_p3;
    end else if (((1'b0 == ap_block_pp0_stage2_01001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op43_write_state3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        data_out_TDATA_int_regslice = output_data_1_fu_254_p3;
    end else if (((1'b0 == ap_block_pp0_stage1_01001) & (ap_predicate_op31_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        data_out_TDATA_int_regslice = output_data_fu_217_p1;
    end else begin
        data_out_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_predicate_op82_write_state6 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_out_TLAST_int_regslice = output_last_4_reg_493;
    end else if (((1'b0 == ap_block_pp0_stage4_01001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_predicate_op70_write_state5 == 1'b1))) begin
        data_out_TLAST_int_regslice = output_last_3_fu_347_p2;
    end else if (((1'b0 == ap_block_pp0_stage3_01001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op55_write_state4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        data_out_TLAST_int_regslice = output_last_2_fu_305_p2;
    end else if (((1'b0 == ap_block_pp0_stage2_01001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op43_write_state3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        data_out_TLAST_int_regslice = output_last_1_fu_263_p2;
    end else if (((1'b0 == ap_block_pp0_stage1_01001) & (ap_predicate_op31_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        data_out_TLAST_int_regslice = output_last_fu_222_p2;
    end else begin
        data_out_TLAST_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op82_write_state6 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_predicate_op70_write_state5 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op55_write_state4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op43_write_state3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op31_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        data_out_TVALID_int_regslice = 1'b1;
    end else begin
        data_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4) & (icmp_ln159_reg_409 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3) & (icmp_ln159_reg_409 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2) & (icmp_ln159_reg_409 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (icmp_ln159_reg_409 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        output_r_blk_n = output_r_empty_n;
    end else begin
        output_r_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (icmp_ln159_reg_409 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln159_reg_409 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln159_reg_409 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln159_reg_409 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        output_r_read = 1'b1;
    end else begin
        output_r_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((regslice_both_data_out_V_data_V_U_apdone_blk == 1'b1) & (icmp_ln159_reg_409 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter1))) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((regslice_both_data_out_V_data_V_U_apdone_blk == 1'b1) & (icmp_ln159_reg_409 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter1))) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((regslice_both_data_out_V_data_V_U_apdone_blk == 1'b1) & (icmp_ln159_reg_409 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage1_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0)) | ((regslice_both_data_out_V_data_V_U_apdone_blk == 1'b1) & (icmp_ln159_reg_409 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage1_iter1))) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0))) | ((regslice_both_data_out_V_data_V_U_apdone_blk == 1'b1) & (icmp_ln159_reg_409 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage1_iter1))) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0))) | ((regslice_both_data_out_V_data_V_U_apdone_blk == 1'b1) & (icmp_ln159_reg_409 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0)) | ((regslice_both_data_out_V_data_V_U_apdone_blk == 1'b1) & (icmp_ln159_reg_409 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)));
end

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage2_iter0))) | ((regslice_both_data_out_V_data_V_U_apdone_blk == 1'b1) & (icmp_ln159_reg_409 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage2_iter0))) | ((regslice_both_data_out_V_data_V_U_apdone_blk == 1'b1) & (icmp_ln159_reg_409 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_01001 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0)) | ((regslice_both_data_out_V_data_V_U_apdone_blk == 1'b1) & (icmp_ln159_reg_409 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)));
end

always @ (*) begin
    ap_block_pp0_stage3_11001 = (((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage3_iter0))) | ((regslice_both_data_out_V_data_V_U_apdone_blk == 1'b1) & (icmp_ln159_reg_409 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = (((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage3_iter0))) | ((regslice_both_data_out_V_data_V_U_apdone_blk == 1'b1) & (icmp_ln159_reg_409 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_01001 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0)) | ((regslice_both_data_out_V_data_V_U_apdone_blk == 1'b1) & (icmp_ln159_reg_409 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)));
end

always @ (*) begin
    ap_block_pp0_stage4_11001 = (((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage4_iter0))) | ((regslice_both_data_out_V_data_V_U_apdone_blk == 1'b1) & (icmp_ln159_reg_409 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone = (((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage4_iter0))) | ((regslice_both_data_out_V_data_V_U_apdone_blk == 1'b1) & (icmp_ln159_reg_409 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_io = ((data_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op31_write_state2 == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((regslice_both_data_out_V_data_V_U_apdone_blk == 1'b1) | ((data_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op31_write_state2 == 1'b1)) | ((icmp_ln159_reg_409 == 1'd1) & (output_r_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state3_io = (((data_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op43_write_state3 == 1'b1)) | ((data_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op38_write_state3 == 1'b1)));
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0 = (((data_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op43_write_state3 == 1'b1)) | ((data_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op38_write_state3 == 1'b1)) | ((icmp_ln159_reg_409 == 1'd1) & (output_r_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state4_io = (((data_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state4 == 1'b1)) | ((data_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op50_write_state4 == 1'b1)));
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0 = (((data_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state4 == 1'b1)) | ((data_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op50_write_state4 == 1'b1)) | ((icmp_ln159_reg_409 == 1'd1) & (output_r_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state5_io = (((data_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op70_write_state5 == 1'b1)) | ((data_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op65_write_state5 == 1'b1)));
end

always @ (*) begin
    ap_block_state5_pp0_stage4_iter0 = (((data_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op70_write_state5 == 1'b1)) | ((data_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op65_write_state5 == 1'b1)) | ((icmp_ln159_reg_409 == 1'd1) & (output_r_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state6_io = (((data_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op82_write_state6 == 1'b1)) | ((data_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op80_write_state6 == 1'b1)));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter1 = (((data_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op82_write_state6 == 1'b1)) | ((data_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op80_write_state6 == 1'b1)));
end

always @ (*) begin
    ap_block_state7_io = ((ap_predicate_op83_write_state7 == 1'b1) & (data_out_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state7_pp0_stage1_iter1 = ((ap_predicate_op83_write_state7 == 1'b1) & (data_out_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_condition_346 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_400 = ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln159_fu_188_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_405 = ((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln159_reg_409 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_condition_406 = ((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln159_reg_409 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2));
end

always @ (*) begin
    ap_condition_408 = ((1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln159_reg_409 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3));
end

always @ (*) begin
    ap_condition_675 = ((1'b0 == ap_block_pp0_stage4_11001) & (icmp_ln159_reg_409 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage4));
end

always @ (*) begin
    ap_condition_679 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_phi_reg_pp0_iter0_output_addr_10_reg_158 = 'bx;

always @ (*) begin
    ap_predicate_op31_write_state2 = ((icmp_ln169_reg_413 == 1'd1) & (icmp_ln159_reg_409 == 1'd1));
end

always @ (*) begin
    ap_predicate_op38_write_state3 = ((icmp_ln169_reg_413 == 1'd1) & (icmp_ln159_reg_409 == 1'd1));
end

always @ (*) begin
    ap_predicate_op43_write_state3 = ((icmp_ln159_reg_409 == 1'd1) & (icmp_ln169_1_reg_432 == 1'd1));
end

always @ (*) begin
    ap_predicate_op50_write_state4 = ((icmp_ln159_reg_409 == 1'd1) & (icmp_ln169_1_reg_432 == 1'd1));
end

always @ (*) begin
    ap_predicate_op55_write_state4 = ((icmp_ln159_reg_409 == 1'd1) & (icmp_ln169_2_reg_451 == 1'd1));
end

always @ (*) begin
    ap_predicate_op65_write_state5 = ((icmp_ln159_reg_409 == 1'd1) & (icmp_ln169_2_reg_451 == 1'd1));
end

always @ (*) begin
    ap_predicate_op70_write_state5 = ((icmp_ln159_reg_409 == 1'd1) & (icmp_ln169_3_reg_470 == 1'd1));
end

always @ (*) begin
    ap_predicate_op80_write_state6 = ((icmp_ln159_reg_409 == 1'd1) & (icmp_ln169_3_reg_470 == 1'd1));
end

always @ (*) begin
    ap_predicate_op82_write_state6 = ((icmp_ln169_4_reg_489 == 1'd1) & (icmp_ln159_reg_409 == 1'd1));
end

always @ (*) begin
    ap_predicate_op83_write_state7 = ((icmp_ln169_4_reg_489 == 1'd1) & (icmp_ln159_reg_409_pp0_iter1_reg == 1'd1));
end

assign data_out_TSTRB_int_regslice = 'bx;

assign data_out_TVALID = regslice_both_data_out_V_data_V_U_vld_out;

assign i_5_fu_206_p2 = (ap_sig_allocacmp_i_4 + 18'd4);

assign icmp_ln159_fu_188_p2 = ((ap_sig_allocacmp_i_4 < 18'd259200) ? 1'b1 : 1'b0);

assign icmp_ln169_1_fu_228_p2 = (($signed(ap_phi_reg_pp0_iter0_output_addr_2_reg_116) < $signed(32'd324000)) ? 1'b1 : 1'b0);

assign icmp_ln169_2_fu_270_p2 = (($signed(ap_phi_reg_pp0_iter0_output_addr_4_reg_126) < $signed(32'd324000)) ? 1'b1 : 1'b0);

assign icmp_ln169_3_fu_312_p2 = (($signed(ap_phi_reg_pp0_iter0_output_addr_6_reg_137) < $signed(32'd324000)) ? 1'b1 : 1'b0);

assign icmp_ln169_4_fu_354_p2 = (($signed(ap_phi_reg_pp0_iter0_output_addr_8_reg_148) < $signed(32'd324000)) ? 1'b1 : 1'b0);

assign icmp_ln169_fu_194_p2 = (($signed(ap_sig_allocacmp_output_addr_11) < $signed(32'd324000)) ? 1'b1 : 1'b0);

assign output_addr_12_fu_200_p2 = (ap_sig_allocacmp_output_addr_11 + 32'd1);

assign output_addr_13_fu_234_p2 = (ap_phi_reg_pp0_iter0_output_addr_2_reg_116 + 32'd1);

assign output_addr_14_fu_276_p2 = (ap_phi_reg_pp0_iter0_output_addr_4_reg_126 + 32'd1);

assign output_addr_15_fu_318_p2 = (ap_phi_reg_pp0_iter0_output_addr_6_reg_137 + 32'd1);

assign output_addr_16_fu_366_p2 = (ap_phi_reg_pp0_iter0_output_addr_8_reg_148 + 32'd1);

assign output_data_1_fu_254_p3 = {{trunc_ln171_fu_250_p1}, {tmp_fu_240_p4}};

assign output_data_2_fu_296_p3 = {{trunc_ln171_1_fu_292_p1}, {tmp_18_fu_282_p4}};

assign output_data_3_fu_338_p3 = {{trunc_ln171_2_fu_334_p1}, {tmp_20_fu_324_p4}};

assign output_data_fu_217_p1 = output_r_dout[63:0];

assign output_last_1_fu_263_p2 = ((output_addr_2_reg_116 == 32'd323999) ? 1'b1 : 1'b0);

assign output_last_2_fu_305_p2 = ((output_addr_4_reg_126 == 32'd323999) ? 1'b1 : 1'b0);

assign output_last_3_fu_347_p2 = ((output_addr_6_reg_137 == 32'd323999) ? 1'b1 : 1'b0);

assign output_last_4_fu_360_p2 = ((ap_phi_reg_pp0_iter0_output_addr_8_reg_148 == 32'd323999) ? 1'b1 : 1'b0);

assign output_last_fu_222_p2 = ((output_addr_11_reg_403 == 32'd323999) ? 1'b1 : 1'b0);

assign tmp_18_fu_282_p4 = {{reg_168[79:48]}};

assign tmp_20_fu_324_p4 = {{reg_168[79:32]}};

assign tmp_fu_240_p4 = {{reg_168[79:64]}};

assign trunc_ln171_1_fu_292_p1 = output_r_dout[31:0];

assign trunc_ln171_2_fu_334_p1 = output_r_dout[15:0];

assign trunc_ln171_fu_250_p1 = output_r_dout[47:0];

endmodule //conv2d_3x3_data_packet
