domain_path: /home/leon/Desktop/Project/ZUBOARD_1CG/baremetal_platform/zynqmp_fsbl/zynqmp_fsbl_bsp
app_src_dir: /media/leon/Extend/Vitis/2023.2/data/embeddedsw/lib/sw_apps/zynqmp_fsbl
template: zynqmp_fsbl
