-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d_3x3_data_unpacket is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    data_in_TVALID : IN STD_LOGIC;
    input_r_din : OUT STD_LOGIC_VECTOR (79 downto 0);
    input_r_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    input_r_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    input_r_full_n : IN STD_LOGIC;
    input_r_write : OUT STD_LOGIC;
    data_in_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    data_in_TREADY : OUT STD_LOGIC;
    data_in_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    data_in_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    data_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of conv2d_3x3_data_unpacket is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv19_0 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    constant ap_const_lv19_4F1A0 : STD_LOGIC_VECTOR (18 downto 0) := "1001111000110100000";
    constant ap_const_lv32_3F480 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000111111010010000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv19_5 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln134_fu_165_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln144_3_reg_372 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state5_pp0_stage4_iter0 : BOOLEAN;
    signal data_in_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal input_r_blk_n : STD_LOGIC;
    signal icmp_ln144_reg_345 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln144_1_reg_354 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln144_2_reg_363 : STD_LOGIC_VECTOR (0 downto 0);
    signal output_cnt_2_reg_103 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_cnt_4_reg_113 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_cnt_6_reg_124 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_2_reg_325 : STD_LOGIC_VECTOR (18 downto 0);
    signal output_cnt_9_reg_330 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln134_reg_336 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_0_reg_340 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln144_fu_171_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_reg_349 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal icmp_ln144_1_fu_205_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_reg_358 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal icmp_ln144_2_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_reg_367 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state4_pp0_stage3_iter0 : BOOLEAN;
    signal icmp_ln144_3_fu_275_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_output_cnt_2_phi_fu_106_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_cnt_10_fu_189_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_output_cnt_2_reg_103 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_output_cnt_4_phi_fu_116_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_cnt_11_fu_223_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_output_cnt_4_reg_113 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_output_cnt_6_phi_fu_127_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_cnt_12_fu_258_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_output_cnt_6_reg_124 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_output_cnt_8_phi_fu_138_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_cnt_13_fu_289_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_output_cnt_8_reg_135 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_fu_76 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    signal i_3_fu_296_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_2 : STD_LOGIC_VECTOR (18 downto 0);
    signal output_cnt_fu_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_output_cnt_9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_181_p3 : STD_LOGIC_VECTOR (79 downto 0);
    signal tmp_s_fu_215_p3 : STD_LOGIC_VECTOR (79 downto 0);
    signal tmp_56_fu_250_p3 : STD_LOGIC_VECTOR (79 downto 0);
    signal tmp_57_fu_281_p3 : STD_LOGIC_VECTOR (79 downto 0);
    signal trunc_ln143_fu_177_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln143_1_fu_211_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln143_2_fu_246_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal regslice_both_data_in_V_data_V_U_apdone_blk : STD_LOGIC;
    signal data_in_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal data_in_TVALID_int_regslice : STD_LOGIC;
    signal data_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_data_in_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_data_in_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal data_in_TKEEP_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_data_in_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_data_in_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_data_in_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal data_in_TSTRB_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_data_in_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_data_in_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_data_in_V_last_V_U_apdone_blk : STD_LOGIC;
    signal data_in_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_data_in_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_data_in_V_last_V_U_ack_in : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component conv2d_3x3_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component conv2d_3x3_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component conv2d_3x3_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);

    regslice_both_data_in_V_data_V_U : component conv2d_3x3_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => data_in_TDATA,
        vld_in => data_in_TVALID,
        ack_in => regslice_both_data_in_V_data_V_U_ack_in,
        data_out => data_in_TDATA_int_regslice,
        vld_out => data_in_TVALID_int_regslice,
        ack_out => data_in_TREADY_int_regslice,
        apdone_blk => regslice_both_data_in_V_data_V_U_apdone_blk);

    regslice_both_data_in_V_keep_V_U : component conv2d_3x3_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => data_in_TKEEP,
        vld_in => data_in_TVALID,
        ack_in => regslice_both_data_in_V_keep_V_U_ack_in,
        data_out => data_in_TKEEP_int_regslice,
        vld_out => regslice_both_data_in_V_keep_V_U_vld_out,
        ack_out => data_in_TREADY_int_regslice,
        apdone_blk => regslice_both_data_in_V_keep_V_U_apdone_blk);

    regslice_both_data_in_V_strb_V_U : component conv2d_3x3_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => data_in_TSTRB,
        vld_in => data_in_TVALID,
        ack_in => regslice_both_data_in_V_strb_V_U_ack_in,
        data_out => data_in_TSTRB_int_regslice,
        vld_out => regslice_both_data_in_V_strb_V_U_vld_out,
        ack_out => data_in_TREADY_int_regslice,
        apdone_blk => regslice_both_data_in_V_strb_V_U_apdone_blk);

    regslice_both_data_in_V_last_V_U : component conv2d_3x3_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => data_in_TLAST,
        vld_in => data_in_TVALID,
        ack_in => regslice_both_data_in_V_last_V_U_ack_in,
        data_out => data_in_TLAST_int_regslice,
        vld_out => regslice_both_data_in_V_last_V_U_vld_out,
        ack_out => data_in_TREADY_int_regslice,
        apdone_blk => regslice_both_data_in_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
                i_fu_76 <= ap_const_lv19_0;
            elsif (((ap_const_boolean_0 = ap_block_state5_pp0_stage4_iter0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                i_fu_76 <= i_3_fu_296_p2;
            end if; 
        end if;
    end process;

    output_cnt_2_reg_103_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state2_pp0_stage1_iter0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                if ((icmp_ln144_reg_345 = ap_const_lv1_1)) then 
                    output_cnt_2_reg_103 <= output_cnt_10_fu_189_p2;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    output_cnt_2_reg_103 <= ap_phi_reg_pp0_iter0_output_cnt_2_reg_103;
                end if;
            end if; 
        end if;
    end process;

    output_cnt_4_reg_113_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state3_pp0_stage2_iter0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                if ((icmp_ln144_1_reg_354 = ap_const_lv1_0)) then 
                    output_cnt_4_reg_113 <= output_cnt_2_reg_103;
                elsif ((icmp_ln144_1_reg_354 = ap_const_lv1_1)) then 
                    output_cnt_4_reg_113 <= output_cnt_11_fu_223_p2;
                elsif (not((icmp_ln134_reg_336 = ap_const_lv1_0))) then 
                    output_cnt_4_reg_113 <= ap_phi_reg_pp0_iter0_output_cnt_4_reg_113;
                end if;
            end if; 
        end if;
    end process;

    output_cnt_6_reg_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state4_pp0_stage3_iter0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                if ((icmp_ln144_2_reg_363 = ap_const_lv1_0)) then 
                    output_cnt_6_reg_124 <= output_cnt_4_reg_113;
                elsif ((icmp_ln144_2_reg_363 = ap_const_lv1_1)) then 
                    output_cnt_6_reg_124 <= output_cnt_12_fu_258_p2;
                elsif (not((icmp_ln134_reg_336 = ap_const_lv1_0))) then 
                    output_cnt_6_reg_124 <= ap_phi_reg_pp0_iter0_output_cnt_6_reg_124;
                end if;
            end if; 
        end if;
    end process;

    output_cnt_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
                output_cnt_fu_80 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_state5_pp0_stage4_iter0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                output_cnt_fu_80 <= ap_phi_mux_output_cnt_8_phi_fu_138_p4;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (icmp_ln134_fu_165_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln144_fu_171_p2 = ap_const_lv1_0))) then
                ap_phi_reg_pp0_iter0_output_cnt_2_reg_103 <= ap_sig_allocacmp_output_cnt_9;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                i_2_reg_325 <= ap_sig_allocacmp_i_2;
                icmp_ln134_reg_336 <= icmp_ln134_fu_165_p2;
                icmp_ln144_reg_345 <= icmp_ln144_fu_171_p2;
                output_cnt_9_reg_330 <= ap_sig_allocacmp_output_cnt_9;
                p_0_reg_340 <= data_in_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state2_pp0_stage1_iter0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                icmp_ln144_1_reg_354 <= icmp_ln144_1_fu_205_p2;
                tmp_12_reg_349 <= data_in_TDATA_int_regslice(63 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state3_pp0_stage2_iter0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                icmp_ln144_2_reg_363 <= icmp_ln144_2_fu_240_p2;
                tmp_14_reg_358 <= data_in_TDATA_int_regslice(63 downto 32);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state4_pp0_stage3_iter0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                icmp_ln144_3_reg_372 <= icmp_ln144_3_fu_275_p2;
                tmp_16_reg_367 <= data_in_TDATA_int_regslice(63 downto 48);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, icmp_ln134_fu_165_p2, ap_block_state1_pp0_stage0_iter0, ap_CS_fsm_state5, ap_block_state5_pp0_stage4_iter0, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_block_state2_pp0_stage1_iter0, ap_block_state3_pp0_stage2_iter0, ap_block_state4_pp0_stage3_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (icmp_ln134_fu_165_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_pp0_stage1_iter0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3_pp0_stage2_iter0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_boolean_0 = ap_block_state4_pp0_stage3_iter0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_boolean_0 = ap_block_state5_pp0_stage4_iter0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_pp0_stage1_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3_pp0_stage2_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(ap_block_state4_pp0_stage3_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(ap_block_state5_pp0_stage4_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(icmp_ln134_fu_165_p2, ap_done_reg, ap_start_int, data_in_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((data_in_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln134_fu_165_p2 = ap_const_lv1_1)));
    end process;


    ap_block_state2_pp0_stage1_iter0_assign_proc : process(input_r_full_n, icmp_ln144_reg_345, data_in_TVALID_int_regslice)
    begin
                ap_block_state2_pp0_stage1_iter0 <= ((data_in_TVALID_int_regslice = ap_const_logic_0) or ((icmp_ln144_reg_345 = ap_const_lv1_1) and (input_r_full_n = ap_const_logic_0)));
    end process;


    ap_block_state3_pp0_stage2_iter0_assign_proc : process(input_r_full_n, icmp_ln144_1_reg_354, data_in_TVALID_int_regslice)
    begin
                ap_block_state3_pp0_stage2_iter0 <= ((data_in_TVALID_int_regslice = ap_const_logic_0) or ((icmp_ln144_1_reg_354 = ap_const_lv1_1) and (input_r_full_n = ap_const_logic_0)));
    end process;


    ap_block_state4_pp0_stage3_iter0_assign_proc : process(input_r_full_n, icmp_ln144_2_reg_363, data_in_TVALID_int_regslice)
    begin
                ap_block_state4_pp0_stage3_iter0 <= ((data_in_TVALID_int_regslice = ap_const_logic_0) or ((input_r_full_n = ap_const_logic_0) and (icmp_ln144_2_reg_363 = ap_const_lv1_1)));
    end process;


    ap_block_state5_pp0_stage4_iter0_assign_proc : process(input_r_full_n, icmp_ln144_3_reg_372, data_in_TVALID_int_regslice)
    begin
                ap_block_state5_pp0_stage4_iter0 <= ((data_in_TVALID_int_regslice = ap_const_logic_0) or ((icmp_ln144_3_reg_372 = ap_const_lv1_1) and (input_r_full_n = ap_const_logic_0)));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, icmp_ln134_fu_165_p2, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (icmp_ln134_fu_165_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_output_cnt_2_phi_fu_106_p4_assign_proc : process(icmp_ln144_reg_345, output_cnt_10_fu_189_p2, ap_phi_reg_pp0_iter0_output_cnt_2_reg_103)
    begin
        if ((icmp_ln144_reg_345 = ap_const_lv1_1)) then 
            ap_phi_mux_output_cnt_2_phi_fu_106_p4 <= output_cnt_10_fu_189_p2;
        else 
            ap_phi_mux_output_cnt_2_phi_fu_106_p4 <= ap_phi_reg_pp0_iter0_output_cnt_2_reg_103;
        end if; 
    end process;


    ap_phi_mux_output_cnt_4_phi_fu_116_p4_assign_proc : process(icmp_ln144_1_reg_354, output_cnt_2_reg_103, output_cnt_11_fu_223_p2, ap_phi_reg_pp0_iter0_output_cnt_4_reg_113)
    begin
        if ((icmp_ln144_1_reg_354 = ap_const_lv1_0)) then 
            ap_phi_mux_output_cnt_4_phi_fu_116_p4 <= output_cnt_2_reg_103;
        elsif ((icmp_ln144_1_reg_354 = ap_const_lv1_1)) then 
            ap_phi_mux_output_cnt_4_phi_fu_116_p4 <= output_cnt_11_fu_223_p2;
        else 
            ap_phi_mux_output_cnt_4_phi_fu_116_p4 <= ap_phi_reg_pp0_iter0_output_cnt_4_reg_113;
        end if; 
    end process;


    ap_phi_mux_output_cnt_6_phi_fu_127_p4_assign_proc : process(icmp_ln144_2_reg_363, output_cnt_4_reg_113, output_cnt_12_fu_258_p2, ap_phi_reg_pp0_iter0_output_cnt_6_reg_124)
    begin
        if ((icmp_ln144_2_reg_363 = ap_const_lv1_0)) then 
            ap_phi_mux_output_cnt_6_phi_fu_127_p4 <= output_cnt_4_reg_113;
        elsif ((icmp_ln144_2_reg_363 = ap_const_lv1_1)) then 
            ap_phi_mux_output_cnt_6_phi_fu_127_p4 <= output_cnt_12_fu_258_p2;
        else 
            ap_phi_mux_output_cnt_6_phi_fu_127_p4 <= ap_phi_reg_pp0_iter0_output_cnt_6_reg_124;
        end if; 
    end process;


    ap_phi_mux_output_cnt_8_phi_fu_138_p4_assign_proc : process(icmp_ln144_3_reg_372, output_cnt_6_reg_124, output_cnt_13_fu_289_p2, ap_phi_reg_pp0_iter0_output_cnt_8_reg_135)
    begin
        if ((icmp_ln144_3_reg_372 = ap_const_lv1_0)) then 
            ap_phi_mux_output_cnt_8_phi_fu_138_p4 <= output_cnt_6_reg_124;
        elsif ((icmp_ln144_3_reg_372 = ap_const_lv1_1)) then 
            ap_phi_mux_output_cnt_8_phi_fu_138_p4 <= output_cnt_13_fu_289_p2;
        else 
            ap_phi_mux_output_cnt_8_phi_fu_138_p4 <= ap_phi_reg_pp0_iter0_output_cnt_8_reg_135;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_output_cnt_4_reg_113 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_output_cnt_6_reg_124 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_output_cnt_8_reg_135 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_ready_int_assign_proc : process(ap_CS_fsm_state5, ap_block_state5_pp0_stage4_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state5_pp0_stage4_iter0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_2_assign_proc : process(ap_CS_fsm_state1, i_fu_76, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_2 <= ap_const_lv19_0;
        else 
            ap_sig_allocacmp_i_2 <= i_fu_76;
        end if; 
    end process;


    ap_sig_allocacmp_output_cnt_9_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, output_cnt_fu_80)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_output_cnt_9 <= ap_const_lv32_0;
        else 
            ap_sig_allocacmp_output_cnt_9 <= output_cnt_fu_80;
        end if; 
    end process;


    data_in_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, icmp_ln134_fu_165_p2, ap_done_reg, ap_CS_fsm_state5, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_start_int, data_in_TVALID_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state5) or (not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0))) and (icmp_ln134_fu_165_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            data_in_TDATA_blk_n <= data_in_TVALID_int_regslice;
        else 
            data_in_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    data_in_TREADY <= regslice_both_data_in_V_data_V_U_ack_in;

    data_in_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state1, icmp_ln134_fu_165_p2, ap_block_state1_pp0_stage0_iter0, ap_CS_fsm_state5, ap_block_state5_pp0_stage4_iter0, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_block_state2_pp0_stage1_iter0, ap_block_state3_pp0_stage2_iter0, ap_block_state4_pp0_stage3_iter0)
    begin
        if ((((ap_const_boolean_0 = ap_block_state5_pp0_stage4_iter0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (icmp_ln134_fu_165_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_boolean_0 = ap_block_state4_pp0_stage3_iter0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((ap_const_boolean_0 = ap_block_state3_pp0_stage2_iter0) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((ap_const_boolean_0 = ap_block_state2_pp0_stage1_iter0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            data_in_TREADY_int_regslice <= ap_const_logic_1;
        else 
            data_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    i_3_fu_296_p2 <= std_logic_vector(unsigned(i_2_reg_325) + unsigned(ap_const_lv19_5));
    icmp_ln134_fu_165_p2 <= "1" when (unsigned(ap_sig_allocacmp_i_2) < unsigned(ap_const_lv19_4F1A0)) else "0";
    icmp_ln144_1_fu_205_p2 <= "1" when (signed(ap_phi_mux_output_cnt_2_phi_fu_106_p4) < signed(ap_const_lv32_3F480)) else "0";
    icmp_ln144_2_fu_240_p2 <= "1" when (signed(ap_phi_mux_output_cnt_4_phi_fu_116_p4) < signed(ap_const_lv32_3F480)) else "0";
    icmp_ln144_3_fu_275_p2 <= "1" when (signed(ap_phi_mux_output_cnt_6_phi_fu_127_p4) < signed(ap_const_lv32_3F480)) else "0";
    icmp_ln144_fu_171_p2 <= "1" when (signed(ap_sig_allocacmp_output_cnt_9) < signed(ap_const_lv32_3F480)) else "0";

    input_r_blk_n_assign_proc : process(ap_CS_fsm_state5, input_r_full_n, icmp_ln144_3_reg_372, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, icmp_ln144_reg_345, icmp_ln144_1_reg_354, icmp_ln144_2_reg_363)
    begin
        if ((((icmp_ln144_reg_345 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln144_2_reg_363 = ap_const_lv1_1)) or ((icmp_ln144_3_reg_372 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((icmp_ln144_1_reg_354 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            input_r_blk_n <= input_r_full_n;
        else 
            input_r_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    input_r_din_assign_proc : process(ap_CS_fsm_state5, icmp_ln144_3_reg_372, ap_block_state5_pp0_stage4_iter0, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, icmp_ln144_reg_345, icmp_ln144_1_reg_354, icmp_ln144_2_reg_363, ap_block_state2_pp0_stage1_iter0, ap_block_state3_pp0_stage2_iter0, ap_block_state4_pp0_stage3_iter0, tmp_fu_181_p3, tmp_s_fu_215_p3, tmp_56_fu_250_p3, tmp_57_fu_281_p3)
    begin
        if (((icmp_ln144_3_reg_372 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state5_pp0_stage4_iter0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            input_r_din <= tmp_57_fu_281_p3;
        elsif (((ap_const_boolean_0 = ap_block_state4_pp0_stage3_iter0) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln144_2_reg_363 = ap_const_lv1_1))) then 
            input_r_din <= tmp_56_fu_250_p3;
        elsif (((icmp_ln144_1_reg_354 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state3_pp0_stage2_iter0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            input_r_din <= tmp_s_fu_215_p3;
        elsif (((icmp_ln144_reg_345 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state2_pp0_stage1_iter0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            input_r_din <= tmp_fu_181_p3;
        else 
            input_r_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    input_r_write_assign_proc : process(ap_CS_fsm_state5, icmp_ln144_3_reg_372, ap_block_state5_pp0_stage4_iter0, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, icmp_ln144_reg_345, icmp_ln144_1_reg_354, icmp_ln144_2_reg_363, ap_block_state2_pp0_stage1_iter0, ap_block_state3_pp0_stage2_iter0, ap_block_state4_pp0_stage3_iter0)
    begin
        if ((((icmp_ln144_reg_345 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state2_pp0_stage1_iter0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((icmp_ln144_3_reg_372 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state5_pp0_stage4_iter0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_const_boolean_0 = ap_block_state4_pp0_stage3_iter0) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln144_2_reg_363 = ap_const_lv1_1)) or ((icmp_ln144_1_reg_354 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state3_pp0_stage2_iter0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            input_r_write <= ap_const_logic_1;
        else 
            input_r_write <= ap_const_logic_0;
        end if; 
    end process;

    output_cnt_10_fu_189_p2 <= std_logic_vector(unsigned(output_cnt_9_reg_330) + unsigned(ap_const_lv32_1));
    output_cnt_11_fu_223_p2 <= std_logic_vector(unsigned(output_cnt_2_reg_103) + unsigned(ap_const_lv32_1));
    output_cnt_12_fu_258_p2 <= std_logic_vector(unsigned(output_cnt_4_reg_113) + unsigned(ap_const_lv32_1));
    output_cnt_13_fu_289_p2 <= std_logic_vector(unsigned(output_cnt_6_reg_124) + unsigned(ap_const_lv32_1));
    tmp_56_fu_250_p3 <= (trunc_ln143_2_fu_246_p1 & tmp_14_reg_358);
    tmp_57_fu_281_p3 <= (data_in_TDATA_int_regslice & tmp_16_reg_367);
    tmp_fu_181_p3 <= (trunc_ln143_fu_177_p1 & p_0_reg_340);
    tmp_s_fu_215_p3 <= (trunc_ln143_1_fu_211_p1 & tmp_12_reg_349);
    trunc_ln143_1_fu_211_p1 <= data_in_TDATA_int_regslice(32 - 1 downto 0);
    trunc_ln143_2_fu_246_p1 <= data_in_TDATA_int_regslice(48 - 1 downto 0);
    trunc_ln143_fu_177_p1 <= data_in_TDATA_int_regslice(16 - 1 downto 0);
end behav;
