domain_path: /home/leon/Desktop/Project/ZUBOARD_1CG/baremetal_platform/export/baremetal_platform/sw/standalone_psu_cortexa53_0
app_src_dir: /media/leon/Extend/Vitis/2023.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
