-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d_3x3_data_packet is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    output_r_dout : IN STD_LOGIC_VECTOR (79 downto 0);
    output_r_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    output_r_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    output_r_empty_n : IN STD_LOGIC;
    output_r_read : OUT STD_LOGIC;
    data_out_TREADY : IN STD_LOGIC;
    data_out_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    data_out_TVALID : OUT STD_LOGIC;
    data_out_TKEEP : OUT STD_LOGIC_VECTOR (7 downto 0);
    data_out_TSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    data_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of conv2d_3x3_data_packet is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv18_3F480 : STD_LOGIC_VECTOR (17 downto 0) := "111111010010000000";
    constant ap_const_lv32_4F1A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000001001111000110100000";
    constant ap_const_lv18_4 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000100";
    constant ap_const_lv32_4F19F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000001001111000110011111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal icmp_ln159_reg_409 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln169_reg_413 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op31_write_state2 : BOOLEAN;
    signal regslice_both_data_out_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal icmp_ln159_reg_409_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln169_4_reg_489 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op83_write_state7 : BOOLEAN;
    signal ap_block_state7_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state7_io : BOOLEAN;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal icmp_ln169_2_reg_451 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op65_write_state5 : BOOLEAN;
    signal icmp_ln169_3_reg_470 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op70_write_state5 : BOOLEAN;
    signal ap_block_state5_pp0_stage4_iter0 : BOOLEAN;
    signal ap_block_state5_io : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal data_out_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal icmp_ln169_1_reg_432 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal output_r_blk_n : STD_LOGIC;
    signal output_addr_2_reg_116 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_addr_4_reg_126 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_addr_6_reg_137 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_168 : STD_LOGIC_VECTOR (79 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_predicate_op38_write_state3 : BOOLEAN;
    signal ap_predicate_op43_write_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_predicate_op50_write_state4 : BOOLEAN;
    signal ap_predicate_op55_write_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage3_iter0 : BOOLEAN;
    signal ap_block_state4_io : BOOLEAN;
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal output_addr_11_reg_403 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_predicate_op80_write_state6 : BOOLEAN;
    signal ap_predicate_op82_write_state6 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state6_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln159_fu_188_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln169_fu_194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal output_addr_12_fu_200_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_data_fu_217_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal output_last_fu_222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln169_1_fu_228_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal output_addr_13_fu_234_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_data_1_fu_254_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal output_last_1_fu_263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln169_2_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal output_addr_14_fu_276_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_data_2_fu_296_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal output_last_2_fu_305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln169_3_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal output_addr_15_fu_318_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_data_3_fu_338_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal output_last_3_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln169_4_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal output_last_4_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal output_last_4_reg_493 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_phi_reg_pp0_iter0_output_addr_2_reg_116 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_output_addr_4_reg_126 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_output_addr_6_reg_137 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_output_addr_8_reg_148 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_output_addr_10_phi_fu_161_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_addr_16_fu_366_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_output_addr_10_reg_158 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_fu_84 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal i_5_fu_206_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_4 : STD_LOGIC_VECTOR (17 downto 0);
    signal output_addr_fu_88 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_output_addr_11 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal ap_block_pp0_stage2_01001 : BOOLEAN;
    signal ap_block_pp0_stage3_01001 : BOOLEAN;
    signal ap_block_pp0_stage4_01001 : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln171_fu_250_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_fu_240_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln171_1_fu_292_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_18_fu_282_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln171_2_fu_334_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_20_fu_324_p4 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal data_out_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal data_out_TVALID_int_regslice : STD_LOGIC;
    signal data_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_data_out_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_data_out_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_data_out_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_data_out_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_data_out_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal data_out_TSTRB_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_data_out_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_data_out_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_data_out_V_last_V_U_apdone_blk : STD_LOGIC;
    signal data_out_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_data_out_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_data_out_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_condition_400 : BOOLEAN;
    signal ap_condition_405 : BOOLEAN;
    signal ap_condition_406 : BOOLEAN;
    signal ap_condition_408 : BOOLEAN;
    signal ap_condition_346 : BOOLEAN;
    signal ap_condition_675 : BOOLEAN;
    signal ap_condition_679 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component conv2d_3x3_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component conv2d_3x3_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component conv2d_3x3_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);

    regslice_both_data_out_V_data_V_U : component conv2d_3x3_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => data_out_TDATA_int_regslice,
        vld_in => data_out_TVALID_int_regslice,
        ack_in => data_out_TREADY_int_regslice,
        data_out => data_out_TDATA,
        vld_out => regslice_both_data_out_V_data_V_U_vld_out,
        ack_out => data_out_TREADY,
        apdone_blk => regslice_both_data_out_V_data_V_U_apdone_blk);

    regslice_both_data_out_V_keep_V_U : component conv2d_3x3_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv8_FF,
        vld_in => data_out_TVALID_int_regslice,
        ack_in => regslice_both_data_out_V_keep_V_U_ack_in_dummy,
        data_out => data_out_TKEEP,
        vld_out => regslice_both_data_out_V_keep_V_U_vld_out,
        ack_out => data_out_TREADY,
        apdone_blk => regslice_both_data_out_V_keep_V_U_apdone_blk);

    regslice_both_data_out_V_strb_V_U : component conv2d_3x3_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => data_out_TSTRB_int_regslice,
        vld_in => data_out_TVALID_int_regslice,
        ack_in => regslice_both_data_out_V_strb_V_U_ack_in_dummy,
        data_out => data_out_TSTRB,
        vld_out => regslice_both_data_out_V_strb_V_U_vld_out,
        ack_out => data_out_TREADY,
        apdone_blk => regslice_both_data_out_V_strb_V_U_apdone_blk);

    regslice_both_data_out_V_last_V_U : component conv2d_3x3_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => data_out_TLAST_int_regslice,
        vld_in => data_out_TVALID_int_regslice,
        ack_in => regslice_both_data_out_V_last_V_U_ack_in_dummy,
        data_out => data_out_TLAST,
        vld_out => regslice_both_data_out_V_last_V_U_vld_out,
        ack_out => data_out_TREADY,
        apdone_blk => regslice_both_data_out_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage4_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter0_output_addr_2_reg_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_400)) then
                if ((icmp_ln169_fu_194_p2 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter0_output_addr_2_reg_116 <= ap_sig_allocacmp_output_addr_11;
                elsif ((icmp_ln169_fu_194_p2 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_output_addr_2_reg_116 <= output_addr_12_fu_200_p2;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_output_addr_4_reg_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_405)) then
                if ((icmp_ln169_1_fu_228_p2 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter0_output_addr_4_reg_126 <= ap_phi_reg_pp0_iter0_output_addr_2_reg_116;
                elsif ((icmp_ln169_1_fu_228_p2 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_output_addr_4_reg_126 <= output_addr_13_fu_234_p2;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_output_addr_6_reg_137_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_406)) then
                if ((icmp_ln169_2_fu_270_p2 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter0_output_addr_6_reg_137 <= ap_phi_reg_pp0_iter0_output_addr_4_reg_126;
                elsif ((icmp_ln169_2_fu_270_p2 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_output_addr_6_reg_137 <= output_addr_14_fu_276_p2;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_output_addr_8_reg_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_408)) then
                if ((icmp_ln169_3_fu_312_p2 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter0_output_addr_8_reg_148 <= ap_phi_reg_pp0_iter0_output_addr_6_reg_137;
                elsif ((icmp_ln169_3_fu_312_p2 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_output_addr_8_reg_148 <= output_addr_15_fu_318_p2;
                end if;
            end if; 
        end if;
    end process;

    i_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_346)) then
                if ((icmp_ln159_fu_188_p2 = ap_const_lv1_1)) then 
                    i_fu_84 <= i_5_fu_206_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_84 <= ap_const_lv18_0;
                end if;
            end if; 
        end if;
    end process;

    output_addr_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
                if ((ap_const_boolean_1 = ap_condition_679)) then 
                    output_addr_fu_88 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_675)) then 
                    output_addr_fu_88 <= ap_phi_mux_output_addr_10_phi_fu_161_p4;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln159_reg_409 <= icmp_ln159_fu_188_p2;
                icmp_ln159_reg_409_pp0_iter1_reg <= icmp_ln159_reg_409;
                icmp_ln169_reg_413 <= icmp_ln169_fu_194_p2;
                output_addr_11_reg_403 <= ap_sig_allocacmp_output_addr_11;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                icmp_ln169_1_reg_432 <= icmp_ln169_1_fu_228_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                icmp_ln169_2_reg_451 <= icmp_ln169_2_fu_270_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                icmp_ln169_3_reg_470 <= icmp_ln169_3_fu_312_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                icmp_ln169_4_reg_489 <= icmp_ln169_4_fu_354_p2;
                output_last_4_reg_493 <= output_last_4_fu_360_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                output_addr_2_reg_116 <= ap_phi_reg_pp0_iter0_output_addr_2_reg_116;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                output_addr_4_reg_126 <= ap_phi_reg_pp0_iter0_output_addr_4_reg_126;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                output_addr_6_reg_137 <= ap_phi_reg_pp0_iter0_output_addr_6_reg_137;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then
                reg_168 <= output_r_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_condition_exit_pp0_iter0_stage1, ap_block_pp0_stage4_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, icmp_ln159_reg_409, regslice_both_data_out_V_data_V_U_apdone_blk, ap_block_state1_pp0_stage0_iter0, ap_block_state6_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) or ((regslice_both_data_out_V_data_V_U_apdone_blk = ap_const_logic_1) and (icmp_ln159_reg_409 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, icmp_ln159_reg_409, regslice_both_data_out_V_data_V_U_apdone_blk, ap_block_state1_pp0_stage0_iter0, ap_block_state6_pp0_stage0_iter1, ap_block_state6_io)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state6_io) or (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter1))) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) or ((regslice_both_data_out_V_data_V_U_apdone_blk = ap_const_logic_1) and (icmp_ln159_reg_409 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, icmp_ln159_reg_409, regslice_both_data_out_V_data_V_U_apdone_blk, ap_block_state1_pp0_stage0_iter0, ap_block_state6_pp0_stage0_iter1, ap_block_state6_io)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state6_io) or (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter1))) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) or ((regslice_both_data_out_V_data_V_U_apdone_blk = ap_const_logic_1) and (icmp_ln159_reg_409 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, icmp_ln159_reg_409, regslice_both_data_out_V_data_V_U_apdone_blk, ap_block_state2_pp0_stage1_iter0, ap_block_state7_pp0_stage1_iter1)
    begin
                ap_block_pp0_stage1_01001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage1_iter1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0)) or ((regslice_both_data_out_V_data_V_U_apdone_blk = ap_const_logic_1) and (icmp_ln159_reg_409 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, icmp_ln159_reg_409, regslice_both_data_out_V_data_V_U_apdone_blk, ap_block_state2_pp0_stage1_iter0, ap_block_state2_io, ap_block_state7_pp0_stage1_iter1, ap_block_state7_io)
    begin
                ap_block_pp0_stage1_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state7_io) or (ap_const_boolean_1 = ap_block_state7_pp0_stage1_iter1))) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0))) or ((regslice_both_data_out_V_data_V_U_apdone_blk = ap_const_logic_1) and (icmp_ln159_reg_409 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, icmp_ln159_reg_409, regslice_both_data_out_V_data_V_U_apdone_blk, ap_block_state2_pp0_stage1_iter0, ap_block_state2_io, ap_block_state7_pp0_stage1_iter1, ap_block_state7_io)
    begin
                ap_block_pp0_stage1_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state7_io) or (ap_const_boolean_1 = ap_block_state7_pp0_stage1_iter1))) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0))) or ((regslice_both_data_out_V_data_V_U_apdone_blk = ap_const_logic_1) and (icmp_ln159_reg_409 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)));
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln159_reg_409, regslice_both_data_out_V_data_V_U_apdone_blk, ap_block_state3_pp0_stage2_iter0, ap_done_reg)
    begin
                ap_block_pp0_stage2_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0)) or ((regslice_both_data_out_V_data_V_U_apdone_blk = ap_const_logic_1) and (icmp_ln159_reg_409 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)));
    end process;


    ap_block_pp0_stage2_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln159_reg_409, regslice_both_data_out_V_data_V_U_apdone_blk, ap_block_state3_pp0_stage2_iter0, ap_block_state3_io, ap_done_reg)
    begin
                ap_block_pp0_stage2_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0))) or ((regslice_both_data_out_V_data_V_U_apdone_blk = ap_const_logic_1) and (icmp_ln159_reg_409 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)));
    end process;


    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln159_reg_409, regslice_both_data_out_V_data_V_U_apdone_blk, ap_block_state3_pp0_stage2_iter0, ap_block_state3_io, ap_done_reg)
    begin
                ap_block_pp0_stage2_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0))) or ((regslice_both_data_out_V_data_V_U_apdone_blk = ap_const_logic_1) and (icmp_ln159_reg_409 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)));
    end process;

        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln159_reg_409, regslice_both_data_out_V_data_V_U_apdone_blk, ap_block_state4_pp0_stage3_iter0)
    begin
                ap_block_pp0_stage3_01001 <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0)) or ((regslice_both_data_out_V_data_V_U_apdone_blk = ap_const_logic_1) and (icmp_ln159_reg_409 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)));
    end process;


    ap_block_pp0_stage3_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln159_reg_409, regslice_both_data_out_V_data_V_U_apdone_blk, ap_block_state4_pp0_stage3_iter0, ap_block_state4_io)
    begin
                ap_block_pp0_stage3_11001 <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0))) or ((regslice_both_data_out_V_data_V_U_apdone_blk = ap_const_logic_1) and (icmp_ln159_reg_409 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)));
    end process;


    ap_block_pp0_stage3_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln159_reg_409, regslice_both_data_out_V_data_V_U_apdone_blk, ap_block_state4_pp0_stage3_iter0, ap_block_state4_io)
    begin
                ap_block_pp0_stage3_subdone <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0))) or ((regslice_both_data_out_V_data_V_U_apdone_blk = ap_const_logic_1) and (icmp_ln159_reg_409 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)));
    end process;

        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln159_reg_409, regslice_both_data_out_V_data_V_U_apdone_blk, ap_block_state5_pp0_stage4_iter0)
    begin
                ap_block_pp0_stage4_01001 <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0)) or ((regslice_both_data_out_V_data_V_U_apdone_blk = ap_const_logic_1) and (icmp_ln159_reg_409 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)));
    end process;


    ap_block_pp0_stage4_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln159_reg_409, regslice_both_data_out_V_data_V_U_apdone_blk, ap_block_state5_pp0_stage4_iter0, ap_block_state5_io)
    begin
                ap_block_pp0_stage4_11001 <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0))) or ((regslice_both_data_out_V_data_V_U_apdone_blk = ap_const_logic_1) and (icmp_ln159_reg_409 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)));
    end process;


    ap_block_pp0_stage4_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln159_reg_409, regslice_both_data_out_V_data_V_U_apdone_blk, ap_block_state5_pp0_stage4_iter0, ap_block_state5_io)
    begin
                ap_block_pp0_stage4_subdone <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0))) or ((regslice_both_data_out_V_data_V_U_apdone_blk = ap_const_logic_1) and (icmp_ln159_reg_409 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_state2_io_assign_proc : process(ap_predicate_op31_write_state2, data_out_TREADY_int_regslice)
    begin
                ap_block_state2_io <= ((data_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op31_write_state2 = ap_const_boolean_1));
    end process;


    ap_block_state2_pp0_stage1_iter0_assign_proc : process(output_r_empty_n, icmp_ln159_reg_409, ap_predicate_op31_write_state2, regslice_both_data_out_V_data_V_U_apdone_blk, data_out_TREADY_int_regslice)
    begin
                ap_block_state2_pp0_stage1_iter0 <= ((regslice_both_data_out_V_data_V_U_apdone_blk = ap_const_logic_1) or ((data_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op31_write_state2 = ap_const_boolean_1)) or ((icmp_ln159_reg_409 = ap_const_lv1_1) and (output_r_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state3_io_assign_proc : process(ap_predicate_op38_write_state3, ap_predicate_op43_write_state3, data_out_TREADY_int_regslice)
    begin
                ap_block_state3_io <= (((data_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op43_write_state3 = ap_const_boolean_1)) or ((data_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op38_write_state3 = ap_const_boolean_1)));
    end process;


    ap_block_state3_pp0_stage2_iter0_assign_proc : process(output_r_empty_n, icmp_ln159_reg_409, ap_predicate_op38_write_state3, ap_predicate_op43_write_state3, data_out_TREADY_int_regslice)
    begin
                ap_block_state3_pp0_stage2_iter0 <= (((data_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op43_write_state3 = ap_const_boolean_1)) or ((data_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op38_write_state3 = ap_const_boolean_1)) or ((icmp_ln159_reg_409 = ap_const_lv1_1) and (output_r_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state4_io_assign_proc : process(ap_predicate_op50_write_state4, ap_predicate_op55_write_state4, data_out_TREADY_int_regslice)
    begin
                ap_block_state4_io <= (((data_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op55_write_state4 = ap_const_boolean_1)) or ((data_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op50_write_state4 = ap_const_boolean_1)));
    end process;


    ap_block_state4_pp0_stage3_iter0_assign_proc : process(output_r_empty_n, icmp_ln159_reg_409, ap_predicate_op50_write_state4, ap_predicate_op55_write_state4, data_out_TREADY_int_regslice)
    begin
                ap_block_state4_pp0_stage3_iter0 <= (((data_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op55_write_state4 = ap_const_boolean_1)) or ((data_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op50_write_state4 = ap_const_boolean_1)) or ((icmp_ln159_reg_409 = ap_const_lv1_1) and (output_r_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state5_io_assign_proc : process(ap_predicate_op65_write_state5, ap_predicate_op70_write_state5, data_out_TREADY_int_regslice)
    begin
                ap_block_state5_io <= (((data_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op70_write_state5 = ap_const_boolean_1)) or ((data_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op65_write_state5 = ap_const_boolean_1)));
    end process;


    ap_block_state5_pp0_stage4_iter0_assign_proc : process(output_r_empty_n, icmp_ln159_reg_409, ap_predicate_op65_write_state5, ap_predicate_op70_write_state5, data_out_TREADY_int_regslice)
    begin
                ap_block_state5_pp0_stage4_iter0 <= (((data_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op70_write_state5 = ap_const_boolean_1)) or ((data_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op65_write_state5 = ap_const_boolean_1)) or ((icmp_ln159_reg_409 = ap_const_lv1_1) and (output_r_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state6_io_assign_proc : process(ap_predicate_op80_write_state6, ap_predicate_op82_write_state6, data_out_TREADY_int_regslice)
    begin
                ap_block_state6_io <= (((data_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op82_write_state6 = ap_const_boolean_1)) or ((data_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op80_write_state6 = ap_const_boolean_1)));
    end process;


    ap_block_state6_pp0_stage0_iter1_assign_proc : process(ap_predicate_op80_write_state6, ap_predicate_op82_write_state6, data_out_TREADY_int_regslice)
    begin
                ap_block_state6_pp0_stage0_iter1 <= (((data_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op82_write_state6 = ap_const_boolean_1)) or ((data_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op80_write_state6 = ap_const_boolean_1)));
    end process;


    ap_block_state7_io_assign_proc : process(ap_predicate_op83_write_state7, data_out_TREADY_int_regslice)
    begin
                ap_block_state7_io <= ((ap_predicate_op83_write_state7 = ap_const_boolean_1) and (data_out_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state7_pp0_stage1_iter1_assign_proc : process(ap_predicate_op83_write_state7, data_out_TREADY_int_regslice)
    begin
                ap_block_state7_pp0_stage1_iter1 <= ((ap_predicate_op83_write_state7 = ap_const_boolean_1) and (data_out_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_condition_346_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_346 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_400_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001, icmp_ln159_fu_188_p2)
    begin
                ap_condition_400 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln159_fu_188_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_405_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln159_reg_409, ap_block_pp0_stage1_11001)
    begin
                ap_condition_405 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln159_reg_409 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1));
    end process;


    ap_condition_406_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln159_reg_409, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
                ap_condition_406 <= ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (icmp_ln159_reg_409 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2));
    end process;


    ap_condition_408_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln159_reg_409, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
                ap_condition_408 <= ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (icmp_ln159_reg_409 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3));
    end process;


    ap_condition_675_assign_proc : process(icmp_ln159_reg_409, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_11001)
    begin
                ap_condition_675 <= ((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (icmp_ln159_reg_409 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4));
    end process;


    ap_condition_679_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_loop_init)
    begin
                ap_condition_679 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln159_reg_409, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (icmp_ln159_reg_409 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_loop_exit_ready, ap_block_pp0_stage1_subdone, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_phi_mux_output_addr_10_phi_fu_161_p4_assign_proc : process(icmp_ln159_reg_409, icmp_ln169_4_fu_354_p2, ap_phi_reg_pp0_iter0_output_addr_8_reg_148, output_addr_16_fu_366_p2, ap_phi_reg_pp0_iter0_output_addr_10_reg_158)
    begin
        if ((icmp_ln159_reg_409 = ap_const_lv1_1)) then
            if ((icmp_ln169_4_fu_354_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_output_addr_10_phi_fu_161_p4 <= ap_phi_reg_pp0_iter0_output_addr_8_reg_148;
            elsif ((icmp_ln169_4_fu_354_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_output_addr_10_phi_fu_161_p4 <= output_addr_16_fu_366_p2;
            else 
                ap_phi_mux_output_addr_10_phi_fu_161_p4 <= ap_phi_reg_pp0_iter0_output_addr_10_reg_158;
            end if;
        else 
            ap_phi_mux_output_addr_10_phi_fu_161_p4 <= ap_phi_reg_pp0_iter0_output_addr_10_reg_158;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_output_addr_10_reg_158 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op31_write_state2_assign_proc : process(icmp_ln159_reg_409, icmp_ln169_reg_413)
    begin
                ap_predicate_op31_write_state2 <= ((icmp_ln169_reg_413 = ap_const_lv1_1) and (icmp_ln159_reg_409 = ap_const_lv1_1));
    end process;


    ap_predicate_op38_write_state3_assign_proc : process(icmp_ln159_reg_409, icmp_ln169_reg_413)
    begin
                ap_predicate_op38_write_state3 <= ((icmp_ln169_reg_413 = ap_const_lv1_1) and (icmp_ln159_reg_409 = ap_const_lv1_1));
    end process;


    ap_predicate_op43_write_state3_assign_proc : process(icmp_ln159_reg_409, icmp_ln169_1_reg_432)
    begin
                ap_predicate_op43_write_state3 <= ((icmp_ln159_reg_409 = ap_const_lv1_1) and (icmp_ln169_1_reg_432 = ap_const_lv1_1));
    end process;


    ap_predicate_op50_write_state4_assign_proc : process(icmp_ln159_reg_409, icmp_ln169_1_reg_432)
    begin
                ap_predicate_op50_write_state4 <= ((icmp_ln159_reg_409 = ap_const_lv1_1) and (icmp_ln169_1_reg_432 = ap_const_lv1_1));
    end process;


    ap_predicate_op55_write_state4_assign_proc : process(icmp_ln159_reg_409, icmp_ln169_2_reg_451)
    begin
                ap_predicate_op55_write_state4 <= ((icmp_ln159_reg_409 = ap_const_lv1_1) and (icmp_ln169_2_reg_451 = ap_const_lv1_1));
    end process;


    ap_predicate_op65_write_state5_assign_proc : process(icmp_ln159_reg_409, icmp_ln169_2_reg_451)
    begin
                ap_predicate_op65_write_state5 <= ((icmp_ln159_reg_409 = ap_const_lv1_1) and (icmp_ln169_2_reg_451 = ap_const_lv1_1));
    end process;


    ap_predicate_op70_write_state5_assign_proc : process(icmp_ln159_reg_409, icmp_ln169_3_reg_470)
    begin
                ap_predicate_op70_write_state5 <= ((icmp_ln159_reg_409 = ap_const_lv1_1) and (icmp_ln169_3_reg_470 = ap_const_lv1_1));
    end process;


    ap_predicate_op80_write_state6_assign_proc : process(icmp_ln159_reg_409, icmp_ln169_3_reg_470)
    begin
                ap_predicate_op80_write_state6 <= ((icmp_ln159_reg_409 = ap_const_lv1_1) and (icmp_ln169_3_reg_470 = ap_const_lv1_1));
    end process;


    ap_predicate_op82_write_state6_assign_proc : process(icmp_ln159_reg_409, icmp_ln169_4_reg_489)
    begin
                ap_predicate_op82_write_state6 <= ((icmp_ln169_4_reg_489 = ap_const_lv1_1) and (icmp_ln159_reg_409 = ap_const_lv1_1));
    end process;


    ap_predicate_op83_write_state7_assign_proc : process(icmp_ln159_reg_409_pp0_iter1_reg, icmp_ln169_4_reg_489)
    begin
                ap_predicate_op83_write_state7 <= ((icmp_ln169_4_reg_489 = ap_const_lv1_1) and (icmp_ln159_reg_409_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage4_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, i_fu_84, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_4 <= ap_const_lv18_0;
        else 
            ap_sig_allocacmp_i_4 <= i_fu_84;
        end if; 
    end process;


    ap_sig_allocacmp_output_addr_11_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_loop_init, output_addr_fu_88)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_output_addr_11 <= ap_const_lv32_0;
        else 
            ap_sig_allocacmp_output_addr_11 <= output_addr_fu_88;
        end if; 
    end process;


    data_out_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, icmp_ln159_reg_409, icmp_ln169_reg_413, ap_predicate_op31_write_state2, icmp_ln169_4_reg_489, ap_predicate_op83_write_state7, ap_CS_fsm_pp0_stage4, icmp_ln169_2_reg_451, ap_predicate_op65_write_state5, icmp_ln169_3_reg_470, ap_predicate_op70_write_state5, ap_block_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, icmp_ln169_1_reg_432, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, ap_block_pp0_stage4, ap_block_pp0_stage0, data_out_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln169_4_reg_489 = ap_const_lv1_1) and (icmp_ln159_reg_409 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln159_reg_409 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln169_3_reg_470 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_predicate_op70_write_state5 = ap_const_boolean_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_predicate_op65_write_state5 = ap_const_boolean_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage3) and (icmp_ln159_reg_409 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) 
    and (icmp_ln169_1_reg_432 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage3) and (icmp_ln159_reg_409 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (icmp_ln169_2_reg_451 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2) and (icmp_ln169_reg_413 = ap_const_lv1_1) and (icmp_ln159_reg_409 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage2) and (icmp_ln159_reg_409 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (icmp_ln169_1_reg_432 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_predicate_op83_write_state7 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_predicate_op31_write_state2 = ap_const_boolean_1) 
    and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            data_out_TDATA_blk_n <= data_out_TREADY_int_regslice;
        else 
            data_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_out_TDATA_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_predicate_op31_write_state2, ap_CS_fsm_pp0_stage4, ap_predicate_op70_write_state5, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, reg_168, ap_predicate_op43_write_state3, ap_predicate_op55_write_state4, ap_predicate_op82_write_state6, output_data_fu_217_p1, output_data_1_fu_254_p3, output_data_2_fu_296_p3, output_data_3_fu_338_p3, ap_block_pp0_stage1_01001, ap_block_pp0_stage2_01001, ap_block_pp0_stage3_01001, ap_block_pp0_stage4_01001, ap_block_pp0_stage0_01001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_predicate_op82_write_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_out_TDATA_int_regslice <= reg_168(79 downto 16);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage4_01001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_predicate_op70_write_state5 = ap_const_boolean_1))) then 
            data_out_TDATA_int_regslice <= output_data_3_fu_338_p3;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_01001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op55_write_state4 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            data_out_TDATA_int_regslice <= output_data_2_fu_296_p3;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_01001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op43_write_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            data_out_TDATA_int_regslice <= output_data_1_fu_254_p3;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_01001) and (ap_predicate_op31_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            data_out_TDATA_int_regslice <= output_data_fu_217_p1;
        else 
            data_out_TDATA_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    data_out_TLAST_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_predicate_op31_write_state2, ap_CS_fsm_pp0_stage4, ap_predicate_op70_write_state5, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_predicate_op43_write_state3, ap_predicate_op55_write_state4, ap_predicate_op82_write_state6, output_last_fu_222_p2, output_last_1_fu_263_p2, output_last_2_fu_305_p2, output_last_3_fu_347_p2, output_last_4_reg_493, ap_block_pp0_stage1_01001, ap_block_pp0_stage2_01001, ap_block_pp0_stage3_01001, ap_block_pp0_stage4_01001, ap_block_pp0_stage0_01001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_predicate_op82_write_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_out_TLAST_int_regslice <= output_last_4_reg_493;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage4_01001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_predicate_op70_write_state5 = ap_const_boolean_1))) then 
            data_out_TLAST_int_regslice <= output_last_3_fu_347_p2;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_01001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op55_write_state4 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            data_out_TLAST_int_regslice <= output_last_2_fu_305_p2;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_01001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op43_write_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            data_out_TLAST_int_regslice <= output_last_1_fu_263_p2;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_01001) and (ap_predicate_op31_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            data_out_TLAST_int_regslice <= output_last_fu_222_p2;
        else 
            data_out_TLAST_int_regslice <= "X";
        end if; 
    end process;

    data_out_TSTRB_int_regslice <= "XXXXXXXX";
    data_out_TVALID <= regslice_both_data_out_V_data_V_U_vld_out;

    data_out_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_predicate_op31_write_state2, ap_CS_fsm_pp0_stage4, ap_predicate_op70_write_state5, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage1_11001, ap_predicate_op43_write_state3, ap_block_pp0_stage2_11001, ap_predicate_op55_write_state4, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001, ap_predicate_op82_write_state6, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op82_write_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (ap_predicate_op70_write_state5 = ap_const_boolean_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op55_write_state4 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op43_write_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_predicate_op31_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            data_out_TVALID_int_regslice <= ap_const_logic_1;
        else 
            data_out_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    i_5_fu_206_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_4) + unsigned(ap_const_lv18_4));
    icmp_ln159_fu_188_p2 <= "1" when (unsigned(ap_sig_allocacmp_i_4) < unsigned(ap_const_lv18_3F480)) else "0";
    icmp_ln169_1_fu_228_p2 <= "1" when (signed(ap_phi_reg_pp0_iter0_output_addr_2_reg_116) < signed(ap_const_lv32_4F1A0)) else "0";
    icmp_ln169_2_fu_270_p2 <= "1" when (signed(ap_phi_reg_pp0_iter0_output_addr_4_reg_126) < signed(ap_const_lv32_4F1A0)) else "0";
    icmp_ln169_3_fu_312_p2 <= "1" when (signed(ap_phi_reg_pp0_iter0_output_addr_6_reg_137) < signed(ap_const_lv32_4F1A0)) else "0";
    icmp_ln169_4_fu_354_p2 <= "1" when (signed(ap_phi_reg_pp0_iter0_output_addr_8_reg_148) < signed(ap_const_lv32_4F1A0)) else "0";
    icmp_ln169_fu_194_p2 <= "1" when (signed(ap_sig_allocacmp_output_addr_11) < signed(ap_const_lv32_4F1A0)) else "0";
    output_addr_12_fu_200_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_output_addr_11) + unsigned(ap_const_lv32_1));
    output_addr_13_fu_234_p2 <= std_logic_vector(unsigned(ap_phi_reg_pp0_iter0_output_addr_2_reg_116) + unsigned(ap_const_lv32_1));
    output_addr_14_fu_276_p2 <= std_logic_vector(unsigned(ap_phi_reg_pp0_iter0_output_addr_4_reg_126) + unsigned(ap_const_lv32_1));
    output_addr_15_fu_318_p2 <= std_logic_vector(unsigned(ap_phi_reg_pp0_iter0_output_addr_6_reg_137) + unsigned(ap_const_lv32_1));
    output_addr_16_fu_366_p2 <= std_logic_vector(unsigned(ap_phi_reg_pp0_iter0_output_addr_8_reg_148) + unsigned(ap_const_lv32_1));
    output_data_1_fu_254_p3 <= (trunc_ln171_fu_250_p1 & tmp_fu_240_p4);
    output_data_2_fu_296_p3 <= (trunc_ln171_1_fu_292_p1 & tmp_18_fu_282_p4);
    output_data_3_fu_338_p3 <= (trunc_ln171_2_fu_334_p1 & tmp_20_fu_324_p4);
    output_data_fu_217_p1 <= output_r_dout(64 - 1 downto 0);
    output_last_1_fu_263_p2 <= "1" when (output_addr_2_reg_116 = ap_const_lv32_4F19F) else "0";
    output_last_2_fu_305_p2 <= "1" when (output_addr_4_reg_126 = ap_const_lv32_4F19F) else "0";
    output_last_3_fu_347_p2 <= "1" when (output_addr_6_reg_137 = ap_const_lv32_4F19F) else "0";
    output_last_4_fu_360_p2 <= "1" when (ap_phi_reg_pp0_iter0_output_addr_8_reg_148 = ap_const_lv32_4F19F) else "0";
    output_last_fu_222_p2 <= "1" when (output_addr_11_reg_403 = ap_const_lv32_4F19F) else "0";

    output_r_blk_n_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, output_r_empty_n, icmp_ln159_reg_409, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, ap_block_pp0_stage4)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage4) and (icmp_ln159_reg_409 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3) and (icmp_ln159_reg_409 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2) and (icmp_ln159_reg_409 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (icmp_ln159_reg_409 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            output_r_blk_n <= output_r_empty_n;
        else 
            output_r_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    output_r_read_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln159_reg_409, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (icmp_ln159_reg_409 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (icmp_ln159_reg_409 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (icmp_ln159_reg_409 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln159_reg_409 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            output_r_read <= ap_const_logic_1;
        else 
            output_r_read <= ap_const_logic_0;
        end if; 
    end process;

    tmp_18_fu_282_p4 <= reg_168(79 downto 48);
    tmp_20_fu_324_p4 <= reg_168(79 downto 32);
    tmp_fu_240_p4 <= reg_168(79 downto 64);
    trunc_ln171_1_fu_292_p1 <= output_r_dout(32 - 1 downto 0);
    trunc_ln171_2_fu_334_p1 <= output_r_dout(16 - 1 downto 0);
    trunc_ln171_fu_250_p1 <= output_r_dout(48 - 1 downto 0);
end behav;
