// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="conv2d_3x3_conv2d_3x3,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu1cg-sbva484-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.304750,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=30,HLS_SYN_DSP=0,HLS_SYN_FF=3194,HLS_SYN_LUT=8490,HLS_VERSION=2023_2}" *)

module conv2d_3x3 (
        data_in_TDATA,
        data_in_TKEEP,
        data_in_TSTRB,
        data_in_TLAST,
        data_out_TDATA,
        data_out_TKEEP,
        data_out_TSTRB,
        data_out_TLAST,
        ap_clk,
        ap_rst_n,
        data_in_TVALID,
        data_in_TREADY,
        data_out_TVALID,
        data_out_TREADY
);


input  [63:0] data_in_TDATA;
input  [7:0] data_in_TKEEP;
input  [7:0] data_in_TSTRB;
input  [0:0] data_in_TLAST;
output  [63:0] data_out_TDATA;
output  [7:0] data_out_TKEEP;
output  [7:0] data_out_TSTRB;
output  [0:0] data_out_TLAST;
input   ap_clk;
input   ap_rst_n;
input   data_in_TVALID;
output   data_in_TREADY;
output   data_out_TVALID;
input   data_out_TREADY;

 reg    ap_rst_n_inv;
wire    data_unpacket_U0_ap_start;
wire    data_unpacket_U0_ap_done;
wire    data_unpacket_U0_ap_continue;
wire    data_unpacket_U0_ap_idle;
wire    data_unpacket_U0_ap_ready;
wire   [79:0] data_unpacket_U0_input_r_din;
wire    data_unpacket_U0_input_r_write;
wire    data_unpacket_U0_data_in_TREADY;
wire    image_filter_U0_ap_start;
wire    image_filter_U0_ap_done;
wire    image_filter_U0_ap_continue;
wire    image_filter_U0_ap_idle;
wire    image_filter_U0_ap_ready;
wire    image_filter_U0_input_r_read;
wire   [79:0] image_filter_U0_output_r_din;
wire    image_filter_U0_output_r_write;
wire    data_packet_U0_ap_start;
wire    data_packet_U0_ap_done;
wire    data_packet_U0_ap_continue;
wire    data_packet_U0_ap_idle;
wire    data_packet_U0_ap_ready;
wire    data_packet_U0_output_r_read;
wire   [63:0] data_packet_U0_data_out_TDATA;
wire    data_packet_U0_data_out_TVALID;
wire   [7:0] data_packet_U0_data_out_TKEEP;
wire   [7:0] data_packet_U0_data_out_TSTRB;
wire   [0:0] data_packet_U0_data_out_TLAST;
wire    input_r_full_n;
wire   [79:0] input_r_dout;
wire   [2:0] input_r_num_data_valid;
wire   [2:0] input_r_fifo_cap;
wire    input_r_empty_n;
wire    output_r_full_n;
wire   [79:0] output_r_dout;
wire   [2:0] output_r_num_data_valid;
wire   [2:0] output_r_fifo_cap;
wire    output_r_empty_n;

conv2d_3x3_data_unpacket data_unpacket_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(data_unpacket_U0_ap_start),
    .ap_done(data_unpacket_U0_ap_done),
    .ap_continue(data_unpacket_U0_ap_continue),
    .ap_idle(data_unpacket_U0_ap_idle),
    .ap_ready(data_unpacket_U0_ap_ready),
    .data_in_TVALID(data_in_TVALID),
    .input_r_din(data_unpacket_U0_input_r_din),
    .input_r_num_data_valid(input_r_num_data_valid),
    .input_r_fifo_cap(input_r_fifo_cap),
    .input_r_full_n(input_r_full_n),
    .input_r_write(data_unpacket_U0_input_r_write),
    .data_in_TDATA(data_in_TDATA),
    .data_in_TREADY(data_unpacket_U0_data_in_TREADY),
    .data_in_TKEEP(data_in_TKEEP),
    .data_in_TSTRB(data_in_TSTRB),
    .data_in_TLAST(data_in_TLAST)
);

conv2d_3x3_image_filter image_filter_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(image_filter_U0_ap_start),
    .ap_done(image_filter_U0_ap_done),
    .ap_continue(image_filter_U0_ap_continue),
    .ap_idle(image_filter_U0_ap_idle),
    .ap_ready(image_filter_U0_ap_ready),
    .input_r_dout(input_r_dout),
    .input_r_num_data_valid(input_r_num_data_valid),
    .input_r_fifo_cap(input_r_fifo_cap),
    .input_r_empty_n(input_r_empty_n),
    .input_r_read(image_filter_U0_input_r_read),
    .output_r_din(image_filter_U0_output_r_din),
    .output_r_num_data_valid(output_r_num_data_valid),
    .output_r_fifo_cap(output_r_fifo_cap),
    .output_r_full_n(output_r_full_n),
    .output_r_write(image_filter_U0_output_r_write)
);

conv2d_3x3_data_packet data_packet_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(data_packet_U0_ap_start),
    .ap_done(data_packet_U0_ap_done),
    .ap_continue(data_packet_U0_ap_continue),
    .ap_idle(data_packet_U0_ap_idle),
    .ap_ready(data_packet_U0_ap_ready),
    .output_r_dout(output_r_dout),
    .output_r_num_data_valid(output_r_num_data_valid),
    .output_r_fifo_cap(output_r_fifo_cap),
    .output_r_empty_n(output_r_empty_n),
    .output_r_read(data_packet_U0_output_r_read),
    .data_out_TREADY(data_out_TREADY),
    .data_out_TDATA(data_packet_U0_data_out_TDATA),
    .data_out_TVALID(data_packet_U0_data_out_TVALID),
    .data_out_TKEEP(data_packet_U0_data_out_TKEEP),
    .data_out_TSTRB(data_packet_U0_data_out_TSTRB),
    .data_out_TLAST(data_packet_U0_data_out_TLAST)
);

conv2d_3x3_fifo_w80_d2_S input_r_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(data_unpacket_U0_input_r_din),
    .if_full_n(input_r_full_n),
    .if_write(data_unpacket_U0_input_r_write),
    .if_dout(input_r_dout),
    .if_num_data_valid(input_r_num_data_valid),
    .if_fifo_cap(input_r_fifo_cap),
    .if_empty_n(input_r_empty_n),
    .if_read(image_filter_U0_input_r_read)
);

conv2d_3x3_fifo_w80_d2_S output_r_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(image_filter_U0_output_r_din),
    .if_full_n(output_r_full_n),
    .if_write(image_filter_U0_output_r_write),
    .if_dout(output_r_dout),
    .if_num_data_valid(output_r_num_data_valid),
    .if_fifo_cap(output_r_fifo_cap),
    .if_empty_n(output_r_empty_n),
    .if_read(data_packet_U0_output_r_read)
);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign data_in_TREADY = data_unpacket_U0_data_in_TREADY;

assign data_out_TDATA = data_packet_U0_data_out_TDATA;

assign data_out_TKEEP = data_packet_U0_data_out_TKEEP;

assign data_out_TLAST = data_packet_U0_data_out_TLAST;

assign data_out_TSTRB = data_packet_U0_data_out_TSTRB;

assign data_out_TVALID = data_packet_U0_data_out_TVALID;

assign data_packet_U0_ap_continue = 1'b1;

assign data_packet_U0_ap_start = 1'b1;

assign data_unpacket_U0_ap_continue = 1'b1;

assign data_unpacket_U0_ap_start = 1'b1;

assign image_filter_U0_ap_continue = 1'b1;

assign image_filter_U0_ap_start = 1'b1;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "conv2d_3x3_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "conv2d_3x3_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //conv2d_3x3

