// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module conv2d_3x3_image_filter (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        input_r_dout,
        input_r_num_data_valid,
        input_r_fifo_cap,
        input_r_empty_n,
        input_r_read,
        output_r_din,
        output_r_num_data_valid,
        output_r_fifo_cap,
        output_r_full_n,
        output_r_write
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [79:0] input_r_dout;
input  [2:0] input_r_num_data_valid;
input  [2:0] input_r_fifo_cap;
input   input_r_empty_n;
output   input_r_read;
output  [79:0] output_r_din;
input  [2:0] output_r_num_data_valid;
input  [2:0] output_r_fifo_cap;
input   output_r_full_n;
output   output_r_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_r_read;
reg[79:0] output_r_din;
reg output_r_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [9:0] window_adjust_0_0_0;
reg   [9:0] window_adjust_0_2_0;
reg   [9:0] window_adjust_1_0_0;
reg   [9:0] window_adjust_1_2_0;
reg   [9:0] window_adjust_2_0_0;
reg   [9:0] window_adjust_2_2_0;
reg   [9:0] window_adjust_0_0_1;
reg   [9:0] window_adjust_0_2_1;
reg   [9:0] window_adjust_1_0_1;
reg   [9:0] window_adjust_1_2_1;
reg   [9:0] window_adjust_2_0_1;
reg   [9:0] window_adjust_2_2_1;
reg   [9:0] window_adjust_0_0_2;
reg   [9:0] window_adjust_0_2_2;
reg   [9:0] window_adjust_1_0_2;
reg   [9:0] window_adjust_1_2_2;
reg   [9:0] window_adjust_2_0_2;
reg   [9:0] window_adjust_2_2_2;
reg   [9:0] window_adjust_0_0_3;
reg   [9:0] window_adjust_0_2_3;
reg   [9:0] window_adjust_1_0_3;
reg   [9:0] window_adjust_1_2_3;
reg   [9:0] window_adjust_2_0_3;
reg   [9:0] window_adjust_2_2_3;
reg   [9:0] window_adjust_0_0_4;
reg   [9:0] window_adjust_0_2_4;
reg   [9:0] window_adjust_1_0_4;
reg   [9:0] window_adjust_1_2_4;
reg   [9:0] window_adjust_2_0_4;
reg   [9:0] window_adjust_2_2_4;
reg   [9:0] window_adjust_0_0_5;
reg   [9:0] window_adjust_0_2_5;
reg   [9:0] window_adjust_1_0_5;
reg   [9:0] window_adjust_1_2_5;
reg   [9:0] window_adjust_2_0_5;
reg   [9:0] window_adjust_2_2_5;
reg   [9:0] window_adjust_0_0_6;
reg   [9:0] window_adjust_0_2_6;
reg   [9:0] window_adjust_1_0_6;
reg   [9:0] window_adjust_1_2_6;
reg   [9:0] window_adjust_2_0_6;
reg   [9:0] window_adjust_2_2_6;
reg   [9:0] window_adjust_0_0_7;
reg   [9:0] window_adjust_0_2_7;
reg   [9:0] window_adjust_1_0_7;
reg   [9:0] window_adjust_1_2_7;
reg   [9:0] window_adjust_2_0_7;
reg   [9:0] window_adjust_2_2_7;
reg   [6:0] linebuf_0_0_address0;
reg    linebuf_0_0_ce0;
reg    linebuf_0_0_we0;
wire   [79:0] linebuf_0_0_q0;
reg    linebuf_0_0_ce1;
wire   [79:0] linebuf_0_0_q1;
reg   [6:0] linebuf_1_0_address0;
reg    linebuf_1_0_ce0;
reg    linebuf_1_0_we0;
wire   [79:0] linebuf_1_0_q0;
reg    linebuf_1_0_ce1;
wire   [79:0] linebuf_1_0_q1;
reg   [6:0] linebuf_2_0_address0;
reg    linebuf_2_0_ce0;
reg    linebuf_2_0_we0;
wire   [79:0] linebuf_2_0_q0;
reg    linebuf_2_0_ce1;
wire   [79:0] linebuf_2_0_q1;
reg   [6:0] linebuf_1_1_address0;
reg    linebuf_1_1_ce0;
reg    linebuf_1_1_we0;
wire   [79:0] linebuf_1_1_q0;
reg    linebuf_1_1_ce1;
wire   [79:0] linebuf_1_1_q1;
reg   [6:0] linebuf_2_1_address0;
reg    linebuf_2_1_ce0;
reg    linebuf_2_1_we0;
wire   [79:0] linebuf_2_1_q0;
reg    linebuf_2_1_ce1;
wire   [79:0] linebuf_2_1_q1;
reg   [6:0] linebuf_0_1_address0;
reg    linebuf_0_1_ce0;
reg    linebuf_0_1_we0;
wire   [79:0] linebuf_0_1_q0;
reg    linebuf_0_1_ce1;
wire   [79:0] linebuf_0_1_q1;
reg    output_r_blk_n;
wire    ap_CS_fsm_state6;
reg   [0:0] cmp_reg_440;
wire   [0:0] cmp4_fu_401_p2;
reg   [0:0] cmp4_reg_435;
wire    ap_CS_fsm_state2;
wire   [0:0] cmp_fu_408_p2;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_ap_start;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_ap_done;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_ap_idle;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_ap_ready;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_input_r_read;
wire   [79:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_output_r_din;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_output_r_write;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_0_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_0_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_0_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_0_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_0_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_0_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_0_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_0_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_0_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_0_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_0_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_0_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_1_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_1_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_1_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_1_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_1_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_1_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_1_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_1_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_1_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_1_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_1_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_1_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_2_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_2_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_2_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_2_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_2_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_2_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_2_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_2_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_2_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_2_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_2_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_2_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_3_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_3_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_3_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_3_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_3_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_3_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_3_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_3_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_3_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_3_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_3_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_3_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_4_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_4_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_4_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_4_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_4_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_4_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_4_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_4_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_4_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_4_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_4_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_4_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_5_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_5_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_5_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_5_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_5_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_5_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_5_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_5_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_5_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_5_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_5_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_5_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_6_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_6_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_6_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_6_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_6_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_6_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_6_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_6_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_6_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_6_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_6_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_6_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_7_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_7_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_7_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_7_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_7_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_7_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_7_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_7_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_7_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_7_o_ap_vld;
wire   [9:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_7_o;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_7_o_ap_vld;
wire   [6:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_0_address0;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_0_ce0;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_0_we0;
wire   [79:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_0_d0;
wire   [6:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_0_address1;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_0_ce1;
wire   [6:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_0_address0;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_0_ce0;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_0_we0;
wire   [79:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_0_d0;
wire   [6:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_0_address1;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_0_ce1;
wire   [6:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_0_address0;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_0_ce0;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_0_we0;
wire   [79:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_0_d0;
wire   [6:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_0_address1;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_0_ce1;
wire   [6:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_1_address0;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_1_ce0;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_1_we0;
wire   [79:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_1_d0;
wire   [6:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_1_address1;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_1_ce1;
wire   [6:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_1_address0;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_1_ce0;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_1_we0;
wire   [79:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_1_d0;
wire   [6:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_1_address1;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_1_ce1;
wire   [6:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_1_address0;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_1_ce0;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_1_we0;
wire   [79:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_1_d0;
wire   [6:0] grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_1_address1;
wire    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_1_ce1;
wire    grp_shift_register_fu_278_ap_start;
wire    grp_shift_register_fu_278_ap_done;
wire    grp_shift_register_fu_278_ap_idle;
wire    grp_shift_register_fu_278_ap_ready;
wire   [6:0] grp_shift_register_fu_278_linebuf_0_0_address0;
wire    grp_shift_register_fu_278_linebuf_0_0_ce0;
wire   [6:0] grp_shift_register_fu_278_linebuf_0_1_address0;
wire    grp_shift_register_fu_278_linebuf_0_1_ce0;
wire   [6:0] grp_shift_register_fu_278_linebuf_1_0_address0;
wire    grp_shift_register_fu_278_linebuf_1_0_ce0;
wire   [6:0] grp_shift_register_fu_278_linebuf_1_1_address0;
wire    grp_shift_register_fu_278_linebuf_1_1_ce0;
wire   [6:0] grp_shift_register_fu_278_linebuf_2_0_address0;
wire    grp_shift_register_fu_278_linebuf_2_0_ce0;
wire   [6:0] grp_shift_register_fu_278_linebuf_2_1_address0;
wire    grp_shift_register_fu_278_linebuf_2_1_ce0;
wire   [9:0] grp_shift_register_fu_278_window_adjust_0_0_0_o;
wire    grp_shift_register_fu_278_window_adjust_0_0_0_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_1_0_0_o;
wire    grp_shift_register_fu_278_window_adjust_1_0_0_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_2_0_0_o;
wire    grp_shift_register_fu_278_window_adjust_2_0_0_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_0_0_1_o;
wire    grp_shift_register_fu_278_window_adjust_0_0_1_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_1_0_1_o;
wire    grp_shift_register_fu_278_window_adjust_1_0_1_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_2_0_1_o;
wire    grp_shift_register_fu_278_window_adjust_2_0_1_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_0_0_2_o;
wire    grp_shift_register_fu_278_window_adjust_0_0_2_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_1_0_2_o;
wire    grp_shift_register_fu_278_window_adjust_1_0_2_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_2_0_2_o;
wire    grp_shift_register_fu_278_window_adjust_2_0_2_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_0_0_3_o;
wire    grp_shift_register_fu_278_window_adjust_0_0_3_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_1_0_3_o;
wire    grp_shift_register_fu_278_window_adjust_1_0_3_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_2_0_3_o;
wire    grp_shift_register_fu_278_window_adjust_2_0_3_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_0_0_4_o;
wire    grp_shift_register_fu_278_window_adjust_0_0_4_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_1_0_4_o;
wire    grp_shift_register_fu_278_window_adjust_1_0_4_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_2_0_4_o;
wire    grp_shift_register_fu_278_window_adjust_2_0_4_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_0_0_5_o;
wire    grp_shift_register_fu_278_window_adjust_0_0_5_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_1_0_5_o;
wire    grp_shift_register_fu_278_window_adjust_1_0_5_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_2_0_5_o;
wire    grp_shift_register_fu_278_window_adjust_2_0_5_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_0_0_6_o;
wire    grp_shift_register_fu_278_window_adjust_0_0_6_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_1_0_6_o;
wire    grp_shift_register_fu_278_window_adjust_1_0_6_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_2_0_6_o;
wire    grp_shift_register_fu_278_window_adjust_2_0_6_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_0_0_7_o;
wire    grp_shift_register_fu_278_window_adjust_0_0_7_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_1_0_7_o;
wire    grp_shift_register_fu_278_window_adjust_1_0_7_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_2_0_7_o;
wire    grp_shift_register_fu_278_window_adjust_2_0_7_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_0_2_0_o;
wire    grp_shift_register_fu_278_window_adjust_0_2_0_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_1_2_0_o;
wire    grp_shift_register_fu_278_window_adjust_1_2_0_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_2_2_0_o;
wire    grp_shift_register_fu_278_window_adjust_2_2_0_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_0_2_1_o;
wire    grp_shift_register_fu_278_window_adjust_0_2_1_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_1_2_1_o;
wire    grp_shift_register_fu_278_window_adjust_1_2_1_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_2_2_1_o;
wire    grp_shift_register_fu_278_window_adjust_2_2_1_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_0_2_2_o;
wire    grp_shift_register_fu_278_window_adjust_0_2_2_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_1_2_2_o;
wire    grp_shift_register_fu_278_window_adjust_1_2_2_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_2_2_2_o;
wire    grp_shift_register_fu_278_window_adjust_2_2_2_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_0_2_3_o;
wire    grp_shift_register_fu_278_window_adjust_0_2_3_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_1_2_3_o;
wire    grp_shift_register_fu_278_window_adjust_1_2_3_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_2_2_3_o;
wire    grp_shift_register_fu_278_window_adjust_2_2_3_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_0_2_4_o;
wire    grp_shift_register_fu_278_window_adjust_0_2_4_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_1_2_4_o;
wire    grp_shift_register_fu_278_window_adjust_1_2_4_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_2_2_4_o;
wire    grp_shift_register_fu_278_window_adjust_2_2_4_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_0_2_5_o;
wire    grp_shift_register_fu_278_window_adjust_0_2_5_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_1_2_5_o;
wire    grp_shift_register_fu_278_window_adjust_1_2_5_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_2_2_5_o;
wire    grp_shift_register_fu_278_window_adjust_2_2_5_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_0_2_6_o;
wire    grp_shift_register_fu_278_window_adjust_0_2_6_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_1_2_6_o;
wire    grp_shift_register_fu_278_window_adjust_1_2_6_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_2_2_6_o;
wire    grp_shift_register_fu_278_window_adjust_2_2_6_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_0_2_7_o;
wire    grp_shift_register_fu_278_window_adjust_0_2_7_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_1_2_7_o;
wire    grp_shift_register_fu_278_window_adjust_1_2_7_o_ap_vld;
wire   [9:0] grp_shift_register_fu_278_window_adjust_2_2_7_o;
wire    grp_shift_register_fu_278_window_adjust_2_2_7_o_ap_vld;
wire   [79:0] grp_shift_register_fu_278_ap_return;
reg    grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_shift_register_fu_278_ap_start_reg;
reg   [5:0] ap_NS_fsm;
wire    ap_NS_fsm_state4;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [10:0] row_fu_148;
wire   [10:0] row_3_fu_415_p2;
reg    ap_block_state6;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 window_adjust_0_0_0 = 10'd0;
#0 window_adjust_0_2_0 = 10'd0;
#0 window_adjust_1_0_0 = 10'd0;
#0 window_adjust_1_2_0 = 10'd0;
#0 window_adjust_2_0_0 = 10'd0;
#0 window_adjust_2_2_0 = 10'd0;
#0 window_adjust_0_0_1 = 10'd0;
#0 window_adjust_0_2_1 = 10'd0;
#0 window_adjust_1_0_1 = 10'd0;
#0 window_adjust_1_2_1 = 10'd0;
#0 window_adjust_2_0_1 = 10'd0;
#0 window_adjust_2_2_1 = 10'd0;
#0 window_adjust_0_0_2 = 10'd0;
#0 window_adjust_0_2_2 = 10'd0;
#0 window_adjust_1_0_2 = 10'd0;
#0 window_adjust_1_2_2 = 10'd0;
#0 window_adjust_2_0_2 = 10'd0;
#0 window_adjust_2_2_2 = 10'd0;
#0 window_adjust_0_0_3 = 10'd0;
#0 window_adjust_0_2_3 = 10'd0;
#0 window_adjust_1_0_3 = 10'd0;
#0 window_adjust_1_2_3 = 10'd0;
#0 window_adjust_2_0_3 = 10'd0;
#0 window_adjust_2_2_3 = 10'd0;
#0 window_adjust_0_0_4 = 10'd0;
#0 window_adjust_0_2_4 = 10'd0;
#0 window_adjust_1_0_4 = 10'd0;
#0 window_adjust_1_2_4 = 10'd0;
#0 window_adjust_2_0_4 = 10'd0;
#0 window_adjust_2_2_4 = 10'd0;
#0 window_adjust_0_0_5 = 10'd0;
#0 window_adjust_0_2_5 = 10'd0;
#0 window_adjust_1_0_5 = 10'd0;
#0 window_adjust_1_2_5 = 10'd0;
#0 window_adjust_2_0_5 = 10'd0;
#0 window_adjust_2_2_5 = 10'd0;
#0 window_adjust_0_0_6 = 10'd0;
#0 window_adjust_0_2_6 = 10'd0;
#0 window_adjust_1_0_6 = 10'd0;
#0 window_adjust_1_2_6 = 10'd0;
#0 window_adjust_2_0_6 = 10'd0;
#0 window_adjust_2_2_6 = 10'd0;
#0 window_adjust_0_0_7 = 10'd0;
#0 window_adjust_0_2_7 = 10'd0;
#0 window_adjust_1_0_7 = 10'd0;
#0 window_adjust_1_2_7 = 10'd0;
#0 window_adjust_2_0_7 = 10'd0;
#0 window_adjust_2_2_7 = 10'd0;
#0 grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_ap_start_reg = 1'b0;
#0 grp_shift_register_fu_278_ap_start_reg = 1'b0;
#0 row_fu_148 = 11'd0;
end

conv2d_3x3_image_filter_linebuf_0_0_RAM_AUTO_1R1W #(
    .DataWidth( 80 ),
    .AddressRange( 120 ),
    .AddressWidth( 7 ))
linebuf_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linebuf_0_0_address0),
    .ce0(linebuf_0_0_ce0),
    .we0(linebuf_0_0_we0),
    .d0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_0_d0),
    .q0(linebuf_0_0_q0),
    .address1(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_0_address1),
    .ce1(linebuf_0_0_ce1),
    .q1(linebuf_0_0_q1)
);

conv2d_3x3_image_filter_linebuf_0_0_RAM_AUTO_1R1W #(
    .DataWidth( 80 ),
    .AddressRange( 120 ),
    .AddressWidth( 7 ))
linebuf_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linebuf_1_0_address0),
    .ce0(linebuf_1_0_ce0),
    .we0(linebuf_1_0_we0),
    .d0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_0_d0),
    .q0(linebuf_1_0_q0),
    .address1(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_0_address1),
    .ce1(linebuf_1_0_ce1),
    .q1(linebuf_1_0_q1)
);

conv2d_3x3_image_filter_linebuf_0_0_RAM_AUTO_1R1W #(
    .DataWidth( 80 ),
    .AddressRange( 120 ),
    .AddressWidth( 7 ))
linebuf_2_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linebuf_2_0_address0),
    .ce0(linebuf_2_0_ce0),
    .we0(linebuf_2_0_we0),
    .d0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_0_d0),
    .q0(linebuf_2_0_q0),
    .address1(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_0_address1),
    .ce1(linebuf_2_0_ce1),
    .q1(linebuf_2_0_q1)
);

conv2d_3x3_image_filter_linebuf_0_0_RAM_AUTO_1R1W #(
    .DataWidth( 80 ),
    .AddressRange( 120 ),
    .AddressWidth( 7 ))
linebuf_1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linebuf_1_1_address0),
    .ce0(linebuf_1_1_ce0),
    .we0(linebuf_1_1_we0),
    .d0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_1_d0),
    .q0(linebuf_1_1_q0),
    .address1(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_1_address1),
    .ce1(linebuf_1_1_ce1),
    .q1(linebuf_1_1_q1)
);

conv2d_3x3_image_filter_linebuf_0_0_RAM_AUTO_1R1W #(
    .DataWidth( 80 ),
    .AddressRange( 120 ),
    .AddressWidth( 7 ))
linebuf_2_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linebuf_2_1_address0),
    .ce0(linebuf_2_1_ce0),
    .we0(linebuf_2_1_we0),
    .d0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_1_d0),
    .q0(linebuf_2_1_q0),
    .address1(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_1_address1),
    .ce1(linebuf_2_1_ce1),
    .q1(linebuf_2_1_q1)
);

conv2d_3x3_image_filter_linebuf_0_0_RAM_AUTO_1R1W #(
    .DataWidth( 80 ),
    .AddressRange( 120 ),
    .AddressWidth( 7 ))
linebuf_0_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linebuf_0_1_address0),
    .ce0(linebuf_0_1_ce0),
    .we0(linebuf_0_1_we0),
    .d0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_1_d0),
    .q0(linebuf_0_1_q0),
    .address1(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_1_address1),
    .ce1(linebuf_0_1_ce1),
    .q1(linebuf_0_1_q1)
);

conv2d_3x3_image_filter_Pipeline_VITIS_LOOP_188_2 grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_ap_start),
    .ap_done(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_ap_done),
    .ap_idle(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_ap_idle),
    .ap_ready(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_ap_ready),
    .input_r_dout(input_r_dout),
    .input_r_num_data_valid(3'd0),
    .input_r_fifo_cap(3'd0),
    .input_r_empty_n(input_r_empty_n),
    .input_r_read(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_input_r_read),
    .output_r_din(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_output_r_din),
    .output_r_num_data_valid(3'd0),
    .output_r_fifo_cap(3'd0),
    .output_r_full_n(output_r_full_n),
    .output_r_write(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_output_r_write),
    .cmp(cmp_reg_440),
    .row(row_fu_148),
    .cmp4(cmp4_reg_435),
    .window_adjust_0_0_0_i(window_adjust_0_0_0),
    .window_adjust_0_0_0_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_0_o),
    .window_adjust_0_0_0_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_0_o_ap_vld),
    .window_adjust_0_2_0_i(window_adjust_0_2_0),
    .window_adjust_0_2_0_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_0_o),
    .window_adjust_0_2_0_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_0_o_ap_vld),
    .window_adjust_1_0_0_i(window_adjust_1_0_0),
    .window_adjust_1_0_0_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_0_o),
    .window_adjust_1_0_0_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_0_o_ap_vld),
    .window_adjust_1_2_0_i(window_adjust_1_2_0),
    .window_adjust_1_2_0_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_0_o),
    .window_adjust_1_2_0_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_0_o_ap_vld),
    .window_adjust_2_0_0_i(window_adjust_2_0_0),
    .window_adjust_2_0_0_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_0_o),
    .window_adjust_2_0_0_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_0_o_ap_vld),
    .window_adjust_2_2_0_i(window_adjust_2_2_0),
    .window_adjust_2_2_0_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_0_o),
    .window_adjust_2_2_0_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_0_o_ap_vld),
    .window_adjust_0_0_1_i(window_adjust_0_0_1),
    .window_adjust_0_0_1_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_1_o),
    .window_adjust_0_0_1_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_1_o_ap_vld),
    .window_adjust_0_2_1_i(window_adjust_0_2_1),
    .window_adjust_0_2_1_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_1_o),
    .window_adjust_0_2_1_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_1_o_ap_vld),
    .window_adjust_1_0_1_i(window_adjust_1_0_1),
    .window_adjust_1_0_1_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_1_o),
    .window_adjust_1_0_1_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_1_o_ap_vld),
    .window_adjust_1_2_1_i(window_adjust_1_2_1),
    .window_adjust_1_2_1_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_1_o),
    .window_adjust_1_2_1_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_1_o_ap_vld),
    .window_adjust_2_0_1_i(window_adjust_2_0_1),
    .window_adjust_2_0_1_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_1_o),
    .window_adjust_2_0_1_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_1_o_ap_vld),
    .window_adjust_2_2_1_i(window_adjust_2_2_1),
    .window_adjust_2_2_1_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_1_o),
    .window_adjust_2_2_1_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_1_o_ap_vld),
    .window_adjust_0_0_2_i(window_adjust_0_0_2),
    .window_adjust_0_0_2_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_2_o),
    .window_adjust_0_0_2_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_2_o_ap_vld),
    .window_adjust_0_2_2_i(window_adjust_0_2_2),
    .window_adjust_0_2_2_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_2_o),
    .window_adjust_0_2_2_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_2_o_ap_vld),
    .window_adjust_1_0_2_i(window_adjust_1_0_2),
    .window_adjust_1_0_2_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_2_o),
    .window_adjust_1_0_2_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_2_o_ap_vld),
    .window_adjust_1_2_2_i(window_adjust_1_2_2),
    .window_adjust_1_2_2_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_2_o),
    .window_adjust_1_2_2_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_2_o_ap_vld),
    .window_adjust_2_0_2_i(window_adjust_2_0_2),
    .window_adjust_2_0_2_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_2_o),
    .window_adjust_2_0_2_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_2_o_ap_vld),
    .window_adjust_2_2_2_i(window_adjust_2_2_2),
    .window_adjust_2_2_2_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_2_o),
    .window_adjust_2_2_2_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_2_o_ap_vld),
    .window_adjust_0_0_3_i(window_adjust_0_0_3),
    .window_adjust_0_0_3_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_3_o),
    .window_adjust_0_0_3_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_3_o_ap_vld),
    .window_adjust_0_2_3_i(window_adjust_0_2_3),
    .window_adjust_0_2_3_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_3_o),
    .window_adjust_0_2_3_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_3_o_ap_vld),
    .window_adjust_1_0_3_i(window_adjust_1_0_3),
    .window_adjust_1_0_3_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_3_o),
    .window_adjust_1_0_3_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_3_o_ap_vld),
    .window_adjust_1_2_3_i(window_adjust_1_2_3),
    .window_adjust_1_2_3_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_3_o),
    .window_adjust_1_2_3_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_3_o_ap_vld),
    .window_adjust_2_0_3_i(window_adjust_2_0_3),
    .window_adjust_2_0_3_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_3_o),
    .window_adjust_2_0_3_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_3_o_ap_vld),
    .window_adjust_2_2_3_i(window_adjust_2_2_3),
    .window_adjust_2_2_3_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_3_o),
    .window_adjust_2_2_3_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_3_o_ap_vld),
    .window_adjust_0_0_4_i(window_adjust_0_0_4),
    .window_adjust_0_0_4_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_4_o),
    .window_adjust_0_0_4_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_4_o_ap_vld),
    .window_adjust_0_2_4_i(window_adjust_0_2_4),
    .window_adjust_0_2_4_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_4_o),
    .window_adjust_0_2_4_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_4_o_ap_vld),
    .window_adjust_1_0_4_i(window_adjust_1_0_4),
    .window_adjust_1_0_4_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_4_o),
    .window_adjust_1_0_4_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_4_o_ap_vld),
    .window_adjust_1_2_4_i(window_adjust_1_2_4),
    .window_adjust_1_2_4_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_4_o),
    .window_adjust_1_2_4_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_4_o_ap_vld),
    .window_adjust_2_0_4_i(window_adjust_2_0_4),
    .window_adjust_2_0_4_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_4_o),
    .window_adjust_2_0_4_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_4_o_ap_vld),
    .window_adjust_2_2_4_i(window_adjust_2_2_4),
    .window_adjust_2_2_4_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_4_o),
    .window_adjust_2_2_4_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_4_o_ap_vld),
    .window_adjust_0_0_5_i(window_adjust_0_0_5),
    .window_adjust_0_0_5_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_5_o),
    .window_adjust_0_0_5_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_5_o_ap_vld),
    .window_adjust_0_2_5_i(window_adjust_0_2_5),
    .window_adjust_0_2_5_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_5_o),
    .window_adjust_0_2_5_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_5_o_ap_vld),
    .window_adjust_1_0_5_i(window_adjust_1_0_5),
    .window_adjust_1_0_5_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_5_o),
    .window_adjust_1_0_5_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_5_o_ap_vld),
    .window_adjust_1_2_5_i(window_adjust_1_2_5),
    .window_adjust_1_2_5_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_5_o),
    .window_adjust_1_2_5_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_5_o_ap_vld),
    .window_adjust_2_0_5_i(window_adjust_2_0_5),
    .window_adjust_2_0_5_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_5_o),
    .window_adjust_2_0_5_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_5_o_ap_vld),
    .window_adjust_2_2_5_i(window_adjust_2_2_5),
    .window_adjust_2_2_5_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_5_o),
    .window_adjust_2_2_5_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_5_o_ap_vld),
    .window_adjust_0_0_6_i(window_adjust_0_0_6),
    .window_adjust_0_0_6_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_6_o),
    .window_adjust_0_0_6_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_6_o_ap_vld),
    .window_adjust_0_2_6_i(window_adjust_0_2_6),
    .window_adjust_0_2_6_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_6_o),
    .window_adjust_0_2_6_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_6_o_ap_vld),
    .window_adjust_1_0_6_i(window_adjust_1_0_6),
    .window_adjust_1_0_6_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_6_o),
    .window_adjust_1_0_6_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_6_o_ap_vld),
    .window_adjust_1_2_6_i(window_adjust_1_2_6),
    .window_adjust_1_2_6_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_6_o),
    .window_adjust_1_2_6_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_6_o_ap_vld),
    .window_adjust_2_0_6_i(window_adjust_2_0_6),
    .window_adjust_2_0_6_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_6_o),
    .window_adjust_2_0_6_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_6_o_ap_vld),
    .window_adjust_2_2_6_i(window_adjust_2_2_6),
    .window_adjust_2_2_6_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_6_o),
    .window_adjust_2_2_6_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_6_o_ap_vld),
    .window_adjust_0_0_7_i(window_adjust_0_0_7),
    .window_adjust_0_0_7_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_7_o),
    .window_adjust_0_0_7_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_7_o_ap_vld),
    .window_adjust_0_2_7_i(window_adjust_0_2_7),
    .window_adjust_0_2_7_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_7_o),
    .window_adjust_0_2_7_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_7_o_ap_vld),
    .window_adjust_1_0_7_i(window_adjust_1_0_7),
    .window_adjust_1_0_7_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_7_o),
    .window_adjust_1_0_7_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_7_o_ap_vld),
    .window_adjust_1_2_7_i(window_adjust_1_2_7),
    .window_adjust_1_2_7_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_7_o),
    .window_adjust_1_2_7_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_7_o_ap_vld),
    .window_adjust_2_0_7_i(window_adjust_2_0_7),
    .window_adjust_2_0_7_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_7_o),
    .window_adjust_2_0_7_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_7_o_ap_vld),
    .window_adjust_2_2_7_i(window_adjust_2_2_7),
    .window_adjust_2_2_7_o(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_7_o),
    .window_adjust_2_2_7_o_ap_vld(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_7_o_ap_vld),
    .linebuf_0_0_address0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_0_address0),
    .linebuf_0_0_ce0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_0_ce0),
    .linebuf_0_0_we0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_0_we0),
    .linebuf_0_0_d0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_0_d0),
    .linebuf_0_0_q0(linebuf_0_0_q0),
    .linebuf_0_0_address1(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_0_address1),
    .linebuf_0_0_ce1(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_0_ce1),
    .linebuf_0_0_q1(linebuf_0_0_q1),
    .linebuf_1_0_address0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_0_address0),
    .linebuf_1_0_ce0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_0_ce0),
    .linebuf_1_0_we0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_0_we0),
    .linebuf_1_0_d0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_0_d0),
    .linebuf_1_0_q0(linebuf_1_0_q0),
    .linebuf_1_0_address1(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_0_address1),
    .linebuf_1_0_ce1(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_0_ce1),
    .linebuf_1_0_q1(linebuf_1_0_q1),
    .linebuf_2_0_address0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_0_address0),
    .linebuf_2_0_ce0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_0_ce0),
    .linebuf_2_0_we0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_0_we0),
    .linebuf_2_0_d0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_0_d0),
    .linebuf_2_0_q0(linebuf_2_0_q0),
    .linebuf_2_0_address1(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_0_address1),
    .linebuf_2_0_ce1(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_0_ce1),
    .linebuf_2_0_q1(linebuf_2_0_q1),
    .linebuf_1_1_address0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_1_address0),
    .linebuf_1_1_ce0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_1_ce0),
    .linebuf_1_1_we0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_1_we0),
    .linebuf_1_1_d0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_1_d0),
    .linebuf_1_1_q0(linebuf_1_1_q0),
    .linebuf_1_1_address1(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_1_address1),
    .linebuf_1_1_ce1(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_1_ce1),
    .linebuf_1_1_q1(linebuf_1_1_q1),
    .linebuf_2_1_address0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_1_address0),
    .linebuf_2_1_ce0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_1_ce0),
    .linebuf_2_1_we0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_1_we0),
    .linebuf_2_1_d0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_1_d0),
    .linebuf_2_1_q0(linebuf_2_1_q0),
    .linebuf_2_1_address1(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_1_address1),
    .linebuf_2_1_ce1(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_1_ce1),
    .linebuf_2_1_q1(linebuf_2_1_q1),
    .linebuf_0_1_address0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_1_address0),
    .linebuf_0_1_ce0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_1_ce0),
    .linebuf_0_1_we0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_1_we0),
    .linebuf_0_1_d0(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_1_d0),
    .linebuf_0_1_q0(linebuf_0_1_q0),
    .linebuf_0_1_address1(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_1_address1),
    .linebuf_0_1_ce1(grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_1_ce1),
    .linebuf_0_1_q1(linebuf_0_1_q1)
);

conv2d_3x3_shift_register grp_shift_register_fu_278(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_shift_register_fu_278_ap_start),
    .ap_done(grp_shift_register_fu_278_ap_done),
    .ap_idle(grp_shift_register_fu_278_ap_idle),
    .ap_ready(grp_shift_register_fu_278_ap_ready),
    .row(row_fu_148),
    .linebuf_0_0_address0(grp_shift_register_fu_278_linebuf_0_0_address0),
    .linebuf_0_0_ce0(grp_shift_register_fu_278_linebuf_0_0_ce0),
    .linebuf_0_0_q0(linebuf_0_0_q0),
    .linebuf_0_1_address0(grp_shift_register_fu_278_linebuf_0_1_address0),
    .linebuf_0_1_ce0(grp_shift_register_fu_278_linebuf_0_1_ce0),
    .linebuf_0_1_q0(linebuf_0_1_q0),
    .linebuf_1_0_address0(grp_shift_register_fu_278_linebuf_1_0_address0),
    .linebuf_1_0_ce0(grp_shift_register_fu_278_linebuf_1_0_ce0),
    .linebuf_1_0_q0(linebuf_1_0_q0),
    .linebuf_1_1_address0(grp_shift_register_fu_278_linebuf_1_1_address0),
    .linebuf_1_1_ce0(grp_shift_register_fu_278_linebuf_1_1_ce0),
    .linebuf_1_1_q0(linebuf_1_1_q0),
    .linebuf_2_0_address0(grp_shift_register_fu_278_linebuf_2_0_address0),
    .linebuf_2_0_ce0(grp_shift_register_fu_278_linebuf_2_0_ce0),
    .linebuf_2_0_q0(linebuf_2_0_q0),
    .linebuf_2_1_address0(grp_shift_register_fu_278_linebuf_2_1_address0),
    .linebuf_2_1_ce0(grp_shift_register_fu_278_linebuf_2_1_ce0),
    .linebuf_2_1_q0(linebuf_2_1_q0),
    .window_adjust_0_0_0_i(window_adjust_0_0_0),
    .window_adjust_0_0_0_o(grp_shift_register_fu_278_window_adjust_0_0_0_o),
    .window_adjust_0_0_0_o_ap_vld(grp_shift_register_fu_278_window_adjust_0_0_0_o_ap_vld),
    .window_adjust_1_0_0_i(window_adjust_1_0_0),
    .window_adjust_1_0_0_o(grp_shift_register_fu_278_window_adjust_1_0_0_o),
    .window_adjust_1_0_0_o_ap_vld(grp_shift_register_fu_278_window_adjust_1_0_0_o_ap_vld),
    .window_adjust_2_0_0_i(window_adjust_2_0_0),
    .window_adjust_2_0_0_o(grp_shift_register_fu_278_window_adjust_2_0_0_o),
    .window_adjust_2_0_0_o_ap_vld(grp_shift_register_fu_278_window_adjust_2_0_0_o_ap_vld),
    .window_adjust_0_0_1_i(window_adjust_0_0_1),
    .window_adjust_0_0_1_o(grp_shift_register_fu_278_window_adjust_0_0_1_o),
    .window_adjust_0_0_1_o_ap_vld(grp_shift_register_fu_278_window_adjust_0_0_1_o_ap_vld),
    .window_adjust_1_0_1_i(window_adjust_1_0_1),
    .window_adjust_1_0_1_o(grp_shift_register_fu_278_window_adjust_1_0_1_o),
    .window_adjust_1_0_1_o_ap_vld(grp_shift_register_fu_278_window_adjust_1_0_1_o_ap_vld),
    .window_adjust_2_0_1_i(window_adjust_2_0_1),
    .window_adjust_2_0_1_o(grp_shift_register_fu_278_window_adjust_2_0_1_o),
    .window_adjust_2_0_1_o_ap_vld(grp_shift_register_fu_278_window_adjust_2_0_1_o_ap_vld),
    .window_adjust_0_0_2_i(window_adjust_0_0_2),
    .window_adjust_0_0_2_o(grp_shift_register_fu_278_window_adjust_0_0_2_o),
    .window_adjust_0_0_2_o_ap_vld(grp_shift_register_fu_278_window_adjust_0_0_2_o_ap_vld),
    .window_adjust_1_0_2_i(window_adjust_1_0_2),
    .window_adjust_1_0_2_o(grp_shift_register_fu_278_window_adjust_1_0_2_o),
    .window_adjust_1_0_2_o_ap_vld(grp_shift_register_fu_278_window_adjust_1_0_2_o_ap_vld),
    .window_adjust_2_0_2_i(window_adjust_2_0_2),
    .window_adjust_2_0_2_o(grp_shift_register_fu_278_window_adjust_2_0_2_o),
    .window_adjust_2_0_2_o_ap_vld(grp_shift_register_fu_278_window_adjust_2_0_2_o_ap_vld),
    .window_adjust_0_0_3_i(window_adjust_0_0_3),
    .window_adjust_0_0_3_o(grp_shift_register_fu_278_window_adjust_0_0_3_o),
    .window_adjust_0_0_3_o_ap_vld(grp_shift_register_fu_278_window_adjust_0_0_3_o_ap_vld),
    .window_adjust_1_0_3_i(window_adjust_1_0_3),
    .window_adjust_1_0_3_o(grp_shift_register_fu_278_window_adjust_1_0_3_o),
    .window_adjust_1_0_3_o_ap_vld(grp_shift_register_fu_278_window_adjust_1_0_3_o_ap_vld),
    .window_adjust_2_0_3_i(window_adjust_2_0_3),
    .window_adjust_2_0_3_o(grp_shift_register_fu_278_window_adjust_2_0_3_o),
    .window_adjust_2_0_3_o_ap_vld(grp_shift_register_fu_278_window_adjust_2_0_3_o_ap_vld),
    .window_adjust_0_0_4_i(window_adjust_0_0_4),
    .window_adjust_0_0_4_o(grp_shift_register_fu_278_window_adjust_0_0_4_o),
    .window_adjust_0_0_4_o_ap_vld(grp_shift_register_fu_278_window_adjust_0_0_4_o_ap_vld),
    .window_adjust_1_0_4_i(window_adjust_1_0_4),
    .window_adjust_1_0_4_o(grp_shift_register_fu_278_window_adjust_1_0_4_o),
    .window_adjust_1_0_4_o_ap_vld(grp_shift_register_fu_278_window_adjust_1_0_4_o_ap_vld),
    .window_adjust_2_0_4_i(window_adjust_2_0_4),
    .window_adjust_2_0_4_o(grp_shift_register_fu_278_window_adjust_2_0_4_o),
    .window_adjust_2_0_4_o_ap_vld(grp_shift_register_fu_278_window_adjust_2_0_4_o_ap_vld),
    .window_adjust_0_0_5_i(window_adjust_0_0_5),
    .window_adjust_0_0_5_o(grp_shift_register_fu_278_window_adjust_0_0_5_o),
    .window_adjust_0_0_5_o_ap_vld(grp_shift_register_fu_278_window_adjust_0_0_5_o_ap_vld),
    .window_adjust_1_0_5_i(window_adjust_1_0_5),
    .window_adjust_1_0_5_o(grp_shift_register_fu_278_window_adjust_1_0_5_o),
    .window_adjust_1_0_5_o_ap_vld(grp_shift_register_fu_278_window_adjust_1_0_5_o_ap_vld),
    .window_adjust_2_0_5_i(window_adjust_2_0_5),
    .window_adjust_2_0_5_o(grp_shift_register_fu_278_window_adjust_2_0_5_o),
    .window_adjust_2_0_5_o_ap_vld(grp_shift_register_fu_278_window_adjust_2_0_5_o_ap_vld),
    .window_adjust_0_0_6_i(window_adjust_0_0_6),
    .window_adjust_0_0_6_o(grp_shift_register_fu_278_window_adjust_0_0_6_o),
    .window_adjust_0_0_6_o_ap_vld(grp_shift_register_fu_278_window_adjust_0_0_6_o_ap_vld),
    .window_adjust_1_0_6_i(window_adjust_1_0_6),
    .window_adjust_1_0_6_o(grp_shift_register_fu_278_window_adjust_1_0_6_o),
    .window_adjust_1_0_6_o_ap_vld(grp_shift_register_fu_278_window_adjust_1_0_6_o_ap_vld),
    .window_adjust_2_0_6_i(window_adjust_2_0_6),
    .window_adjust_2_0_6_o(grp_shift_register_fu_278_window_adjust_2_0_6_o),
    .window_adjust_2_0_6_o_ap_vld(grp_shift_register_fu_278_window_adjust_2_0_6_o_ap_vld),
    .window_adjust_0_0_7_i(window_adjust_0_0_7),
    .window_adjust_0_0_7_o(grp_shift_register_fu_278_window_adjust_0_0_7_o),
    .window_adjust_0_0_7_o_ap_vld(grp_shift_register_fu_278_window_adjust_0_0_7_o_ap_vld),
    .window_adjust_1_0_7_i(window_adjust_1_0_7),
    .window_adjust_1_0_7_o(grp_shift_register_fu_278_window_adjust_1_0_7_o),
    .window_adjust_1_0_7_o_ap_vld(grp_shift_register_fu_278_window_adjust_1_0_7_o_ap_vld),
    .window_adjust_2_0_7_i(window_adjust_2_0_7),
    .window_adjust_2_0_7_o(grp_shift_register_fu_278_window_adjust_2_0_7_o),
    .window_adjust_2_0_7_o_ap_vld(grp_shift_register_fu_278_window_adjust_2_0_7_o_ap_vld),
    .window_adjust_0_2_0_i(window_adjust_0_2_0),
    .window_adjust_0_2_0_o(grp_shift_register_fu_278_window_adjust_0_2_0_o),
    .window_adjust_0_2_0_o_ap_vld(grp_shift_register_fu_278_window_adjust_0_2_0_o_ap_vld),
    .window_adjust_1_2_0_i(window_adjust_1_2_0),
    .window_adjust_1_2_0_o(grp_shift_register_fu_278_window_adjust_1_2_0_o),
    .window_adjust_1_2_0_o_ap_vld(grp_shift_register_fu_278_window_adjust_1_2_0_o_ap_vld),
    .window_adjust_2_2_0_i(window_adjust_2_2_0),
    .window_adjust_2_2_0_o(grp_shift_register_fu_278_window_adjust_2_2_0_o),
    .window_adjust_2_2_0_o_ap_vld(grp_shift_register_fu_278_window_adjust_2_2_0_o_ap_vld),
    .window_adjust_0_2_1_i(window_adjust_0_2_1),
    .window_adjust_0_2_1_o(grp_shift_register_fu_278_window_adjust_0_2_1_o),
    .window_adjust_0_2_1_o_ap_vld(grp_shift_register_fu_278_window_adjust_0_2_1_o_ap_vld),
    .window_adjust_1_2_1_i(window_adjust_1_2_1),
    .window_adjust_1_2_1_o(grp_shift_register_fu_278_window_adjust_1_2_1_o),
    .window_adjust_1_2_1_o_ap_vld(grp_shift_register_fu_278_window_adjust_1_2_1_o_ap_vld),
    .window_adjust_2_2_1_i(window_adjust_2_2_1),
    .window_adjust_2_2_1_o(grp_shift_register_fu_278_window_adjust_2_2_1_o),
    .window_adjust_2_2_1_o_ap_vld(grp_shift_register_fu_278_window_adjust_2_2_1_o_ap_vld),
    .window_adjust_0_2_2_i(window_adjust_0_2_2),
    .window_adjust_0_2_2_o(grp_shift_register_fu_278_window_adjust_0_2_2_o),
    .window_adjust_0_2_2_o_ap_vld(grp_shift_register_fu_278_window_adjust_0_2_2_o_ap_vld),
    .window_adjust_1_2_2_i(window_adjust_1_2_2),
    .window_adjust_1_2_2_o(grp_shift_register_fu_278_window_adjust_1_2_2_o),
    .window_adjust_1_2_2_o_ap_vld(grp_shift_register_fu_278_window_adjust_1_2_2_o_ap_vld),
    .window_adjust_2_2_2_i(window_adjust_2_2_2),
    .window_adjust_2_2_2_o(grp_shift_register_fu_278_window_adjust_2_2_2_o),
    .window_adjust_2_2_2_o_ap_vld(grp_shift_register_fu_278_window_adjust_2_2_2_o_ap_vld),
    .window_adjust_0_2_3_i(window_adjust_0_2_3),
    .window_adjust_0_2_3_o(grp_shift_register_fu_278_window_adjust_0_2_3_o),
    .window_adjust_0_2_3_o_ap_vld(grp_shift_register_fu_278_window_adjust_0_2_3_o_ap_vld),
    .window_adjust_1_2_3_i(window_adjust_1_2_3),
    .window_adjust_1_2_3_o(grp_shift_register_fu_278_window_adjust_1_2_3_o),
    .window_adjust_1_2_3_o_ap_vld(grp_shift_register_fu_278_window_adjust_1_2_3_o_ap_vld),
    .window_adjust_2_2_3_i(window_adjust_2_2_3),
    .window_adjust_2_2_3_o(grp_shift_register_fu_278_window_adjust_2_2_3_o),
    .window_adjust_2_2_3_o_ap_vld(grp_shift_register_fu_278_window_adjust_2_2_3_o_ap_vld),
    .window_adjust_0_2_4_i(window_adjust_0_2_4),
    .window_adjust_0_2_4_o(grp_shift_register_fu_278_window_adjust_0_2_4_o),
    .window_adjust_0_2_4_o_ap_vld(grp_shift_register_fu_278_window_adjust_0_2_4_o_ap_vld),
    .window_adjust_1_2_4_i(window_adjust_1_2_4),
    .window_adjust_1_2_4_o(grp_shift_register_fu_278_window_adjust_1_2_4_o),
    .window_adjust_1_2_4_o_ap_vld(grp_shift_register_fu_278_window_adjust_1_2_4_o_ap_vld),
    .window_adjust_2_2_4_i(window_adjust_2_2_4),
    .window_adjust_2_2_4_o(grp_shift_register_fu_278_window_adjust_2_2_4_o),
    .window_adjust_2_2_4_o_ap_vld(grp_shift_register_fu_278_window_adjust_2_2_4_o_ap_vld),
    .window_adjust_0_2_5_i(window_adjust_0_2_5),
    .window_adjust_0_2_5_o(grp_shift_register_fu_278_window_adjust_0_2_5_o),
    .window_adjust_0_2_5_o_ap_vld(grp_shift_register_fu_278_window_adjust_0_2_5_o_ap_vld),
    .window_adjust_1_2_5_i(window_adjust_1_2_5),
    .window_adjust_1_2_5_o(grp_shift_register_fu_278_window_adjust_1_2_5_o),
    .window_adjust_1_2_5_o_ap_vld(grp_shift_register_fu_278_window_adjust_1_2_5_o_ap_vld),
    .window_adjust_2_2_5_i(window_adjust_2_2_5),
    .window_adjust_2_2_5_o(grp_shift_register_fu_278_window_adjust_2_2_5_o),
    .window_adjust_2_2_5_o_ap_vld(grp_shift_register_fu_278_window_adjust_2_2_5_o_ap_vld),
    .window_adjust_0_2_6_i(window_adjust_0_2_6),
    .window_adjust_0_2_6_o(grp_shift_register_fu_278_window_adjust_0_2_6_o),
    .window_adjust_0_2_6_o_ap_vld(grp_shift_register_fu_278_window_adjust_0_2_6_o_ap_vld),
    .window_adjust_1_2_6_i(window_adjust_1_2_6),
    .window_adjust_1_2_6_o(grp_shift_register_fu_278_window_adjust_1_2_6_o),
    .window_adjust_1_2_6_o_ap_vld(grp_shift_register_fu_278_window_adjust_1_2_6_o_ap_vld),
    .window_adjust_2_2_6_i(window_adjust_2_2_6),
    .window_adjust_2_2_6_o(grp_shift_register_fu_278_window_adjust_2_2_6_o),
    .window_adjust_2_2_6_o_ap_vld(grp_shift_register_fu_278_window_adjust_2_2_6_o_ap_vld),
    .window_adjust_0_2_7_i(window_adjust_0_2_7),
    .window_adjust_0_2_7_o(grp_shift_register_fu_278_window_adjust_0_2_7_o),
    .window_adjust_0_2_7_o_ap_vld(grp_shift_register_fu_278_window_adjust_0_2_7_o_ap_vld),
    .window_adjust_1_2_7_i(window_adjust_1_2_7),
    .window_adjust_1_2_7_o(grp_shift_register_fu_278_window_adjust_1_2_7_o),
    .window_adjust_1_2_7_o_ap_vld(grp_shift_register_fu_278_window_adjust_1_2_7_o_ap_vld),
    .window_adjust_2_2_7_i(window_adjust_2_2_7),
    .window_adjust_2_2_7_o(grp_shift_register_fu_278_window_adjust_2_2_7_o),
    .window_adjust_2_2_7_o_ap_vld(grp_shift_register_fu_278_window_adjust_2_2_7_o_ap_vld),
    .ap_return(grp_shift_register_fu_278_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6) & (cmp4_reg_435 == 1'd1) & (cmp_reg_440 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_ap_start_reg <= 1'b1;
        end else if ((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_ap_ready == 1'b1)) begin
            grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_shift_register_fu_278_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state4) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_shift_register_fu_278_ap_start_reg <= 1'b1;
        end else if ((grp_shift_register_fu_278_ap_ready == 1'b1)) begin
            grp_shift_register_fu_278_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        row_fu_148 <= 11'd0;
    end else if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6))) begin
        row_fu_148 <= row_3_fu_415_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_0_0_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_0_0 <= grp_shift_register_fu_278_window_adjust_0_0_0_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_0_0 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_0_0_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_0_1 <= grp_shift_register_fu_278_window_adjust_0_0_1_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_0_1 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_0_0_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_0_2 <= grp_shift_register_fu_278_window_adjust_0_0_2_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_0_2 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_0_0_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_0_3 <= grp_shift_register_fu_278_window_adjust_0_0_3_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_0_3 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_0_0_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_0_4 <= grp_shift_register_fu_278_window_adjust_0_0_4_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_0_4 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_0_0_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_0_5 <= grp_shift_register_fu_278_window_adjust_0_0_5_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_0_5 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_5_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_0_0_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_0_6 <= grp_shift_register_fu_278_window_adjust_0_0_6_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_0_6 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_0_0_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_0_7 <= grp_shift_register_fu_278_window_adjust_0_0_7_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_0_7 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_0_7_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_0_2_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_2_0 <= grp_shift_register_fu_278_window_adjust_0_2_0_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_2_0 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_0_2_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_2_1 <= grp_shift_register_fu_278_window_adjust_0_2_1_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_2_1 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_0_2_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_2_2 <= grp_shift_register_fu_278_window_adjust_0_2_2_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_2_2 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_0_2_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_2_3 <= grp_shift_register_fu_278_window_adjust_0_2_3_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_2_3 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_0_2_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_2_4 <= grp_shift_register_fu_278_window_adjust_0_2_4_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_2_4 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_0_2_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_2_5 <= grp_shift_register_fu_278_window_adjust_0_2_5_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_2_5 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_5_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_0_2_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_2_6 <= grp_shift_register_fu_278_window_adjust_0_2_6_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_2_6 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_0_2_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_0_2_7 <= grp_shift_register_fu_278_window_adjust_0_2_7_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_0_2_7 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_0_2_7_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_1_0_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_0_0 <= grp_shift_register_fu_278_window_adjust_1_0_0_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_0_0 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_1_0_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_0_1 <= grp_shift_register_fu_278_window_adjust_1_0_1_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_0_1 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_1_0_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_0_2 <= grp_shift_register_fu_278_window_adjust_1_0_2_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_0_2 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_1_0_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_0_3 <= grp_shift_register_fu_278_window_adjust_1_0_3_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_0_3 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_1_0_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_0_4 <= grp_shift_register_fu_278_window_adjust_1_0_4_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_0_4 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_1_0_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_0_5 <= grp_shift_register_fu_278_window_adjust_1_0_5_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_0_5 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_5_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_1_0_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_0_6 <= grp_shift_register_fu_278_window_adjust_1_0_6_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_0_6 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_1_0_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_0_7 <= grp_shift_register_fu_278_window_adjust_1_0_7_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_0_7 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_0_7_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_1_2_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_2_0 <= grp_shift_register_fu_278_window_adjust_1_2_0_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_2_0 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_1_2_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_2_1 <= grp_shift_register_fu_278_window_adjust_1_2_1_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_2_1 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_1_2_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_2_2 <= grp_shift_register_fu_278_window_adjust_1_2_2_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_2_2 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_1_2_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_2_3 <= grp_shift_register_fu_278_window_adjust_1_2_3_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_2_3 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_1_2_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_2_4 <= grp_shift_register_fu_278_window_adjust_1_2_4_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_2_4 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_1_2_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_2_5 <= grp_shift_register_fu_278_window_adjust_1_2_5_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_2_5 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_5_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_1_2_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_2_6 <= grp_shift_register_fu_278_window_adjust_1_2_6_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_2_6 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_1_2_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_1_2_7 <= grp_shift_register_fu_278_window_adjust_1_2_7_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_1_2_7 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_1_2_7_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_2_0_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_0_0 <= grp_shift_register_fu_278_window_adjust_2_0_0_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_0_0 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_2_0_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_0_1 <= grp_shift_register_fu_278_window_adjust_2_0_1_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_0_1 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_2_0_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_0_2 <= grp_shift_register_fu_278_window_adjust_2_0_2_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_0_2 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_2_0_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_0_3 <= grp_shift_register_fu_278_window_adjust_2_0_3_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_0_3 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_2_0_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_0_4 <= grp_shift_register_fu_278_window_adjust_2_0_4_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_0_4 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_2_0_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_0_5 <= grp_shift_register_fu_278_window_adjust_2_0_5_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_0_5 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_5_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_2_0_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_0_6 <= grp_shift_register_fu_278_window_adjust_2_0_6_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_0_6 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_2_0_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_0_7 <= grp_shift_register_fu_278_window_adjust_2_0_7_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_0_7 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_0_7_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_2_2_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_2_0 <= grp_shift_register_fu_278_window_adjust_2_2_0_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_2_0 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_2_2_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_2_1 <= grp_shift_register_fu_278_window_adjust_2_2_1_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_2_1 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_2_2_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_2_2 <= grp_shift_register_fu_278_window_adjust_2_2_2_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_2_2 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_2_2_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_2_3 <= grp_shift_register_fu_278_window_adjust_2_2_3_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_2_3 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_2_2_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_2_4 <= grp_shift_register_fu_278_window_adjust_2_2_4_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_2_4 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_2_2_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_2_5 <= grp_shift_register_fu_278_window_adjust_2_2_5_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_2_5 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_5_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_2_2_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_2_6 <= grp_shift_register_fu_278_window_adjust_2_2_6_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_2_6 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_shift_register_fu_278_window_adjust_2_2_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        window_adjust_2_2_7 <= grp_shift_register_fu_278_window_adjust_2_2_7_o;
    end else if (((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        window_adjust_2_2_7 <= grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_window_adjust_2_2_7_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmp4_reg_435 <= cmp4_fu_401_p2;
        cmp_reg_440 <= cmp_fu_408_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state6)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6) & (cmp4_reg_435 == 1'd1) & (cmp_reg_440 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6) & (cmp4_reg_435 == 1'd1) & (cmp_reg_440 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_r_read = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_input_r_read;
    end else begin
        input_r_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_0_0_address0 = grp_shift_register_fu_278_linebuf_0_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_0_0_address0 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_0_address0;
    end else begin
        linebuf_0_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_0_0_ce0 = grp_shift_register_fu_278_linebuf_0_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_0_0_ce0 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_0_ce0;
    end else begin
        linebuf_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_0_0_ce1 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_0_ce1;
    end else begin
        linebuf_0_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_0_0_we0 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_0_we0;
    end else begin
        linebuf_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_0_1_address0 = grp_shift_register_fu_278_linebuf_0_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_0_1_address0 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_1_address0;
    end else begin
        linebuf_0_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_0_1_ce0 = grp_shift_register_fu_278_linebuf_0_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_0_1_ce0 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_1_ce0;
    end else begin
        linebuf_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_0_1_ce1 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_1_ce1;
    end else begin
        linebuf_0_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_0_1_we0 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_0_1_we0;
    end else begin
        linebuf_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_1_0_address0 = grp_shift_register_fu_278_linebuf_1_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_1_0_address0 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_0_address0;
    end else begin
        linebuf_1_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_1_0_ce0 = grp_shift_register_fu_278_linebuf_1_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_1_0_ce0 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_0_ce0;
    end else begin
        linebuf_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_1_0_ce1 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_0_ce1;
    end else begin
        linebuf_1_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_1_0_we0 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_0_we0;
    end else begin
        linebuf_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_1_1_address0 = grp_shift_register_fu_278_linebuf_1_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_1_1_address0 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_1_address0;
    end else begin
        linebuf_1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_1_1_ce0 = grp_shift_register_fu_278_linebuf_1_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_1_1_ce0 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_1_ce0;
    end else begin
        linebuf_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_1_1_ce1 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_1_ce1;
    end else begin
        linebuf_1_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_1_1_we0 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_1_1_we0;
    end else begin
        linebuf_1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_2_0_address0 = grp_shift_register_fu_278_linebuf_2_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_2_0_address0 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_0_address0;
    end else begin
        linebuf_2_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_2_0_ce0 = grp_shift_register_fu_278_linebuf_2_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_2_0_ce0 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_0_ce0;
    end else begin
        linebuf_2_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_2_0_ce1 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_0_ce1;
    end else begin
        linebuf_2_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_2_0_we0 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_0_we0;
    end else begin
        linebuf_2_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_2_1_address0 = grp_shift_register_fu_278_linebuf_2_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_2_1_address0 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_1_address0;
    end else begin
        linebuf_2_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linebuf_2_1_ce0 = grp_shift_register_fu_278_linebuf_2_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_2_1_ce0 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_1_ce0;
    end else begin
        linebuf_2_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_2_1_ce1 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_1_ce1;
    end else begin
        linebuf_2_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        linebuf_2_1_we0 = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_linebuf_2_1_we0;
    end else begin
        linebuf_2_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (cmp_reg_440 == 1'd1))) begin
        output_r_blk_n = output_r_full_n;
    end else begin
        output_r_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6) & (cmp_reg_440 == 1'd1))) begin
        output_r_din = grp_shift_register_fu_278_ap_return;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        output_r_din = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_output_r_din;
    end else begin
        output_r_din = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_output_r_din;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6) & (cmp_reg_440 == 1'd1))) begin
        output_r_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        output_r_write = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_output_r_write;
    end else begin
        output_r_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6) & (cmp4_reg_435 == 1'd1) & (cmp_reg_440 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6) & (cmp4_reg_435 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_NS_fsm_state4 = ap_NS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state6 = ((output_r_full_n == 1'b0) & (cmp_reg_440 == 1'd1));
end

assign cmp4_fu_401_p2 = ((row_fu_148 == 11'd1080) ? 1'b1 : 1'b0);

assign cmp_fu_408_p2 = ((row_fu_148 != 11'd0) ? 1'b1 : 1'b0);

assign grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_ap_start = grp_image_filter_Pipeline_VITIS_LOOP_188_2_fu_159_ap_start_reg;

assign grp_shift_register_fu_278_ap_start = grp_shift_register_fu_278_ap_start_reg;

assign row_3_fu_415_p2 = (row_fu_148 + 11'd1);

endmodule //conv2d_3x3_image_filter
