// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module conv2d_3x3_data_unpacket (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        data_in_TVALID,
        input_r_din,
        input_r_num_data_valid,
        input_r_fifo_cap,
        input_r_full_n,
        input_r_write,
        data_in_TDATA,
        data_in_TREADY,
        data_in_TKEEP,
        data_in_TSTRB,
        data_in_TLAST
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   data_in_TVALID;
output  [79:0] input_r_din;
input  [2:0] input_r_num_data_valid;
input  [2:0] input_r_fifo_cap;
input   input_r_full_n;
output   input_r_write;
input  [63:0] data_in_TDATA;
output   data_in_TREADY;
input  [7:0] data_in_TKEEP;
input  [7:0] data_in_TSTRB;
input  [0:0] data_in_TLAST;

reg ap_idle;
reg[79:0] input_r_din;
reg input_r_write;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln134_fu_165_p2;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state5;
reg   [0:0] icmp_ln144_3_reg_372;
reg    ap_block_state5_pp0_stage4_iter0;
reg    data_in_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    input_r_blk_n;
reg   [0:0] icmp_ln144_reg_345;
reg   [0:0] icmp_ln144_1_reg_354;
reg   [0:0] icmp_ln144_2_reg_363;
reg   [31:0] output_cnt_2_reg_103;
reg   [31:0] output_cnt_4_reg_113;
reg   [31:0] output_cnt_6_reg_124;
reg   [18:0] i_2_reg_325;
reg   [31:0] output_cnt_9_reg_330;
reg   [0:0] icmp_ln134_reg_336;
reg   [63:0] p_0_reg_340;
wire   [0:0] icmp_ln144_fu_171_p2;
reg   [47:0] tmp_12_reg_349;
reg    ap_block_state2_pp0_stage1_iter0;
wire   [0:0] icmp_ln144_1_fu_205_p2;
reg   [31:0] tmp_14_reg_358;
reg    ap_block_state3_pp0_stage2_iter0;
wire   [0:0] icmp_ln144_2_fu_240_p2;
reg   [15:0] tmp_16_reg_367;
reg    ap_block_state4_pp0_stage3_iter0;
wire   [0:0] icmp_ln144_3_fu_275_p2;
reg   [31:0] ap_phi_mux_output_cnt_2_phi_fu_106_p4;
wire   [31:0] output_cnt_10_fu_189_p2;
reg   [31:0] ap_phi_reg_pp0_iter0_output_cnt_2_reg_103;
reg   [31:0] ap_phi_mux_output_cnt_4_phi_fu_116_p4;
wire   [31:0] output_cnt_11_fu_223_p2;
wire   [31:0] ap_phi_reg_pp0_iter0_output_cnt_4_reg_113;
reg   [31:0] ap_phi_mux_output_cnt_6_phi_fu_127_p4;
wire   [31:0] output_cnt_12_fu_258_p2;
wire   [31:0] ap_phi_reg_pp0_iter0_output_cnt_6_reg_124;
reg   [31:0] ap_phi_mux_output_cnt_8_phi_fu_138_p4;
wire   [31:0] output_cnt_13_fu_289_p2;
wire   [31:0] ap_phi_reg_pp0_iter0_output_cnt_8_reg_135;
reg   [18:0] i_fu_76;
wire   [18:0] i_3_fu_296_p2;
wire    ap_loop_init;
reg   [18:0] ap_sig_allocacmp_i_2;
reg   [31:0] output_cnt_fu_80;
reg   [31:0] ap_sig_allocacmp_output_cnt_9;
wire   [79:0] tmp_fu_181_p3;
wire   [79:0] tmp_s_fu_215_p3;
wire   [79:0] tmp_56_fu_250_p3;
wire   [79:0] tmp_57_fu_281_p3;
wire   [15:0] trunc_ln143_fu_177_p1;
wire   [31:0] trunc_ln143_1_fu_211_p1;
wire   [47:0] trunc_ln143_2_fu_246_p1;
wire    ap_continue_int;
reg    ap_done_int;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_start_int;
wire    regslice_both_data_in_V_data_V_U_apdone_blk;
wire   [63:0] data_in_TDATA_int_regslice;
wire    data_in_TVALID_int_regslice;
reg    data_in_TREADY_int_regslice;
wire    regslice_both_data_in_V_data_V_U_ack_in;
wire    regslice_both_data_in_V_keep_V_U_apdone_blk;
wire   [7:0] data_in_TKEEP_int_regslice;
wire    regslice_both_data_in_V_keep_V_U_vld_out;
wire    regslice_both_data_in_V_keep_V_U_ack_in;
wire    regslice_both_data_in_V_strb_V_U_apdone_blk;
wire   [7:0] data_in_TSTRB_int_regslice;
wire    regslice_both_data_in_V_strb_V_U_vld_out;
wire    regslice_both_data_in_V_strb_V_U_ack_in;
wire    regslice_both_data_in_V_last_V_U_apdone_blk;
wire   [0:0] data_in_TLAST_int_regslice;
wire    regslice_both_data_in_V_last_V_U_vld_out;
wire    regslice_both_data_in_V_last_V_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_done_reg = 1'b0;
#0 i_fu_76 = 19'd0;
#0 output_cnt_fu_80 = 32'd0;
end

conv2d_3x3_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

conv2d_3x3_regslice_both #(
    .DataWidth( 64 ))
regslice_both_data_in_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(data_in_TDATA),
    .vld_in(data_in_TVALID),
    .ack_in(regslice_both_data_in_V_data_V_U_ack_in),
    .data_out(data_in_TDATA_int_regslice),
    .vld_out(data_in_TVALID_int_regslice),
    .ack_out(data_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_data_in_V_data_V_U_apdone_blk)
);

conv2d_3x3_regslice_both #(
    .DataWidth( 8 ))
regslice_both_data_in_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(data_in_TKEEP),
    .vld_in(data_in_TVALID),
    .ack_in(regslice_both_data_in_V_keep_V_U_ack_in),
    .data_out(data_in_TKEEP_int_regslice),
    .vld_out(regslice_both_data_in_V_keep_V_U_vld_out),
    .ack_out(data_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_data_in_V_keep_V_U_apdone_blk)
);

conv2d_3x3_regslice_both #(
    .DataWidth( 8 ))
regslice_both_data_in_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(data_in_TSTRB),
    .vld_in(data_in_TVALID),
    .ack_in(regslice_both_data_in_V_strb_V_U_ack_in),
    .data_out(data_in_TSTRB_int_regslice),
    .vld_out(regslice_both_data_in_V_strb_V_U_vld_out),
    .ack_out(data_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_data_in_V_strb_V_U_apdone_blk)
);

conv2d_3x3_regslice_both #(
    .DataWidth( 1 ))
regslice_both_data_in_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(data_in_TLAST),
    .vld_in(data_in_TVALID),
    .ack_in(regslice_both_data_in_V_last_V_U_ack_in),
    .data_out(data_in_TLAST_int_regslice),
    .vld_out(regslice_both_data_in_V_last_V_U_vld_out),
    .ack_out(data_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_data_in_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        i_fu_76 <= 19'd0;
    end else if (((1'b0 == ap_block_state5_pp0_stage4_iter0) & (1'b1 == ap_CS_fsm_state5))) begin
        i_fu_76 <= i_3_fu_296_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        if ((icmp_ln144_reg_345 == 1'd1)) begin
            output_cnt_2_reg_103 <= output_cnt_10_fu_189_p2;
        end else if ((1'b1 == 1'b1)) begin
            output_cnt_2_reg_103 <= ap_phi_reg_pp0_iter0_output_cnt_2_reg_103;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3))) begin
        if ((icmp_ln144_1_reg_354 == 1'd0)) begin
            output_cnt_4_reg_113 <= output_cnt_2_reg_103;
        end else if ((icmp_ln144_1_reg_354 == 1'd1)) begin
            output_cnt_4_reg_113 <= output_cnt_11_fu_223_p2;
        end else if (~(icmp_ln134_reg_336 == 1'd0)) begin
            output_cnt_4_reg_113 <= ap_phi_reg_pp0_iter0_output_cnt_4_reg_113;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state4_pp0_stage3_iter0) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((icmp_ln144_2_reg_363 == 1'd0)) begin
            output_cnt_6_reg_124 <= output_cnt_4_reg_113;
        end else if ((icmp_ln144_2_reg_363 == 1'd1)) begin
            output_cnt_6_reg_124 <= output_cnt_12_fu_258_p2;
        end else if (~(icmp_ln134_reg_336 == 1'd0)) begin
            output_cnt_6_reg_124 <= ap_phi_reg_pp0_iter0_output_cnt_6_reg_124;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        output_cnt_fu_80 <= 32'd0;
    end else if (((1'b0 == ap_block_state5_pp0_stage4_iter0) & (1'b1 == ap_CS_fsm_state5))) begin
        output_cnt_fu_80 <= ap_phi_mux_output_cnt_8_phi_fu_138_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln134_fu_165_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln144_fu_171_p2 == 1'd0))) begin
        ap_phi_reg_pp0_iter0_output_cnt_2_reg_103 <= ap_sig_allocacmp_output_cnt_9;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        i_2_reg_325 <= ap_sig_allocacmp_i_2;
        icmp_ln134_reg_336 <= icmp_ln134_fu_165_p2;
        icmp_ln144_reg_345 <= icmp_ln144_fu_171_p2;
        output_cnt_9_reg_330 <= ap_sig_allocacmp_output_cnt_9;
        p_0_reg_340 <= data_in_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_ln144_1_reg_354 <= icmp_ln144_1_fu_205_p2;
        tmp_12_reg_349 <= {{data_in_TDATA_int_regslice[63:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_ln144_2_reg_363 <= icmp_ln144_2_fu_240_p2;
        tmp_14_reg_358 <= {{data_in_TDATA_int_regslice[63:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state4_pp0_stage3_iter0) & (1'b1 == ap_CS_fsm_state4))) begin
        icmp_ln144_3_reg_372 <= icmp_ln144_3_fu_275_p2;
        tmp_16_reg_367 <= {{data_in_TDATA_int_regslice[63:48]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_pp0_stage1_iter0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3_pp0_stage2_iter0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state4_pp0_stage3_iter0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state5_pp0_stage4_iter0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln134_fu_165_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln144_reg_345 == 1'd1)) begin
        ap_phi_mux_output_cnt_2_phi_fu_106_p4 = output_cnt_10_fu_189_p2;
    end else begin
        ap_phi_mux_output_cnt_2_phi_fu_106_p4 = ap_phi_reg_pp0_iter0_output_cnt_2_reg_103;
    end
end

always @ (*) begin
    if ((icmp_ln144_1_reg_354 == 1'd0)) begin
        ap_phi_mux_output_cnt_4_phi_fu_116_p4 = output_cnt_2_reg_103;
    end else if ((icmp_ln144_1_reg_354 == 1'd1)) begin
        ap_phi_mux_output_cnt_4_phi_fu_116_p4 = output_cnt_11_fu_223_p2;
    end else begin
        ap_phi_mux_output_cnt_4_phi_fu_116_p4 = ap_phi_reg_pp0_iter0_output_cnt_4_reg_113;
    end
end

always @ (*) begin
    if ((icmp_ln144_2_reg_363 == 1'd0)) begin
        ap_phi_mux_output_cnt_6_phi_fu_127_p4 = output_cnt_4_reg_113;
    end else if ((icmp_ln144_2_reg_363 == 1'd1)) begin
        ap_phi_mux_output_cnt_6_phi_fu_127_p4 = output_cnt_12_fu_258_p2;
    end else begin
        ap_phi_mux_output_cnt_6_phi_fu_127_p4 = ap_phi_reg_pp0_iter0_output_cnt_6_reg_124;
    end
end

always @ (*) begin
    if ((icmp_ln144_3_reg_372 == 1'd0)) begin
        ap_phi_mux_output_cnt_8_phi_fu_138_p4 = output_cnt_6_reg_124;
    end else if ((icmp_ln144_3_reg_372 == 1'd1)) begin
        ap_phi_mux_output_cnt_8_phi_fu_138_p4 = output_cnt_13_fu_289_p2;
    end else begin
        ap_phi_mux_output_cnt_8_phi_fu_138_p4 = ap_phi_reg_pp0_iter0_output_cnt_8_reg_135;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state5_pp0_stage4_iter0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 19'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_76;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_output_cnt_9 = 32'd0;
    end else begin
        ap_sig_allocacmp_output_cnt_9 = output_cnt_fu_80;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | (~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0)) & (icmp_ln134_fu_165_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        data_in_TDATA_blk_n = data_in_TVALID_int_regslice;
    end else begin
        data_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state5_pp0_stage4_iter0) & (1'b1 == ap_CS_fsm_state5)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln134_fu_165_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state4_pp0_stage3_iter0) & (1'b1 == ap_CS_fsm_state4)) | ((1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3)) | ((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2)))) begin
        data_in_TREADY_int_regslice = 1'b1;
    end else begin
        data_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln144_reg_345 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln144_2_reg_363 == 1'd1)) | ((icmp_ln144_3_reg_372 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln144_1_reg_354 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        input_r_blk_n = input_r_full_n;
    end else begin
        input_r_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln144_3_reg_372 == 1'd1) & (1'b0 == ap_block_state5_pp0_stage4_iter0) & (1'b1 == ap_CS_fsm_state5))) begin
        input_r_din = tmp_57_fu_281_p3;
    end else if (((1'b0 == ap_block_state4_pp0_stage3_iter0) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln144_2_reg_363 == 1'd1))) begin
        input_r_din = tmp_56_fu_250_p3;
    end else if (((icmp_ln144_1_reg_354 == 1'd1) & (1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3))) begin
        input_r_din = tmp_s_fu_215_p3;
    end else if (((icmp_ln144_reg_345 == 1'd1) & (1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        input_r_din = tmp_fu_181_p3;
    end else begin
        input_r_din = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln144_reg_345 == 1'd1) & (1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln144_3_reg_372 == 1'd1) & (1'b0 == ap_block_state5_pp0_stage4_iter0) & (1'b1 == ap_CS_fsm_state5)) | ((1'b0 == ap_block_state4_pp0_stage3_iter0) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln144_2_reg_363 == 1'd1)) | ((icmp_ln144_1_reg_354 == 1'd1) & (1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3)))) begin
        input_r_write = 1'b1;
    end else begin
        input_r_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln134_fu_165_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_pp0_stage3_iter0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b0 == ap_block_state5_pp0_stage4_iter0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((data_in_TVALID_int_regslice == 1'b0) & (icmp_ln134_fu_165_p2 == 1'd1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((data_in_TVALID_int_regslice == 1'b0) | ((icmp_ln144_reg_345 == 1'd1) & (input_r_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0 = ((data_in_TVALID_int_regslice == 1'b0) | ((icmp_ln144_1_reg_354 == 1'd1) & (input_r_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0 = ((data_in_TVALID_int_regslice == 1'b0) | ((input_r_full_n == 1'b0) & (icmp_ln144_2_reg_363 == 1'd1)));
end

always @ (*) begin
    ap_block_state5_pp0_stage4_iter0 = ((data_in_TVALID_int_regslice == 1'b0) | ((icmp_ln144_3_reg_372 == 1'd1) & (input_r_full_n == 1'b0)));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_output_cnt_4_reg_113 = 'bx;

assign ap_phi_reg_pp0_iter0_output_cnt_6_reg_124 = 'bx;

assign ap_phi_reg_pp0_iter0_output_cnt_8_reg_135 = 'bx;

assign data_in_TREADY = regslice_both_data_in_V_data_V_U_ack_in;

assign i_3_fu_296_p2 = (i_2_reg_325 + 19'd5);

assign icmp_ln134_fu_165_p2 = ((ap_sig_allocacmp_i_2 < 19'd324000) ? 1'b1 : 1'b0);

assign icmp_ln144_1_fu_205_p2 = (($signed(ap_phi_mux_output_cnt_2_phi_fu_106_p4) < $signed(32'd259200)) ? 1'b1 : 1'b0);

assign icmp_ln144_2_fu_240_p2 = (($signed(ap_phi_mux_output_cnt_4_phi_fu_116_p4) < $signed(32'd259200)) ? 1'b1 : 1'b0);

assign icmp_ln144_3_fu_275_p2 = (($signed(ap_phi_mux_output_cnt_6_phi_fu_127_p4) < $signed(32'd259200)) ? 1'b1 : 1'b0);

assign icmp_ln144_fu_171_p2 = (($signed(ap_sig_allocacmp_output_cnt_9) < $signed(32'd259200)) ? 1'b1 : 1'b0);

assign output_cnt_10_fu_189_p2 = (output_cnt_9_reg_330 + 32'd1);

assign output_cnt_11_fu_223_p2 = (output_cnt_2_reg_103 + 32'd1);

assign output_cnt_12_fu_258_p2 = (output_cnt_4_reg_113 + 32'd1);

assign output_cnt_13_fu_289_p2 = (output_cnt_6_reg_124 + 32'd1);

assign tmp_56_fu_250_p3 = {{trunc_ln143_2_fu_246_p1}, {tmp_14_reg_358}};

assign tmp_57_fu_281_p3 = {{data_in_TDATA_int_regslice}, {tmp_16_reg_367}};

assign tmp_fu_181_p3 = {{trunc_ln143_fu_177_p1}, {p_0_reg_340}};

assign tmp_s_fu_215_p3 = {{trunc_ln143_1_fu_211_p1}, {tmp_12_reg_349}};

assign trunc_ln143_1_fu_211_p1 = data_in_TDATA_int_regslice[31:0];

assign trunc_ln143_2_fu_246_p1 = data_in_TDATA_int_regslice[47:0];

assign trunc_ln143_fu_177_p1 = data_in_TDATA_int_regslice[15:0];

endmodule //conv2d_3x3_data_unpacket
